### ISSUE TITLE
一代需求：美国可以按邮编制作报价分区

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1]
美国可以按邮编制作报价分区（如邮编10001-10006对应的美国1区，系统支持把单个邮编拆分后（10001,10002,10003,10004,10005,10006）再维护分区基础数据及报价的分区邮编导入）

**Comment by WENLINRONG** [comment]
[美国邮编明细Zones for zip code by SP hub.xlsx](https://github.com/itdida/itdida-issues/files/1823656/Zones.for.zip.code.by.SP.hub.xlsx)

**Comment by iamforrest** [comment]
@WENLINRONG 是不是这份报价，有些分区是国家，有些分区是邮编？

**Comment by WENLINRONG** [comment]
只有按照邮编的分区或者只有按照国家的分区
如果选择为按邮编做分区时，肯定只有单一国家
现在只有美国 @iamforrest

**Comment by WENLINRONG** [comment]
已解决
