### ISSUE TITLE
众鑫通需求：收货录单新界面

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#10]
收货录单新界面
[收货录单新界面.pdf](https://github.com/itdida/itdida-issues/files/1823774/default.pdf)

**Comment by chenguolin123** [comment]
已解决 @WENLINRONG

**Comment by WENLINRONG** [comment]
@问题反馈：录单界面---扫描预报单号收货后，修改多件详情，运单要进入到待收货界面且基本界面的总件数，重量显示错误
![image](https://user-images.githubusercontent.com/37489976/37699305-f41cb7f4-2d21-11e8-802c-84113b86de90.png)
![image](https://user-images.githubusercontent.com/37489976/37699368-358acbd6-2d22-11e8-8eec-6410389af31f.png)
@chenguolin123

**Comment by WENLINRONG** [comment]
经测试，已解决
