### ISSUE TITLE
客户端---费用对账打开，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#100]
客户端---费用对账打开，系统报错
![image](https://user-images.githubusercontent.com/37489976/38466126-1169f8d8-3b57-11e8-9bd6-eb9e8fa5adec.png)

**Comment by WENLINRONG** [comment]
赶本周三发布

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
运单视图没有费用明细的数据 @tomlamcn 
![q q 20180411163801](https://user-images.githubusercontent.com/37489976/38605779-de481ab4-3da6-11e8-8bed-add5b0ea8ce9.png)

**Comment by tomlamcn** [comment]
@WENLINRONG
