### ISSUE TITLE
微信公众号的注册和绑定的新逻辑

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1001]
1. 每次进入微信公众号，要检查这个微信openid在中心库的用户表存在不存在，不存在的话，就自动根据当前的微信openID自动创建一个中心库的用户记录；

2. 每次进入微信公众号，如果发现这个中心用户没有绑定机构的（机构域名字段为空，或者机构userid为空，或者找不到有效的机构user记录，比如被删除，被假删除），就要进入绑定机构页面；

3. 绑定机构的页面，跟现在一样，输入域名，点击下一步，进入下一个页面；

4. 绑定机构的下一个页面，就是让用户输入登录账号（用户名/手机号/电子邮件）和密码，点击绑定。

5. 后台程序校验账号密码，如果不正确，提示失败和拦截；如果成功，更新中心库的机构域名和userid字段，完成绑定。

后续逻辑都不变了。

注意：这里的用户同时支持员工和客户端账号。因为这两者，其实在业务系统的用户表，是一个表来的。只是有个类型的字段来区分而已。

**Comment by casparthh** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
