### ISSUE TITLE
状态栏样式下掉，改善一下。不然客户没法操作。

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1003]
![581532753387_ pic_hd](https://user-images.githubusercontent.com/37174434/43355365-7212b1f6-928d-11e8-9da0-ac208c70d8b4.jpg)
还有这个排序也改一下
![2371532676392_ pic_hd](https://user-images.githubusercontent.com/37174434/43355750-74642c6c-9294-11e8-9645-6a79affa343a.jpg)

**Comment by WENLINRONG** [comment]
经测试，已解决
