### ISSUE TITLE
财务bug修复

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1005]
![2351532676009_ pic_hd](https://user-images.githubusercontent.com/37174434/43355741-3241f8b4-9294-11e8-8bfd-501ce00b2231.jpg)
![2361532676090_ pic_hd](https://user-images.githubusercontent.com/37174434/43355743-44b488d6-9294-11e8-801f-ea4bf4be3ded.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
