### ISSUE TITLE
统计分析---发货统计，按照单个代理查询时，查询的汇总数据跟明细错误，没有按照指定代理分统计汇总及统计分析界面数据及明细及统计分析所有界面统计的汇总数跟明细不准确 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1006]
1，统计分析---发货统计，按照单个代理查询时，查询的汇总数据跟明细错误，没有按照指定代理分统计汇总数据及明细
2，统计分析所有界面的数据统计不确认
![image](https://user-images.githubusercontent.com/37489976/43357245-10b23e30-92b1-11e8-867d-6e33968889e5.png)
![image](https://user-images.githubusercontent.com/37489976/43357274-81c04cf2-92b1-11e8-81d8-0a70aacd4b93.png)
![image](https://user-images.githubusercontent.com/37489976/43357291-d0a0c34c-92b1-11e8-8c2c-51cb3848a24d.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
