### ISSUE TITLE
打单录入 州/省

### ISSUE THREAD

**Issue by mrrc333** [itdida/itdida-issues#1009]
![71f69c38-bfc4-4dcc-b017-fe3ac03ad4b6](https://user-images.githubusercontent.com/25746597/43361806-49eb1332-930d-11e8-8bf9-746c163a33ec.png)

**Comment by mrrc333** [comment]
@WENLINRONG 就是改了下样式，把州/省移了个位置~ 测试下打单录入能否正常使用就可以了~

**Comment by WENLINRONG** [comment]
经测试，已解决
