### ISSUE TITLE
websocet改造

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1011]
为支持同账户同时登录做准备。回归测试点如下：

1. 导入预报看看状态条等正常不正常
2. 导入费用
3. 打单录入

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：导入费用，系统报错 
![image](https://user-images.githubusercontent.com/37489976/43364320-987c08c0-934a-11e8-92ea-ac3013215f47.png)
