### ISSUE TITLE
主界面支持自定义表头查询，其他界面尚未支持

### ISSUE THREAD

**Issue by chenguolin123** [itdida/itdida-issues#1013]
具体写法映象笔记有笔记，留待后续支持

**Comment by WENLINRONG** [comment]
@chenguolin123 问题反馈：等于不等于搜索不准确
![image](https://user-images.githubusercontent.com/37489976/43366717-cfa30cde-9374-11e8-95f7-f739508ee29d.png)

![image](https://user-images.githubusercontent.com/37489976/43366730-e51122cc-9374-11e8-811d-73c9290b6237.png)
