### ISSUE TITLE
角色权限---复制角色，提供报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1016]
![image](https://user-images.githubusercontent.com/37489976/43376296-87fc5430-93ec-11e8-981f-12cabf07bc08.png)
![image](https://user-images.githubusercontent.com/37489976/43376335-bdba32e0-93ec-11e8-83a0-8a9c374ebbbc.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
