### ISSUE TITLE
日常收支---收支登记的优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1018]
1，日常收支---收支登记的优化
2，科目实现可输可选

![--- qq 20180730114608](https://user-images.githubusercontent.com/37489976/43376615-4bef0d78-93ee-11e8-87ca-f20c8ed02487.jpg)
![image](https://user-images.githubusercontent.com/37489976/43394606-e03a6380-942d-11e8-830e-8355aa5a1f92.png)

**Comment by mrrc333** [comment]
@WENLINRONG
