### ISSUE TITLE
客户端---DIDA预报，批量修改，确认上网，确认签收的按钮隐藏 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1019]
![image](https://user-images.githubusercontent.com/37489976/43376677-aef51372-93ee-11e8-8c74-8df2330a4979.png)
![image](https://user-images.githubusercontent.com/37489976/43376714-e160e43a-93ee-11e8-9b02-880c621a407b.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
