### ISSUE TITLE
问题处理的按钮样式显示异常

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#102]
1，问题处理的按钮样式显示异常
![image](https://user-images.githubusercontent.com/37489976/38466218-6f499688-3b58-11e8-965b-ed151ec0e276.png),
2，待收货的界面显示异常
![image](https://user-images.githubusercontent.com/37489976/38477821-6a3a3e2e-3be7-11e8-9711-6ead7faf5232.png)

**Comment by tomlamcn** [comment]
下次发布后可以测试。不行清缓存

**Comment by WENLINRONG** [comment]
经测试，已解决
