### ISSUE TITLE
银行账户列表的备注栏自动记录收付款撤销审核时的金额跟对应的流水号

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1020]
银行账户列表的备注栏自动记录收付款撤销审核时的金额跟对应的流水号
![qq 20180730115242](https://user-images.githubusercontent.com/37489976/43376862-a9ae9770-93ef-11e8-864d-600edd81dbec.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认
