### ISSUE TITLE
银行流水表界面的字段ID重复

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1024]
银行流水表界面的字段ID重复
![id qq 20180730144844](https://user-images.githubusercontent.com/37489976/43381659-e666c6d4-9407-11e8-9dd6-1339ca5aeafd.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
