### ISSUE TITLE
客户端及客户档案优化

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1030]
这个不显示的先去掉。
![image](https://user-images.githubusercontent.com/37174434/43387892-4420c5c4-941a-11e8-828a-9d5fcdc7bfed.png)
下面的是优化修改。
![image](https://user-images.githubusercontent.com/37174434/43387404-ee35309c-9418-11e8-9c76-d84114dc57c3.png)
![image](https://user-images.githubusercontent.com/37174434/43387525-402cb1cc-9419-11e8-97de-ac43bc003d17.png)

麻烦导出也改一下，增加这两列。
![451533020370_ pic_hd](https://user-images.githubusercontent.com/37174434/43451029-95080a52-94e6-11e8-970b-397c540cfef7.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认，倒数第二个图里面所说的职位其实是部门
