### ISSUE TITLE
预报录单保存后，运单数据进入到已预报界面，确认收货，客户的预估余额没有抵扣 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#104]
预报录单保存后，运单数据进入到已预报界面，确认收货，客户的预估余额没有抵扣

**Comment by WENLINRONG** [comment]
![qq 20180409105423](https://user-images.githubusercontent.com/37489976/38477341-ae0ea160-3be4-11e8-992f-e742ee605390.png)

**Comment by iamforrest** [comment]
@WENLINRONG @chenguolin123 陈国林目前就在处理这个问题
