### ISSUE TITLE
发货批号列表，退货批号列表，收货批号列表改成弹窗模式

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1041]
发货批号列表，退货批号列表，收货批号列表改成弹窗模式
1，双击弹窗,
2，下面有个按钮，“查看明细”，点击可以查看所选包号的所有明细（可多个包号）
3，明细弹出框跟expand出来的差不多，有明细和汇总即可。
![image](https://user-images.githubusercontent.com/37489976/43453623-1b6b981a-94ed-11e8-9df6-a6e243d29748.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
