### ISSUE TITLE
问题通知经常滞后，或者收不到 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1058]
问题通知经常滞后，或者收不到 
![qq 20180802110657](https://user-images.githubusercontent.com/37489976/43560298-5dc21eb6-9644-11e8-9fe0-9d16d3f3512e.png)

**Comment by casparthh** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
