### ISSUE TITLE
总账表界面的 银行账户，客户账户，代理账户----只要有撤销审核的的，走着走着余额就不对了，撤销的数据双击也打不开，凡是撤销的要对应的加备注跟生成 负数金额，且收付款单的状态跟对账金额 状态也要对应的标注撤销类型

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1059]
总账表界面的 银行账户，客户账户，代理账户----只要有撤销审核的的，走着走着余额就不对了，撤销的数据双击也打不开，凡是撤销的要对应的加备注跟生成 负数金额，且收付款单的状态跟对账金额 状态也要对应的标注撤销类型
![image](https://user-images.githubusercontent.com/37489976/43562797-54e340f6-9651-11e8-9ae4-9285e8de9e5a.png)

**Comment by iamforrest** [comment]
我只做了衔接，其他的你重新整理一个清单出来，新git出来

**Comment by WENLINRONG** [comment]
经测试，已解决
