### ISSUE TITLE
确认预报，确认收货，确认发货时，乐递突然就卡死

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#106]
确认预报，确认收货，确认发货时，乐递突然就卡死
![image](https://user-images.githubusercontent.com/37489976/38490821-b6382022-3c1c-11e8-9674-2c311f2ef2bd.png)

**Comment by tomlamcn** [comment]
[itdida-web.2018-04-09.32.log.tar.gz](https://github.com/itdida/itdida-issues/files/1889366/itdida-web.2018-04-09.32.log.tar.gz)
48849 这行开始有报错。

**Comment by tomlamcn** [comment]
@iamforrest

**Comment by iamforrest** [comment]
@WENLINRONG 需要测试费用重算，运单倒入，导出，运单批量确认排货等等

**Comment by WENLINRONG** [comment]
导入200票，还是会卡死 @iamforrest

**Comment by iamforrest** [comment]
@tomlamcn @WENLINRONG 这其实和之前的是两个问题来的，之前的那个是死锁问题，不是真的死了。现在这个导入的问题，是整个服务器挂掉了。请新开一个issue去跟进，并且林锦斌拿出死的的日志（我估计有outofmemeory之类的错误信息）
