### ISSUE TITLE
主界面，搜索单号后，界面跳到了待发货界面，界面的操作按钮显示的是全部界面的按钮

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1061]
主界面，搜索单号后，界面跳到了待发货界面，界面的操作按钮显示的是全部界面的按钮
![image](https://user-images.githubusercontent.com/37489976/43566477-1cb0da6c-9661-11e8-89af-d27263e40450.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
