### ISSUE TITLE
打单录入页面优化

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1063]
打单录入4个问题
1-输入框加宽
2-输入框位置排版
3-申报信息列表，品名行位排列要固定，不能随机变行，比如录入的时候第一行品名A第二行B，下次查看保持这个排列
4-联邦打印对接

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by tomlamcn** [comment]
还需要作些微调：@mrcc333 @WENLINRONG 
![image](https://user-images.githubusercontent.com/37174434/43754653-82ca4d84-9a3e-11e8-8731-9bcf168ff8d2.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
