### ISSUE TITLE
应收财务事务重构

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1065]
1. 应收财务的操作都回归一下，包括费用的对账，审核，撤销等等，收款单的对账，审核，撤销
2. 同时两个账号一起点击操作同一个按钮，同个数据，看看有没有异常。
3. 同时两个账号一起点击操作同一个按钮，不同个费用或者收款单，看看有没有异常。

**Comment by WENLINRONG** [comment]
经测试，已解决
