### ISSUE TITLE
承运商----英文：SAGAWA的轨迹抓取

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1068]
英文：SAGAWA
中文：佐川急便
http://k2k.sagawa-exp.co.jp/p/web/okurijosearch.do#detail-1
参考单号：355785862681

**Comment by WENLINRONG** [comment]
![qq 20180802170433](https://user-images.githubusercontent.com/37489976/43574851-bf07cec4-9634-11e8-8b3c-b48939865d89.jpg)

**Comment by johnnyZchan** [comment]
@wny123 @WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
