### ISSUE TITLE
财务导出排序

### ISSUE THREAD

**Issue by chenguolin123** [itdida/itdida-issues#1076]

**Comment by WENLINRONG** [comment]
@chenguolin123 问题反馈：应收财务导出的还是个界面看到的顺序不一样 
![image](https://user-images.githubusercontent.com/37489976/43593009-619210ea-96a9-11e8-9e9d-5efc8453e494.png)
****
![image](https://user-images.githubusercontent.com/37489976/43593061-8528786e-96a9-11e8-8161-db6a7170aee4.png)
