### ISSUE TITLE
微信问题通知优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1093]
1.微信端收到问题通知：单号=SY0001805，问题标题=【不锈钢类（空运）】；在pc端查看该运单没有这个标题的问题件
2.在pc端新建问题件，选择通知人为该运单关联的【业务员、销售客服、港前客服、港后客服、应收财务、应付财务】，这些人的微信端都收不到问题通知；测试单号9180705127033
![qq 20180803183028](https://user-images.githubusercontent.com/37489976/43638420-489243e4-9708-11e8-88ae-c62f1f969627.jpg)

**Comment by casparthh** [comment]
运单9180705127033 有三个问题件，分别分通送给 （13528783002,13528783003,13798512217）
select * from tong_zhi_lie_biao where wen_ti_jian_id in (select id from wen_ti_jian where yun_dan_id = 'fe15c110d47e448aa2e341e9663d7475') order by wen_ti_jian_id;



这些收件人手机号中只有一个账号有绑定公众号
select * from itdida_center.zhong_xin_yong_hu where shou_ji_hao_ma in ('13528783003','13528783002','13798512217');

id	shou_ji_hao_ma	openid	nickname	current_domain	lei_xing	yong_hu_id
d31713f618d44b5c9de451f5c07d04de	13528783003	otTSUwpG2I1JkRpEMPTrmC3GsBUo	%E6%95%8F	ledii	2	5ffb4690be4243dd9a4f6ce63b6c09a4

所以该问题件只有13528783003能收到。

**Comment by WENLINRONG** [comment]
经测试，已解决
