### ISSUE TITLE
总账表，客户单档案实现所见即所得，导出列表上所以显示字段（现在导出的字段不全，只能导出部分字段）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1099]
总账表，客户单档案实现所见即所得，导出列表上所以显示字段

**Comment by WENLINRONG** [comment]
![image](https://user-images.githubusercontent.com/37489976/43672084-e7174b60-97d8-11e8-9a94-f3d3b1100c3d.png)
![image](https://user-images.githubusercontent.com/37489976/43672097-25b627f6-97d9-11e8-8899-8aae01ad03e0.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
