### ISSUE TITLE
扫单助手-包/板号、批号生成方式优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#11]
扫单助手-包/板号、批号生成方式优化
![qq 20180319131730](https://user-images.githubusercontent.com/37489976/37579197-f17347e4-2b77-11e8-9f8d-faa03e2435f9.jpg)

**Comment by WENLINRONG** [comment]
扫单助手包号的优化问题汇总：
1，包号覆盖，列表数据没有即时刷新。
![qq 20180320172643](https://user-images.githubusercontent.com/37489976/37646197-f3a51078-2c63-11e8-8bb4-583a96d40696.png)
2，点代理的分组，代理按钮会消失不见
3，未知的要在分组列表顶置显示
4，选中的运单要汇总

**Comment by WENLINRONG** [comment]
@likeasb 
![qq 20180320172817](https://user-images.githubusercontent.com/37489976/37646445-adf4da6c-2c64-11e8-9b0f-fb2484ddf8e4.png)
![qq 20180320172924](https://user-images.githubusercontent.com/37489976/37646462-b819769c-2c64-11e8-979e-69e770410e94.jpg)

**Comment by WENLINRONG** [comment]
![qq 20180320173058](https://user-images.githubusercontent.com/37489976/37646606-0dbc1bea-2c65-11e8-8144-154bb9fa58e0.png)

**Comment by iamforrest** [comment]
@WENLINRONG 请测试

**Comment by WENLINRONG** [comment]
问题反馈：4，选中的运单要汇总 @tomlamcn

**Comment by iamforrest** [comment]
这个可以抄，应收应付财务。

**Comment by WENLINRONG** [comment]
汇总的还在处理

**Comment by WENLINRONG** [comment]
经测试，已解决
