### ISSUE TITLE
不勾选欠费方式，将永不欠费

### ISSUE THREAD

**Issue by chenguolin123** [itdida/itdida-issues#1105]

**Comment by chenguolin123** [comment]
不勾选欠费方式，将永不欠费 #1105

**Comment by WENLINRONG** [comment]
![image](https://user-images.githubusercontent.com/37489976/43674982-bdd6cf9c-980e-11e8-81bd-3c73b07eb1e3.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
