### ISSUE TITLE
财务操作回归

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1112]
应收财务和应付财务都要测试：
1. 费用的各种操作：对账->核销-....；以及反过来撤销等操作；
2. 收款单的各种操作，审核，撤销审核，登记并直接审核
3. 以上各种批处理操作也需要测试一下

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：应收财务，应付财务，导出对账单的倒三角按钮点开，数据展开不了（客户端也一样）
![image](https://user-images.githubusercontent.com/37489976/43684118-b6c6d1a2-98cc-11e8-95e5-acadf36b353b.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
