### ISSUE TITLE
客户流水账，代理水流账撤销核销审核的明细双击数据弹不出明细

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1117]
1，客户流水账，代理水流账撤销核销审核的核销金额双击数据弹不出明细
2，客户流水账，代理水流账撤销核销审核的收款金额数据弹不出明细

![image](https://user-images.githubusercontent.com/37489976/43686602-38b8aa9a-98fb-11e8-83af-21edfd73da9c.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
