### ISSUE TITLE
系统做客户单号唯一的判定及拦截（主界面的转单号不能多行过滤查询 ）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1140]
系统做客户单号唯一的判定及拦截（主界面的转单号不能多行过滤查询 ）

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
问题反馈：
@johnnyZchan 
客户单号重复的，要提示客户单号已存在
![qq 20180816184908](https://user-images.githubusercontent.com/37489976/44204452-1cece200-a142-11e8-8f2e-8ca38851bf3a.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG  已修正，请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
