### ISSUE TITLE
api删除运单接口，运单状态仅在【已预报】才可以

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1145]
1- api删除运单接口，运单状态仅在【已预报】才可以 
2-要验证登录账号，运单对应的客户编号与登录账号对应才可以

**Comment by wny123** [comment]
增加
1.可删除状态=已预报运单接口，提交客户单号，判断与登录账号的客户编号是否对应
2.转单号查询接口，提交客户单号--返回转单号码，判断与登录账号的客户编号是否对应

**Comment by johnnyZchan** [comment]
@wny123 @WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
