### ISSUE TITLE
问题件---问题处理界面回复不了问题件且双击问题件，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1159]
问题件---问题处理界面回复不了问题件且双击问题件，系统报错
![qq 20180809123637](https://user-images.githubusercontent.com/37489976/43878334-0d77d578-9b8e-11e8-9000-0ea1361b6371.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
