### ISSUE TITLE
收支登记登记界面增加对象的输入，可以切换输入客户或者代理且不会跟客户或者代理的余额发生关系，只进入一笔银行流水的收入或者支出（客户押金对应的是收入，代理押金对应的是支出 ）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1161]
收支登记登记界面增加对象的输入，可以切换输入客户或者代理且不会跟客户或者代理的余额发生关系，只进入一笔银行流水的收入或者支出（客户押金对应的是收入，代理押金对应的是支出 ）
![image](https://user-images.githubusercontent.com/37489976/43895591-6a838828-9c08-11e8-8b9a-80f183027942.png)

**Comment by wny123** [comment]
对象是：客户
对象名称=客户名称
对象是：代理
对象名称=代理名称
对象是：分公司
对象名称=分公司名称
 对象是：其它
对象名称=随便写入
