### ISSUE TITLE
问题件界面增加批量通知按钮

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1175]
问题件界面增加批量推送微信通知按钮
![image](https://user-images.githubusercontent.com/37526066/43969663-77b81ae0-9cfd-11e8-8184-c9b47540fb27.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
