### ISSUE TITLE
超长超重附加费达不到最低消费的不会按照最低消费计算费用

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1178]
超长超重附加费达不到最低消费的不会按照最低消费计算费用
![image](https://user-images.githubusercontent.com/37489976/43967324-b4acb7e6-9cf6-11e8-9197-0fa4a77a505e.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
