### ISSUE TITLE
客户档案修改了什么 就插一条日志 （类似于运单日志）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1180]
运单 基本现在不是有个日志
客户档案也做个类似的。
把原来的岗位变更可以不要，也一样加到日志就可以。
客户档案修改了什么 就插一条日志 。
岗位变了，扣货额度 打了勾的，或者改了的。都加到日志

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认
