### ISSUE TITLE
如果运单修改了客户，岗位应该也要做相对的改动

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1187]
岗位包括：应收财务，应付财务，港前，港后，客服，业务员
（如果以上有遗漏请指正）

我已经部署到测试环境，直接测试即可

@WENLINRONG

**Comment by WENLINRONG** [comment]
问题反馈：修改客户，提交保存，系统报错
![qq 20180811211445](https://user-images.githubusercontent.com/37489976/43992087-a5419708-9dab-11e8-8c09-88ff03f88404.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
