### ISSUE TITLE
运单报表导出的明细

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1191]
1.运单列表增加显示字段并可以导出excelimage
![image](https://user-images.githubusercontent.com/37489976/43998813-456347b0-9e31-11e8-848d-f49279255105.png)

2.导出的excel按报表名称自动命名，每个报表导出一个excel文件

3.每票运单明细增加显示字段，不需要导出
image
![image](https://user-images.githubusercontent.com/37489976/43998822-74b14454-9e31-11e8-84c6-22b7962d26d8.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
