### ISSUE TITLE
零费用的附加逻辑

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1205]
测试一下
1. 只有发了货的运单，才会自动添加0费用
2. 只有收了货的运单，才会自动添加0费用

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
确认收货，确认发货，针对无服务的反而不会生成零的费用
![qq 20180813231446](https://user-images.githubusercontent.com/37489976/44040916-07fd1800-9f4f-11e8-9d49-94df00a70ad2.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
