### ISSUE TITLE
应付财务界面的数据底色标识错误，只有待对账的数据才标识紫色

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#121]
应付财务界面的数据底色标识错误，只有待对账的数据才标识紫色
![qq 20180410185930](https://user-images.githubusercontent.com/37489976/38553321-7cbc9be0-3cf1-11e8-82af-9acfbb8f0f25.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
