### ISSUE TITLE
在app该运单未封包，还有第二种情况

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1216]
在app该运单未封包，还有第二种情况
1.一票多件
2.扫第一件到包号中
3.再次扫入其它，都会提示为：该运单未封包，无法扫入

**Comment by mrrc333** [comment]
![919d2f9bad7e960cbc7bca1363ee07a2](https://user-images.githubusercontent.com/25746597/44138860-df92016e-a0a7-11e8-849a-b5e9105b8b42.jpg)
暂时挂起，等重现后再处理..
现在的app扫入，不会改变包号状态的，代码里也没相应的逻辑~ 现在的逻辑是扫单助手设置了包号限制并且未封包才提示这个，和一票多件没啥关系…
