### ISSUE TITLE
代理档案界面，余额没显示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#122]
1，代理档案界面，余额没显示
![qq 20180411110538](https://user-images.githubusercontent.com/37489976/38594349-6aa1197c-3d78-11e8-89d7-c87e11fe750a.png),
2，欠费状态显示空白
![qq 20180411110802](https://user-images.githubusercontent.com/37489976/38594428-c32ff310-3d78-11e8-8188-675e0b5c64bf.png)

**Comment by tomlamcn** [comment]
@WENLINRONG
