### ISSUE TITLE
确认收货的对话框左下角要有这个记忆

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1221]
确认收货的对话框左下角要有这个记忆：

有安装客户端套件的电脑： 直接打印（打印机名/模版名称）
没安装客户端套件的电脑：下载（模版名称）

有打勾：确认收货—》直接打印出纸或者下载
没打勾：确认收货—》跳转到模版选择框，重选模版和打印机，在模板选择框点【确认】继续打印出纸或者下载
![image](https://user-images.githubusercontent.com/37489976/44132091-a9f71724-a089-11e8-9854-fc791d7b3525.png)

**Comment by mrrc333** [comment]
@WENLINRONG
