### ISSUE TITLE
 一代正式环境： 单号：7150889480  ，已选择退所有费用，但未退费用。 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1224]
一代正式环境： 单号：7150889480  ，已选择退所有费用，但未退费用。 

![qq 20180815150759](https://user-images.githubusercontent.com/37489976/44135763-f87bcabe-a059-11e8-912b-8be545be99c9.png)

**Comment by mrrc333** [comment]
![36e89ff10febffe7d54cb29cc88a05f0](https://user-images.githubusercontent.com/25746597/44138788-9e6a6532-a0a7-11e8-95d2-2a0c0872ded8.jpg)
如图所示，费用是退了的~

**Comment by WENLINRONG** [comment]
经测试，已解决
