### ISSUE TITLE
hkdhl查件

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1239]
hkdhl查件
 1.设置收邮件邮箱
2.拿一票已签收的hkdhl填写上来提交，
3.看看是否正常接收邮件
4.是否自动将收到的邮件生成对应单号的港后问题件

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

注意点：1、有SQL需要执行；
               2、机器人项目要更新发布；
               3、查件邮箱的密码需要去对应的邮箱申请授权码

**Comment by WENLINRONG** [comment]
经测试，已解决
