### ISSUE TITLE
主界面，应收财务，应付财务，报价管理界面牵涉到批量操作，增，删，改的操作按钮加上小菊花

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1241]
主界面，应收财务，应付财务，报价管理界面牵涉到批量操作，增，删，改的操作按钮加上小菊花
(确认预报，确认收货，确认排货，确认发货，批量修改，重算应收，重算应付，重算销售，确认对账，确认对账审核，费用登记，确认核销，确认核销审核，重算费用）

**Comment by WENLINRONG** [comment]
![qq 20180817112422](https://user-images.githubusercontent.com/37489976/44246774-8830c580-a1cf-11e8-9402-2b459bd28018.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
