### ISSUE TITLE
客户端-用户端：运费试算的界面排版优化 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1264]
用户端运费试算的界面样式 
<img width="1440" alt="qq 20180820130421" src="https://user-images.githubusercontent.com/37489976/44321308-ced42900-a436-11e8-8aac-52ca6331515a.png">

**Comment by wny123** [comment]
客户端运费试算样式
![image](https://user-images.githubusercontent.com/37526066/44614003-9629ba80-a84f-11e8-92c9-802fc175f2d1.png)
@ @likeasb 
这个较急
