### ISSUE TITLE
应收财务，应付财务双击运单，基本右侧栏要置顶

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1272]
应收财务，应付财务双击运单，基本右侧栏要置顶
![qq 20180821000508](https://user-images.githubusercontent.com/37489976/44352126-15c52b80-a4d6-11e8-9ddc-a3131e4e8cbb.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
