### ISSUE TITLE
重构 NotificationRobot

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1279]
帮忙把NotificationRobot 从轮询改为 mq监听，去掉那个 tong_zhi_lie_biao 这表，去掉延迟。
1. 改写 NotificationRobot
2. 删掉tong_zhi_lie_biao 并把所有插入该表的代码换成推送MQ

**Comment by casparthh** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
