### ISSUE TITLE
打单录入界面的地址验证是RESIDENTIAL时，自动产生港前问题

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1280]
打单录入界面的地址验证是RESIDENTIAL时，自动产生港前问题
![residential qq 20180821153404](https://user-images.githubusercontent.com/37489976/44388537-d8818d80-a517-11e8-9f82-0f550d8a7b70.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
