### ISSUE TITLE
日志提示修正一下。

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1283]
![118491534836256_ pic_hd](https://user-images.githubusercontent.com/37174434/44391604-e0b2ea80-a562-11e8-9e84-dba1ac30d4f3.jpg)
如图，改渠道是不支持包裹袋的，但是日志提示的是重量段的提示。她们希望可以把该渠道
不支持包裹袋的提示提示出来，而不是提示重量段。
应该是包裹类型是wpx才对。
![118501534836256_ pic_hd](https://user-images.githubusercontent.com/37174434/44391614-e7416200-a562-11e8-9e08-2c2c3696c01b.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
