### ISSUE TITLE
客户端的录单界面增加邮编和城市的验证。

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1285]
![333333](https://user-images.githubusercontent.com/37174434/44392100-fa086680-a563-11e8-9f16-5c2d618e2a85.png)
下面的详细录入也需要改成对应的限制条件。
![55555555](https://user-images.githubusercontent.com/37174434/44392157-2623e780-a564-11e8-977c-28a85cf92629.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
