### ISSUE TITLE
手动新建，写入问题名称时一定要往回删除一个汉字，才能正常查找

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1286]
手动新建，写入问题名称时一定要往回删除一个汉字，才能正常查找

**Comment by WENLINRONG** [comment]
![qq 20180821170428](https://user-images.githubusercontent.com/37489976/44392709-59de1d80-a522-11e8-8f92-0b008631aa56.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
