### ISSUE TITLE
客户端用快捷建（CTRL+Y）查询报价，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1291]
客户端用快捷建查询报价，系统报错
![qq 20180822103820](https://user-images.githubusercontent.com/37489976/44439804-cdc90600-a5b4-11e8-9a6c-16c07efdd0a9.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
