### ISSUE TITLE
客户端的报价管理界面切换系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1292]
客户端的报价管理界面切换系统报错
![qq 20180822112908](https://user-images.githubusercontent.com/37489976/44441379-c0634a00-a5bb-11e8-824e-ac88b417d8e2.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
