### ISSUE TITLE
客户端的报价管理界面增加权限且隐藏报价名称

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1295]
客户端的报价管理界面增加权限且隐藏报价名称
![image](https://user-images.githubusercontent.com/37489976/44451192-99d9f900-a625-11e8-8c75-7d8736747e2d.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
