### ISSUE TITLE
微信公众号的优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1296]
一、进行中的运单查询，加载运单
![image](https://user-images.githubusercontent.com/37489976/44453444-a6f9e680-a62b-11e8-95a9-7f50fdb018ff.png)
二、收到问题通知，点击直接进入问题查看和回复界面
![image](https://user-images.githubusercontent.com/37489976/44453471-afeab800-a62b-11e8-950a-e2692256c3fc.png)
三、运单查询列表，运单不是问题件的时候，要显示为最新轨迹描述和时间地点
![image](https://user-images.githubusercontent.com/37489976/44453507-bf6a0100-a62b-11e8-81f7-1112018e1ad4.png)
四、正式切换机构报错
![image](https://user-images.githubusercontent.com/37489976/44453527-cbee5980-a62b-11e8-8e50-ed1f93d6a6c2.png)

**Comment by casparthh** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试。已解决
