### ISSUE TITLE
问题中心默认选中未跟进

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1297]
问题中心默认选中未跟进
![qq 20180822165406](https://user-images.githubusercontent.com/37489976/44453619-1243b880-a62c-11e8-88bf-ea8d11b05e75.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
问题反馈： @mrrc333

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
