### ISSUE TITLE
客户端的姓名后面显示的预估余额现在只有显示rmb的，需要增加hkd和usd

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1298]
![120631534920003_ pic_hd](https://user-images.githubusercontent.com/37174434/44453735-6babe780-a62c-11e8-8021-66f02330d7e0.jpg)
![120641534920004_ pic_hd](https://user-images.githubusercontent.com/37174434/44453737-6c447e00-a62c-11e8-9ddf-d06e9e7e6aed.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
