### ISSUE TITLE
用户端默认显示收货录单且优化收货问题件的报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1299]
用户端默认显示收货录单且优化收货问题件的报错
![qq 20180822172322](https://user-images.githubusercontent.com/37489976/44455289-3d300b80-a630-11e8-9376-0dcb4d34f13c.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
