### ISSUE TITLE
总账表-客户账户-未对账金额双击查看明细

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1315]
总账表-客户账户-未对账金额双击查看明细，
1.导出按钮被挤走，要翻滚至最底部才能看到
2.点导出，无需选中可直接导出
![- - qq 20180824173704](https://user-images.githubusercontent.com/37489976/44577689-48468100-a781-11e8-9d9e-e833591e6a38.png)
![qq 20180824173750](https://user-images.githubusercontent.com/37489976/44577782-71ffa800-a781-11e8-9262-85e036ce9522.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
