### ISSUE TITLE
回归测试费用信息同步

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1330]
我优化了一下费用同步的机制和性能，麻烦回归测试一下，测试方法如下：

1. 费用添加或者重算之后，看看费用有没有进财务，客户端单号之类有没有变成跟运单一样
2. 运单修改了操作状态，客户单号之类的，看看费用表有没有相应变化

**Comment by WENLINRONG** [comment]
经测试，已解决
