### ISSUE TITLE
统计分析所有界面的导出没有明细表

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1334]
统计分析的导出没有明细表
![qq 20180827142056](https://user-images.githubusercontent.com/37489976/44643831-7ca88000-a9c1-11e8-91bd-55993c67ada1.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：成本分析查询不了，也导出不了
![image](https://user-images.githubusercontent.com/37489976/45585526-5c147b80-b918-11e8-9761-c474ad9edac5.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
点导出还是不行，这是修好了的，现在又不行了
![image](https://user-images.githubusercontent.com/37489976/45917174-4ff26600-bea4-11e8-842f-a3fd6a5f27b8.png)

**Comment by mrrc333** [comment]
@WENLINRONG 这个也是之前测好了的，忘记转你了，直接关闭即可

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
经测试，已解决
