### ISSUE TITLE
导入预报增加一栏备注导入

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1344]
导入预报增加一栏备注导入

**Comment by WENLINRONG** [comment]
![qq 20180828141640](https://user-images.githubusercontent.com/37489976/44704898-8a770780-aa8c-11e8-9d4d-87d3303ce220.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
