### ISSUE TITLE
统计分析增加销售业绩统计

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1345]
统计分析增加销售业绩统计
![qq 20180828172522](https://user-images.githubusercontent.com/37489976/44714254-66bfbb80-aaa4-11e8-94af-cc66f6bc0006.jpg)

**Comment by WENLINRONG** [comment]
![qq 20180828142126](https://user-images.githubusercontent.com/37489976/44704928-9b277d80-aa8c-11e8-82fe-74f5c4085f73.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
客户数量没数据
![qq 20180915195658](https://user-images.githubusercontent.com/37489976/45585989-a3533a00-b921-11e8-94c2-b53fc4d3c4e4.png)

**Comment by mrrc333** [comment]
@WENLINRONG
