### ISSUE TITLE
捷美达微信登录异常

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1351]
捷美达微信登录异常
![qq 20180828171056](https://user-images.githubusercontent.com/37489976/44713297-62929e80-aaa2-11e8-9fe0-d25810506075.png)

**Comment by WENLINRONG** [comment]
[[超长消息]28-Aug-2018.pdf](https://github.com/itdida/itdida-issues/files/2327352/28-Aug-2018.pdf)

**Comment by mrrc333** [comment]
@WENLINRONG
