### ISSUE TITLE
收货独立界面优化

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1361]
一、主界面
![image](https://user-images.githubusercontent.com/37526066/44791003-3dea1400-abd3-11e8-92a3-a4d769bd8d05.png)
二、录入界面细节
a.快递专线
![image](https://user-images.githubusercontent.com/37526066/44791063-63771d80-abd3-11e8-9d25-048c57df28ea.png)
b.快递包裹
![image](https://user-images.githubusercontent.com/37526066/44791125-843f7300-abd3-11e8-8dc9-460d01eee9ba.png)
c.邮政小包
![image](https://user-images.githubusercontent.com/37526066/44791161-97ead980-abd3-11e8-9fd0-c790796fdf89.png)
三、完整列表
a.重量列表
![image](https://user-images.githubusercontent.com/37526066/44791249-c8cb0e80-abd3-11e8-8945-c3f35d9f5846.png)
b.运单列表
![image](https://user-images.githubusercontent.com/37526066/44791301-e304ec80-abd3-11e8-8b96-efd019f7a549.png)
四、操作细节
1.在顶部框扫入
A.无预报：将单号填写入客户单号
光标到达客户框，自动显示上一次选中的客户
B.有预报：
客户有：判断客户与上一次是否相符，相同则继续
客户无：加载客户信息
加载重量以外的所有信息
光标直接到重量录入框，
判断重量值
从电子称读数，稳定>0，直接保存
手动录入，回车直接保存
2.红色数字标为回车顺序
3.根据报价提示，国家、包裹类型、重量：是否有服务
4.运单修改：从右边列表选中运单，全部加载左边操作区，可修改
5.播音：
国家：写入即时播报
重量：计费重写入即时播报
6.录入框白底色的才可录入
7.有预报运单，扫入收货后要保持子单号码不变
因有有些子单号标签可能是客户已经贴好
五、边框尺寸
![image](https://user-images.githubusercontent.com/37526066/44791397-1e9fb680-abd4-11e8-8e02-6bf565f7e73e.png)

**Comment by wny123** [comment]
![image](https://user-images.githubusercontent.com/37526066/44967869-d0453b80-af76-11e8-802c-1384cb5bbb25.png)
@ @chenguolin123

**Comment by WENLINRONG** [comment]
经测试，已解决
