### ISSUE TITLE
统计分析界面增加日常收支分析

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1365]
统计分析界面增加日常收支分析
![qq 20180830121815](https://user-images.githubusercontent.com/37489976/44829332-c5ec1000-ac0b-11e8-96d1-eb93326b3060.jpg)
日常收支的结果分析
![qq 20180830121900](https://user-images.githubusercontent.com/37489976/44829344-e1efb180-ac0b-11e8-92aa-6f20d9de659a.jpg)
日常收支的明细汇总表

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
