### ISSUE TITLE
客户档案的操作日志缺少了老的值（欠费判定修改后，日志经常没记录完 ）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1372]
客户档案的操作日志缺少了老的值（欠费判定修改后，日志经常没记录完 ）

**Comment by WENLINRONG** [comment]
![qq 20180830165933](https://user-images.githubusercontent.com/37489976/44841583-39554800-ac33-11e8-9039-82640a45d60d.png)

**Comment by tomlamcn** [comment]
我改了额度有日志

**Comment by WENLINRONG** [comment]
经测试，已解决
