### ISSUE TITLE
EXCEL导入预报后，确认收货，系统没有记录收货日志，且收货站点跟收货位置显示空白

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#138]
EXCEL导入预报后，确认收货，系统没有记录收货日志，且收货站点跟收货位置显示空白
![excel qq 20180413102804](https://user-images.githubusercontent.com/37489976/38713851-0057784c-3f06-11e8-8dbf-6b9528f09d44.png)

**Comment by iamforrest** [comment]
@mrrc333 帮我看看什么问题

**Comment by WENLINRONG** [comment]
经测试，已解决
