### ISSUE TITLE
系统参数---录单限制增加件数，包裹类型，货物特性的参数

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1380]
系统参数---录单限制增加件数，包裹类型，货物特性的参数

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
1，设置限制条件后，没有拦截（新收货录单界面，预报确认收货）
![image](https://user-images.githubusercontent.com/37489976/45154568-8aa0a100-b20a-11e8-9431-25488ca5a677.png)
![image](https://user-images.githubusercontent.com/37489976/45154581-9b511700-b20a-11e8-96d3-b88954d718dc.png)

**Comment by mrrc333** [comment]
@WENLINRONG
