### ISSUE TITLE
费用折算金额显示错误

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1382]
费用折算金额显示错误

**Comment by WENLINRONG** [comment]
![qq 20180831105840](https://user-images.githubusercontent.com/37489976/44890457-e37faf00-acc9-11e8-874d-df20471ee4b3.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
