### ISSUE TITLE
代理档案的左侧栏输入关键字搜索，敲回车,报UI错误

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1388]
代理档案的左侧栏输入关键字搜索，敲回车,报UI错误
![image](https://user-images.githubusercontent.com/37489976/44901446-fc27ad80-ad39-11e8-9e0a-ef4f01346ba9.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
