### ISSUE TITLE
应收财务，应付财务的费用视图，运单视图的汇总数据的原币种数据显示错误

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#139]
应收财务，应付财务的费用视图，运单视图的汇总数据的原币种数据显示错误
![image](https://user-images.githubusercontent.com/37489976/38715446-b01a8470-3f0d-11e8-8317-60615f85309b.png)

**Comment by WENLINRONG** [comment]
赶下一个版本发布

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
汇总还是不对 @tomlamcn

**Comment by tomlamcn** [comment]
昨天改了，看看行不行@WENLINRONG

**Comment by WENLINRONG** [comment]
@tomlamcn 原币种汇总显示错误

**Comment by WENLINRONG** [comment]
经测试，已解决
