### ISSUE TITLE
基本界面单独修改发货计费重修改不了 （发货计费重从7KG修改到5.5KG，会自动变回7KG）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1390]
基本界面单独修改发货计费重修改不了 （发货计费重从7KG修改到5.5KG，会自动变回7KG）
![7kg 5 5kg 7kg qq 20180831170704](https://user-images.githubusercontent.com/37489976/44903912-48a0c800-acfd-11e8-82b1-55241bec2e0c.png)

**Comment by mrrc333** [comment]
@WENLINRONG
