### ISSUE TITLE
已预报界面双击查看详情，再关闭详情，确认收货后，详情会自动弹出

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1399]
已预报界面双击查看详情，再关闭详情，确认收货后，详情会自动弹出
![qq 20180901120504](https://user-images.githubusercontent.com/37489976/44942213-7eb67880-addf-11e8-85b5-fcb0570184f0.jpg)

**Comment by wny123** [comment]
如果在确认收货、确认发货、导出，这些操作之前有曾经打开某一票运单详情。做这些操作都会自动将运单详情开启。

**Comment by mrrc333** [comment]
@WENLINRONG
