### ISSUE TITLE
触发器的触发环节勾了费用相关，运单修改后，有费用产生但没有触发问题件

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#140]
触发器的触发环节勾了费用相关，运单修改后，有费用产生但没有触发问题件
![qq 20180413120149](https://user-images.githubusercontent.com/37489976/38716342-d2b2e61c-3f12-11e8-8842-72e3bd62d42c.png)

**Comment by iamforrest** [comment]
@WENLINRONG 这个只是某个触发器，还是所有触发器都是这样
