### ISSUE TITLE
收货统计的优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1401]
收货统计的优化
![image](https://user-images.githubusercontent.com/37489976/44942473-7e6cac00-ade4-11e8-9d66-39f0c82be700.png)

**Comment by wny123** [comment]
统计分析查询后，所有导出execel明细增加【客户编号】

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
客户分组查询时，查询的统计结果样式现实异常（换行了）

**Comment by mrrc333** [comment]
@WENLINRONG
