### ISSUE TITLE
客户端样式优化

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1405]
1. - [ ]   费用对账，改名：费用明细
![image](https://user-images.githubusercontent.com/37526066/44954307-b3572c80-aed2-11e8-8ba2-9205e68782ec.png)
2.右边空白区域优化
![image](https://user-images.githubusercontent.com/37526066/44954318-d8e43600-aed2-11e8-8678-5da6fb8c6285.png)
3.黑名单查询样式
![image](https://user-images.githubusercontent.com/37526066/44954322-e8fc1580-aed2-11e8-91bc-c19784f6faba.png)
4.账户余额-未对账费用明细列表底部栏固定
![image](https://user-images.githubusercontent.com/37526066/44954331-1f399500-aed3-11e8-80f5-49f11fa2beb3.png)
和代理信息‘发货渠道’隐藏
![image](https://user-images.githubusercontent.com/37526066/44954333-252f7600-aed3-11e8-8eb8-b90ac1fda157.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
