### ISSUE TITLE
客户端打单录入新界面黑名单的判定跟提示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1408]
客户端打单录入新界面黑名单的判定跟提示

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
黑名单没判定 
![qq 20180903195053](https://user-images.githubusercontent.com/37489976/44985357-b590b800-afb2-11e8-8903-74aaf37d5d01.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
