### ISSUE TITLE
已预报的产生的问题件不用进入到问题列表

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1409]
已预报的产生的问题件不用进入到问题列表
![q q 20180902224921](https://user-images.githubusercontent.com/37489976/44957256-ceda2b80-af02-11e8-84fb-be86596c4598.jpg)
![qq 20180902225307](https://user-images.githubusercontent.com/37489976/44957269-021cba80-af03-11e8-816a-d0cafbf19d8a.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
