### ISSUE TITLE
员工端、客户端，主界面增加全局查找框

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1410]
物流端、客户端，主界面增加全局查找框
image
![image](https://user-images.githubusercontent.com/37526066/44957592-2332da80-af06-11e8-86e8-4b153add9b72.png)

1.可以多行录入查找
2.能提示找不到的单号
3.仅在当前标签操作状态下查找
image
![image](https://user-images.githubusercontent.com/37526066/44957598-36de4100-af06-11e8-9c78-4f0ff4a485d4.png)

![image](https://user-images.githubusercontent.com/37526066/44957638-8e7cac80-af06-11e8-8a9e-2e47939fd61c.png)

**Comment by WENLINRONG** [comment]
@likeasb 问题反馈：
带字母的单号搜索不了
![q q 20180914214632](https://user-images.githubusercontent.com/37489976/45554052-0da7a400-b868-11e8-9e62-f00147d6ad4c.png)
带字母的单号搜索不了

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
待字母的还是搜索不到
![image](https://user-images.githubusercontent.com/37489976/45597254-cc47fd80-b9fb-11e8-866b-5dec4c3d3fc7.png)
![image](https://user-images.githubusercontent.com/37489976/45597258-dcf87380-b9fb-11e8-9292-e3de34b63973.png)
