### ISSUE TITLE
收付款单界面样式跟标题的优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1412]
收付款单界面样式跟标题的优化

**Comment by WENLINRONG** [comment]
![qq 20180903172643](https://user-images.githubusercontent.com/37489976/44979436-ac74fc00-af5c-11e8-8d3e-cd12405c1a76.jpg)
![qq 20180903172618](https://user-images.githubusercontent.com/37489976/44979478-be569f00-af5c-11e8-8805-38175bec3df7.jpg)

**Comment by chenguolin123** [comment]
待测试

**Comment by WENLINRONG** [comment]
@chenguolin123 问题反馈：
1,收款单---选择退款类型，选中银行账户时。系统报错
2,,付款单---选择类型是付款或者退款，选中银行账户时，系统报错 
![image](https://user-images.githubusercontent.com/37489976/45929490-17768900-bf85-11e8-9ef0-e8d952dc1716.png)


![image](https://user-images.githubusercontent.com/37489976/45929438-4b04e380-bf84-11e8-94a1-0bb535c83cb5.png)
![image](https://user-images.githubusercontent.com/37489976/45929467-dd0cec00-bf84-11e8-889a-75eb2317a45a.png)

**Comment by mrrc333** [comment]
@WENLINRONG 这个之前你测过了，忘记转了，直接关闭即可
