### ISSUE TITLE
确认排货，发货渠道和代理为空，确认排货时要拦截

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1415]
确认排货，发货渠道和代理为空，确认排货时要拦截
![qq 20180903182417](https://user-images.githubusercontent.com/37489976/44981936-ad328000-afa6-11e8-84c4-e4ae966b2c3f.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
