### ISSUE TITLE
正式客户单微信登录，扫描二维码，绑定微信异常

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1424]
正式客户单微信登录，扫描二维码，绑定微信异常
![qq 20180904163315](https://user-images.githubusercontent.com/37489976/45019976-42457f80-b060-11e8-9747-7abf89f726cd.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
