### ISSUE TITLE
微信问题件通知优化：推送问题件 和 操作界面新建问题件 这两个需要重测试。其它的只是做了些优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1426]

**Comment by casparthh** [comment]
需要重点测试问题
1.推送问题件 和 操作界面新建问题件
2.绑定微信后切换机构需要重新登录
3.退出微信后重打开，不应该进入登录页面，应该记住上次登录的账号和机构。

**Comment by WENLINRONG** [comment]
@casparthh 问题反馈：绑定微信后切换机构需要重新登录没解决
现在切换机构是直接进入的，没有重新登录

**Comment by WENLINRONG** [comment]
经测试，已解决
