### ISSUE TITLE
相关的权限过滤回归测试一下

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1427]
优化了代码，回归测试一下：
1. 主列表的运单的权限是否正确，比如只能授权看自己的站点单的话，是不是看到的运单是正确的；
2. 成本分析
3. 报价
4. 问题处理
5. 运费试算

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
1，分配权限后，运费试算查不了数据
![image](https://user-images.githubusercontent.com/37489976/45075847-00c5da80-b11b-11e8-8b68-5450a13bc075.png),
2，客户档案显示空白
![image](https://user-images.githubusercontent.com/37489976/45075995-70d46080-b11b-11e8-8390-d81cd74d898d.png)

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by iamforrest** [comment]
@WENLINRONG 另加下面几个回归测试：

1. 发货统计
2. 收货统计
3. 应付分析
4. 应收分析
5. 组织架构

也优化了权限相关的代码

**Comment by WENLINRONG** [comment]
经测试，已解决
