### ISSUE TITLE
录单优化

### ISSUE THREAD

**Issue by chenguolin123** [itdida/itdida-issues#1428]
1扫描客户不一致拦截
2预报重量不符拦截

**Comment by WENLINRONG** [comment]
@chenguolin123 问题反馈：
1，预报重跟收货重不符时，产生的问题件要对接新旧值
![image](https://user-images.githubusercontent.com/37489976/45084310-9f106b00-b130-11e8-9887-9211d676edf1.png)
2，客户拦截时，要提示具体的客户名现在显示的是NULL 
![image](https://user-images.githubusercontent.com/37489976/45084365-ba7b7600-b130-11e8-9f69-3c0e426e6092.png)
