### ISSUE TITLE
收货录单及补资料排版调整

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#143]
特点
1.支持上下左右键
2.收货录单特定区域的回车往下一格跳转
3.新增加收货问题录入框，确认收货后同时提交
4.最近录入重量滚动至第一行可见区域
5.详细录入区域显示和隐藏方式变更

补录资料
1.支持放大为全屏
2.申报新增加按回车加一行

[20180413收货录单调整及补资料.pdf](https://github.com/itdida/itdida-issues/files/1909878/20180413.pdf)

**Comment by wny123** [comment]
目标时间：下周三可以升级

**Comment by WENLINRONG** [comment]
经测试，已解决
