### ISSUE TITLE
财务：应收应付审核账单同时审核核销

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#144]
对账金额直接进入流水，可省去后两步核销

![image](https://user-images.githubusercontent.com/37526066/40908880-9bb9d39c-681a-11e8-89ec-4aab127811ad.png)
![image](https://user-images.githubusercontent.com/37526066/40908930-c84e1184-681a-11e8-8e7c-d1e6facd5850.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
问题反馈：
指点审核且核销，数据只会到待核销，到不了已核销 @mrrc333

**Comment by mrrc333** [comment]
@WENLINRONG ctrl+f下操作会有此问题，已修复~

**Comment by WENLINRONG** [comment]
经测试，已解决
