### ISSUE TITLE
复制运单的日志记录的收货实重，收货材积，收费重记录错误

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1443]
复制运单的日志记录的收货实重，收货材积，收费重记录错误
![qq 20180906151108](https://user-images.githubusercontent.com/37489976/45141042-5962a980-b1e7-11e8-9b03-64954df64c7e.png)
![image](https://user-images.githubusercontent.com/37489976/45141059-67b0c580-b1e7-11e8-944e-b5bb8cb572ac.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
