### ISSUE TITLE
应收报价查询策略逻辑优化，指定永远优先

### ISSUE THREAD

**Issue by chenguolin123** [itdida/itdida-issues#1446]
生效中指定价格>失效中指定价格>生效中全部价格>失效中全部价格

**Comment by WENLINRONG** [comment]
指定价格还是找不对，总会去找全部的 @chenguolin123 
![image](https://user-images.githubusercontent.com/37489976/45197279-edd61600-b292-11e8-8eaa-3603d50973c5.png)
