### ISSUE TITLE
导入预报示例模板优化

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#145]
增加字段
1.件数，支持一行多件，每件同一尺寸、多件总实重，看截图；是必填项!
![10931523775218_ pic_hd](https://user-images.githubusercontent.com/37526066/38775792-6b9a9e78-40bd-11e8-83f7-261697c83025.jpg)
2.发货渠道、代理编号，这两个字段填写后，导入的运单为手动排货，收货后进入待排货状态，但不是必填项，以下是具体说明
导入模板增加「发货渠道、代理名称」两个字段
    *  1.认识名字，发货渠道名称不存在的，拒绝导入
    *  2.自动匹配代理，并计算应付费用
    *  3.名称存在于多个代理中，不匹配
    *  4.以上为手动排货运单收货后，第一站到待排货，等待审核，确认排货后往下一状态

修改：
按截图前7列为必填，第8列开始改为不是必填项

**Comment by wny123** [comment]
代替原来一行一件模板

**Comment by iamforrest** [comment]
@WENLINRONG @wny123 由于时间的关系，我已经直接更新到正式环境了。麻烦测试一下。

注意，件数那一列还没实现，其他都做了。

**Comment by iamforrest** [comment]
@mrrc333 加一列件数，然后根据件数的逻辑去生成单件（原来是一行一个单件，现在是根据件数循环生成多个单件），截图是可能需要修改的地方

![image](https://user-images.githubusercontent.com/2240276/38802573-5fa652d2-419f-11e8-963e-7f02390e5d71.png)
![image](https://user-images.githubusercontent.com/2240276/38802611-78bd56da-419f-11e8-941d-49a007b63b0a.png)

![image](https://user-images.githubusercontent.com/2240276/38802681-b9257946-419f-11e8-9593-40be63e778de.png)

**Comment by WENLINRONG** [comment]
手动排货的预报导入，数据导入不到系统，提示找不到报价跟客户单号为空
![image](https://user-images.githubusercontent.com/37489976/38866068-4f37a490-4272-11e8-9504-f77f9d06e5a4.png)
@iamforrest 
[11-手动排货---导入运单_duoPinMing (4).xlsx](https://github.com/itdida/itdida-issues/files/1919389/11-.---._duoPinMing.4.xlsx)

**Comment by WENLINRONG** [comment]
经测试，已解决
