### ISSUE TITLE
运单撤销退货重新排货，再到已预报界面点重现排货，运单的操作状态会自动被改成待发货(其他状态：草稿，待收货，待上网，待签收，已签收运单同样的操作也会有这个问题）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1452]
运单撤销退货重新排货，再到已预报界面点重现排货，运单的操作状态会自动被改成待发货(其他状态：草稿，待收货，待上网，待签收，已签收运单同样的操作也会有这个问题）
导致就是没有收货站点，没有收货日志，没有判定偏远，莫名其妙收货批号，收不了货
![image](https://user-images.githubusercontent.com/37489976/45198231-10b6f900-b298-11e8-8a04-8d0eb5ec6a31.png)
![image](https://user-images.githubusercontent.com/37489976/45198233-19a7ca80-b298-11e8-9468-57fa8a253f1f.png)

**Comment by mrrc333** [comment]
@WENLINRONG
