### ISSUE TITLE
运单录入-预报录单优化

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1455]
![image](https://user-images.githubusercontent.com/37526066/45204184-081eec80-b2b1-11e8-9878-a4df0481d16a.png)
![image](https://user-images.githubusercontent.com/37526066/45204196-0bb27380-b2b1-11e8-8155-51f4e41ecb6e.png)
![image](https://user-images.githubusercontent.com/37526066/45204202-0fde9100-b2b1-11e8-8419-fe73e287e651.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
