### ISSUE TITLE
客户端的，基本，主查询列表要隐藏收货备注

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1458]
客户端的，基本，主查询列表要隐藏收货备注

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：客户端---草稿基本的样式现实换行
![image](https://user-images.githubusercontent.com/37489976/45222778-fc9ae800-b2e7-11e8-9932-060452ef3de3.png)

**Comment by WENLINRONG** [comment]
经 测试，已解决
