### ISSUE TITLE
系统的每天第一次登陆会被踢下线，点确定，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1463]
系统的每天第一次登陆会被踢下线，点确定，系统报错

![image](https://user-images.githubusercontent.com/37489976/45251470-37992c00-b379-11e8-85f3-2e9a63a943c5.png)
![image](https://user-images.githubusercontent.com/37489976/45251472-41229400-b379-11e8-878c-2faa3678d518.png)

**Comment by mrrc333** [comment]
@WENLINRONG
