### ISSUE TITLE
捷美达业务员查询代理价格，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1464]
![image](https://user-images.githubusercontent.com/37489976/45250209-eaa95b80-b360-11e8-814e-78bcdf6ee1ec.png)
![image](https://user-images.githubusercontent.com/37489976/45250211-06146680-b361-11e8-8700-fdf585fbc75e.png)
![image](https://user-images.githubusercontent.com/37489976/45250213-12002880-b361-11e8-9436-1c1459a2ec7e.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
