### ISSUE TITLE
TNT，DHL,FedExD，UPS抓取到（正在运输，已取货，运输途中）的轨迹关键字，把运单状态从待上网更新到待签收

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1496]
TNT，DHL,FedExD，UPS抓取到（正在运输，已取货，运输途中,货物运输中）的轨迹关键字，把运单状态从待上网更新到待签收
TNT的轨迹关键字抓取到货物运输中，运单状态要从待上网更新为待签收
![image](https://user-images.githubusercontent.com/37489976/45348514-792c1000-b5e1-11e8-869e-8b8b49eedd39.png)

![image](https://user-images.githubusercontent.com/37489976/45348522-81844b00-b5e1-11e8-9385-1213fc5c0574.png)
![tnt _20180917103729](https://user-images.githubusercontent.com/37489976/45604394-8010b380-ba23-11e8-9fdd-0f6d6f7fc9bc.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
问题反馈：运单状态更改错误，应该是从待上网更新到待签收（FEDEX转单号：446315297506）
![image](https://user-images.githubusercontent.com/37489976/45799769-305f1000-bce1-11e8-9348-2dd23fe372cc.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
