### ISSUE TITLE
应付财务界面列表的财务列数据显示错误（应该显示的是应付财务，现在显示的是应收财务）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1499]
应付财务界面列表的财务列数据显示错误（应该显示的是应付财务，现在显示的是应收财务）

![qq 20180911181658](https://user-images.githubusercontent.com/37489976/45354787-23f7fa80-b5f1-11e8-836e-b10db3934363.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG
