### ISSUE TITLE
系统登录界面增加忘记密码的功能

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#15]
系统登录界面增加忘记密码的功
![qq 20180319172037](https://user-images.githubusercontent.com/37489976/37587332-fd1b1884-2b99-11e8-80af-6ce141a1ca5f.png)

**Comment by wny123** [comment]
找回密码
系统自动生成一个新密码，发给登录账号的邮箱
要提示是否成功发送

**Comment by johnnyZchan** [comment]
@WENLINRONG   已完成

**Comment by WENLINRONG** [comment]
@johnnyZchan 问题反馈：
这个密码没发送成功
没收到邮件
![image](https://user-images.githubusercontent.com/37489976/41464344-86aa64b6-70cc-11e8-9862-230b1724ab96.png)

![image](https://user-images.githubusercontent.com/37489976/41464366-a06a39e4-70cc-11e8-979a-9800e5ecf8fb.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   现在应该可以了，请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
