### ISSUE TITLE
打单录入修改国家后，系统重新排货后，没有记录日志改修改日志

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1503]
打单录入排货后，没有记录日志改修改日志
![qq 20180911210812](https://user-images.githubusercontent.com/37489976/45362246-ec944880-b606-11e8-896d-6b83fae1d91e.png)

**Comment by mrrc333** [comment]
@WENLINRONG 改了修改日志记录方法，烦请测试所有记录的地方，如打单录入，基本修改，扫单助手，机器人排货等

**Comment by WENLINRONG** [comment]
经测试，已解决
