### ISSUE TITLE
一代：UPS转单号：  1Z8A6A610432093013  此票UPS件系统轨迹抓取异常

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1508]
一代：UPS转单号：  1Z8A6A610432093013  此票UPS件系统轨迹抓取异常
![image](https://user-images.githubusercontent.com/37489976/45407099-04b5a780-b69b-11e8-822f-6b48812eacb5.png)
![image](https://user-images.githubusercontent.com/37489976/45407110-0bdcb580-b69b-11e8-8953-aeb83362ecfa.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
