### ISSUE TITLE
复制运单不能调整通常是草稿界面没有数据才跳转不了，有数据是可以跳转的

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1514]
复制运单不能调整通常是草稿界面没有数据才跳转不了，有数据是可以跳转的
![qq 20180913121141](https://user-images.githubusercontent.com/37489976/45466742-4ce1d200-b74e-11e8-8f6c-9d2b4a1c7ce0.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
