### ISSUE TITLE
待退货---撤销退货并重新排货，手动排货时，运单选中了系统识别不了，还提示清选择运单

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1515]
待退货---撤销退货并重新排货，手动排货时，运单选中了系统识别不了，还提示清选择运单
![--- qq 20180913144040](https://user-images.githubusercontent.com/37489976/45471314-49a51100-b763-11e8-8aac-2a9dbb91ada3.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
