### ISSUE TITLE
删除草稿运单，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1521]
删除草稿运单，系统报错

![image](https://user-images.githubusercontent.com/37489976/45582008-108fac80-b8db-11e8-9b15-5dc52dfe65d0.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
