### ISSUE TITLE
运单确认退货，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1526]
运单确认退货，系统报错
![qq 20180914103041](https://user-images.githubusercontent.com/37489976/45526393-69b9ec00-b7c6-11e8-808b-348e71bdd00e.png)
报错日志
![image](https://user-images.githubusercontent.com/37489976/45581988-aa0a8e80-b8da-11e8-9df2-6a1174e09342.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
