### ISSUE TITLE
总账表的表头搜索查询不了(银行，客户，代理都搜索不了）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1529]
总账表的表头搜索查询不了(银行，客户，代理都搜索不了）

**Comment by WENLINRONG** [comment]
![qq 20180914113206](https://user-images.githubusercontent.com/37489976/45528219-e7571980-b811-11e8-8d09-853684e9e24a.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
总账表表头搜索异常（账户，客户，代理）
![image](https://user-images.githubusercontent.com/37489976/45585883-2626c580-b91f-11e8-93b4-caf5d5a4464f.png)

![image](https://user-images.githubusercontent.com/37489976/45585873-e9f36500-b91e-11e8-8ff5-bb273c876310.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
