### ISSUE TITLE
一代需求：系统主查询界面的数据列（申报信息，收货实重，收货材积，收费重，发货实重，发货材积，发货计费汇总，代理计费重支持按照数值范围搜索运单，入申报价值的多行过滤输入1到100，系统把申报价值在这个范围内的运单搜索出来 ）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#153]
系统主查询界面的数据列（申报信息，收货实重，收货材积，收费重，发货实重，发货材积，发货计费汇总，代理计费重支持按照数值范围搜索运单，入申报价值的多行过滤输入1到100，系统把申报价值在这个范围内的运单搜索出来 ）
![1 100 qq 20180416193403](https://user-images.githubusercontent.com/37489976/38806970-9b293d84-41ad-11e8-9cc7-08522277d73b.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
输入空搜索不出来数据

**Comment by johnnyZchan** [comment]
空过滤总结如下：
1、主页面：城市名、邮编、代理名、发货渠道
2、应收财务：收货渠道、发货渠道
3、应付财务：收货渠道、代理名、发货渠道

排序总结如下：
1、主页面：目的地国家、国家英文名，国家二字码，件数、收货实重、收货材积重、收货计费重、发货实重、发货抛重、发货计费重、城市、申报价值、收件人邮编
2、应收财务：金额、燃油费、折算金额、国家中文名、国家英文名、国家二字码，件数、实重、材积重、计费重、运费、折算合计
3、应付财务：代理名称、国家中文名、国家英文名、国家二字码，件数、实重、材积重、发货计费重、运费、折算合计、金额、燃油费、折算金额

范围检索总结如下：
1、主页面：收货实重、收货材积重、收货计费重、发货实重、发货抛重、发货计费重、申报信息、件数
2、应收财务：件数、实重、材积重、计费重、金额、燃油费、折算金额
3、应付财务：件数、实重、材积重、发货计费重、金额、燃油费、折算金额

@WENLINRONG 已经按照这个进行了调整，请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
