### ISSUE TITLE
主界面的字段显示空白，全部界面也没有

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1532]
主界面的字段显示空白，全部界面也没有
![image](https://user-images.githubusercontent.com/37489976/45532270-08296a00-b826-11e8-8f39-48d231f3b4ab.png)
![image](https://user-images.githubusercontent.com/37489976/45532534-06ac7180-b827-11e8-8acb-390de16daf48.png)
![image](https://user-images.githubusercontent.com/37489976/45532536-0dd37f80-b827-11e8-9920-a020d79b3741.png)
![image](https://user-images.githubusercontent.com/37489976/45532574-2b084e00-b827-11e8-8516-dc58744c3221.png)

**Comment by mrrc333** [comment]
@iamforrest es问题

**Comment by WENLINRONG** [comment]
经测试，已解决
