### ISSUE TITLE
应收财务----导入重量，重量导入后，应收费用不会按照导入重量重算费用 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1538]
应收财务----导入重量，重量导入后，应收费用不会按照导入重量重算费用

**Comment by WENLINRONG** [comment]
![---- qq 20180914164817](https://user-images.githubusercontent.com/37489976/45540032-f5e60680-b7fa-11e8-975d-d4d41b5c8ff1.png)

**Comment by mrrc333** [comment]
@WENLINRONG
