### ISSUE TITLE
客户端---对账单界面打不开

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1539]
客户端---对账单界面打不开

**Comment by mrrc333** [comment]
@iamforrest es下sql错误

**Comment by iamforrest** [comment]
![image](https://user-images.githubusercontent.com/2240276/45585358-a21c1000-b915-11e8-8dfa-4faf16bf79a3.png)

**Comment by iamforrest** [comment]
费用明细能打开，对账单打不开

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
客户端对账单界面--没进入数据，实际是有数据的
![qq 20180916103832](https://user-images.githubusercontent.com/37489976/45592359-fd451580-b99c-11e8-8927-00583183e0c7.png)
