### ISSUE TITLE
客户端---账户余额打不开

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1540]
1，客户端---账户余额打不开
2，客户端有两个对账单界面，打开显示找不到网页
3，客户端的偏远查询，邮编查询，黑名单查询，下载报价打开异常
4，客户端显示的运单数据都是用户端的数据，不是这个客户的数据
![qq 20180914171922](https://user-images.githubusercontent.com/37489976/45541715-56774280-b7ff-11e8-850c-67b23b32477e.png)
![qq 20180914171439](https://user-images.githubusercontent.com/37489976/45541445-a99cc580-b7fe-11e8-85aa-10684df1a415.png)
![qq 20180914171638](https://user-images.githubusercontent.com/37489976/45541798-845c8700-b7ff-11e8-90b2-6aee6bed21ef.png)
![image](https://user-images.githubusercontent.com/37489976/45582146-7bda7e00-b8dd-11e8-94cb-7d232462d747.png)
![image](https://user-images.githubusercontent.com/37489976/45582148-80069b80-b8dd-11e8-8092-0946481b0c38.png)
[log.txt](https://github.com/itdida/itdida-issues/files/2385341/log.txt)[log.txt](https://github.com/itdida/itdida-issues/files/2385341/log.txt)

**Comment by mrrc333** [comment]
@iamforrest 显示找不到网页是权限问题，其他打不开均为es问题，sql错误

**Comment by iamforrest** [comment]
@WENLINRONG 再试试

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
1，客户端界面有两个对账单，打开现实找不到页面
![image](https://user-images.githubusercontent.com/37489976/45585842-25416400-b91e-11e8-9976-d4a1e4b6ae96.png)
2，客户端显示的运单数据都是用户端的数据，不是这个客户的数据
![image](https://user-images.githubusercontent.com/37489976/45585856-5d48a700-b91e-11e8-92f0-1e9e3add8250.png)

**Comment by mrrc333** [comment]
@WENLINRONG
