### ISSUE TITLE
待退货界面---撤销退件报错 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1542]
撤销退件报错

**Comment by WENLINRONG** [comment]
![qq 20180915120719](https://user-images.githubusercontent.com/37489976/45582331-3b303400-b8e0-11e8-8521-c6f7169dfa87.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
