### ISSUE TITLE
主界面增加显示重量差字段（应收计费重减去应付计费重）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1547]
主界面增加显示重量差字段（应收计费重减去应付计费重）
![qq 20180917113012](https://user-images.githubusercontent.com/37489976/45605168-685e1d00-ba6d-11e8-9eb6-f9338b1cea98.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
