### ISSUE TITLE
系统操作成功后，界面数据不会自动即时刷新了（只能手动刷新整个系统链接才行）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1549]
系统操作成功后，界面数据不会自动即时刷新了
![qq 20180917114717](https://user-images.githubusercontent.com/37489976/45605449-a0fef600-ba6f-11e8-9399-331033fea697.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
