### ISSUE TITLE
待排货界面的汇总数据显示错误（待排货的汇总数据跟列表数据对不上）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1550]
![image](https://user-images.githubusercontent.com/37489976/45605592-a6a90b80-ba70-11e8-8478-894bcb15ff8c.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
待排货汇总按钮还是跟界面数据对不上 
![image](https://user-images.githubusercontent.com/37489976/45673671-e3066580-bb5d-11e8-9e60-a6dd3db83514.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
