### ISSUE TITLE
客户端---主界面的左侧栏显示空白

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1551]
1，客户端---主界面的左侧栏显示空白
![image](https://user-images.githubusercontent.com/37489976/45610626-2b0a8700-ba8f-11e8-948a-77e539df5ff8.png)
2，问题件的分组也不行
![qq 20180917154134](https://user-images.githubusercontent.com/37489976/45610914-35795080-ba90-11e8-9bd8-eaf5a621dddf.png)

**Comment by mrrc333** [comment]
@WENLINRONG
