### ISSUE TITLE
对接：DTDC

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1556]
[对接DTDC.pdf](https://github.com/itdida/itdida-issues/files/2388296/DTDC.pdf)
getonline.dtdc.com

用户名：DE1397
密码 : Sinotrans2018#

下载开发文件https://getonline.dtdc.com/developers_docs_wsc.aspx?sessionid=85D7C91A2ADDCA6686673DA1E39BBE41

API Credential:-
Entity ID :- 25FF3DEF90DF109EF76CD7CF536FBEBE
Entity PIN:- 8asf9asdfjasjdf9

一、运单提交
二、转单lb和转单发票下载
2.1转单lbhdzsst
https://ws01.ffdx.net/v4/printdoc/[label file name]?accessid=[entity id]&shipno=[shipment no]&format=pdf
label file name=docConnoteStyle3.aspx
2.2转单发票
https://ws01.ffdx.net/v4/printdoc/[label file name]?accessid=[entity id]&shipno=[shipment no]&format=pdf
label file name=docCommercialInvoice_pcs.aspx
三、轨迹抓取    

查询参与单号：

API模板名称：DTDC
可填写内容：
EntityID：
EntityPIN：
CCAccCardCode：这是登录的用户名吗？
CCWeightMeasure：重量类型=固定kgs
CCSTypeCode：代理渠道代码或发货渠道名称
CCSenderName：发件人公司名
CCSenderAdd1：地址1
CCSenderAdd2：地址2
CCSenderAdd3：地址3
CCSenderLocCode：发件人国家代码
CCSenderLocName：发件人国家英文名
CCSenderLocState：发件人洲名
CCSenderLocPostcode：发件人邮编
CCSenderLocCtryCode：发件人国家代码
CCSenderContact：发件人名
CCSenderPhone：发件人电话
CCSenderEmail：发件人邮箱

**Comment by johnnyZchan** [comment]
@wny123   和postshipping重复   不需要实现
