### ISSUE TITLE
对接：POSTSHIPPING

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1557]
[对接POSTSHIPPING.pdf](https://github.com/itdida/itdida-issues/files/2388301/POSTSHIPPING.pdf)

**Comment by WENLINRONG** [comment]
@casparthh 问题反馈：对接打单的寄件人信息填写不了
![qq 20181010155102](https://user-images.githubusercontent.com/37489976/46720926-62421180-cca4-11e8-854d-16d8ebdc798f.jpg)

**Comment by WENLINRONG** [comment]
@casparthh 对接字段还是有问题

**Comment by WENLINRONG** [comment]
@casparthh 问题反馈：
申报信息有多个品名的，发票上没显示完，只显示了一个品

**Comment by WENLINRONG** [comment]
经测试，已解决
