### ISSUE TITLE
众鑫通需求：客户档案界面增加显示一列扣货额度

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#156]
客户档案界面增加显示一列扣货额度
![qq 20180416194757](https://user-images.githubusercontent.com/37489976/38807451-34e803c8-41af-11e8-9b54-2253b316143f.png)

**Comment by WENLINRONG** [comment]
题反馈：受信额度的字段选择显示后，出现了两列预估余额且客户档案的界面界面打不开
@tomlamcn 
![image](https://user-images.githubusercontent.com/37489976/39284541-63831526-4946-11e8-98d9-ec44d8694b74.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
