### ISSUE TITLE
9180913517205 ， 9180913100619，导致在对代理帐单一直导不入，才发现，是系统没有国家----用户端，客户端运单录入界面 拦截没有填写国家，客户单号，渠道，件数，总量的运单保存

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1563]
导致在对代理帐单一直导不入，才发现，是系统没有国家
![image](https://user-images.githubusercontent.com/37489976/45666291-94e66780-bb47-11e8-87e0-a16e078254ec.png)

![qq 20180918125514](https://user-images.githubusercontent.com/37489976/45665750-0ffa4e80-bb45-11e8-8e19-93a680230ff0.png)
![image](https://user-images.githubusercontent.com/37489976/45665766-1c7ea700-bb45-11e8-9d5a-1b4a729ae9e7.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
