### ISSUE TITLE
草稿界面，全选运单后，确认预报，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1573]
草稿界面，全选运单后，确认预报，系统报错
![image](https://user-images.githubusercontent.com/37489976/45675797-bb65cc00-bb62-11e8-90b9-6e7c3c1c42ab.png)
[log (2).txt](https://github.com/itdida/itdida-issues/files/2391938/log.2.txt)

**Comment by iamforrest** [comment]
@WENLINRONG 已解决

**Comment by WENLINRONG** [comment]
经测试，已解决
