### ISSUE TITLE
草稿界面，新建问题件，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1575]
1，草稿界面，新建问题件，系统报错
2，草稿运单修改渠道，系统报错
![image](https://user-images.githubusercontent.com/37489976/45677633-3d57f400-bb67-11e8-87a9-63071536ffb9.png)
![image](https://user-images.githubusercontent.com/37489976/45677825-bbb49600-bb67-11e8-8ab8-800cd7c16936.png)

**Comment by mrrc333** [comment]
@WENLINRONG
