### ISSUE TITLE
主界面跟财务界面的重量差增加排序

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1580]
主界面跟财务界面的重量差增加排序
![qq 20180919104706](https://user-images.githubusercontent.com/37489976/45728196-8e182d00-bbf9-11e8-86bc-43846a6d5bc2.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
