### ISSUE TITLE
确认对账后，多了一个不存在单号的弹窗

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1584]
确认对账后，多了一个不存在单号的弹窗
![qq 20180919115047](https://user-images.githubusercontent.com/37489976/45730078-53ff5900-bc02-11e8-987e-f14e631fad6b.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
