### ISSUE TITLE
应收财务，应付财务界面，搜索查询后，选中运单，汇总数据错误

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1585]
应收财务，应付财务界面，搜索查询后，选中运单，汇总数据错误
查询条件 ：12312413
12312413
300201894102
300201894105
300201894105
![image](https://user-images.githubusercontent.com/37489976/45730225-10f1b580-bc03-11e8-9707-ab94a70b6c7f.png)
![image](https://user-images.githubusercontent.com/37489976/45730283-66c65d80-bc03-11e8-81ed-3b1f2ea6cca9.png)

**Comment by mrrc333** [comment]
@WENLINRONG
