### ISSUE TITLE
修改基本的国家，链接加后缀了，导致界面死了

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1588]
修改基本的国家，链接加后缀了，导致界面死了
![qq 20180919150739](https://user-images.githubusercontent.com/37489976/45736538-d3e6ec80-bc1d-11e8-8032-afe96d587741.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
