### ISSUE TITLE
主界面没有按照操作时间默认排序 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1589]
主界面没有按照操作时间默认排序 
![qq 20180919152103](https://user-images.githubusercontent.com/37489976/45737201-ba46a480-bc1f-11e8-9c0c-fdfe2841a18a.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
