### ISSUE TITLE
确认预报的运单不会排货跟算费用，也不会同步界面数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1597]
确认预报的运单不会排货跟算费用，也不会同步界面数据
![qq 20180920120402](https://user-images.githubusercontent.com/37489976/45795244-4f53a700-bccd-11e8-8034-19a12ae4ce87.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
导入预报到草稿界面，主列表的收货渠道没有对接显示
![qq 20180920174904](https://user-images.githubusercontent.com/37489976/45810573-7c1fb280-bcfd-11e8-9cfd-e0a7e0dc9a70.png)
（基本是有收货渠道的）

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
