### ISSUE TITLE
界面汇总按钮数据经常跟列表实际数据不准

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1598]
界面汇总按钮数据经常跟列表实际数据不准
![qq 20180920150305](https://user-images.githubusercontent.com/37489976/45801500-9ef29c80-bce6-11e8-9df9-53af609ff147.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
