### ISSUE TITLE
问题件中心界面增加显示一列最新轨迹

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1603]
问题件中心界面增加显示一列最新轨迹
![qq 20180920204700](https://user-images.githubusercontent.com/37489976/45819242-7387a600-bd16-11e8-92cb-01f37911fba3.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
