### ISSUE TITLE
ups随货文件模板-获取转单自动生成-合并到转单发票

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1605]
ups随货文件模板
![ups qq 20180920224804](https://user-images.githubusercontent.com/37489976/45826602-5dceac80-bd27-11e8-851d-2b8fa4369cd3.jpg)
[Zipcodes_OPA_ODA-FEDEX.pdf](https://github.com/itdida/itdida-issues/files/2401809/Zipcodes_OPA_ODA-FEDEX.pdf)

**Comment by wny123** [comment]
api接口模板名称：HKUPS
增加功能：获取转单同时，自动生成随货文件，
随货文件：一份pdf有中英文各一份，共2页a4【模板已做好，以上标注字段需对接】
与转单发票合并：合并到转单发票中，转单发票打印将会是1式5页纸
