### ISSUE TITLE
主列表增加显示一列地址验证，在打单录入时，点地址验证后，将验证结果保存起来显示在主列表里

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1607]
主列表增加显示一列地址验证，在打单录入时，点地址验证后，将验证结果保存起来显示在主列表里

**Comment by WENLINRONG** [comment]
![qq 20180921113926](https://user-images.githubusercontent.com/37489976/45859270-e877d180-bd50-11e8-88b0-6b2500befd97.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
