### ISSUE TITLE
确认发货界面的发货渠道没显示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1638]
确认发货界面的发货渠道没显示

**Comment by WENLINRONG** [comment]
![qq 20181008103017](https://user-images.githubusercontent.com/37489976/46590704-dca44300-caa4-11e8-85ef-37c40a1e1830.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
