### ISSUE TITLE
收货批号，发货批号，退货批号，包号支持es

### ISSUE THREAD

**Issue by chenguolin123** [itdida/itdida-issues#1642]

**Comment by chenguolin123** [comment]
包号支持索引 @WENLINRONG @wny123

**Comment by WENLINRONG** [comment]
@chenguolin123 问题处理：
1，包号详情界面的数据显示为0
![image](https://user-images.githubusercontent.com/37489976/46918103-4f12a700-d000-11e8-882f-6e0ed01ce80c.png)
2，旧数据的日期跟创建人显示空白，状态，封包显示错误


3，退货批号的总件数显示为零
![image](https://user-images.githubusercontent.com/37489976/46918147-d19b6680-d000-11e8-8bc6-31897a542836.png)
4，发货批号详情列表修改的数据不能同步更新奥发货批号的列表
![qq 20181014223917](https://user-images.githubusercontent.com/37489976/46918224-2ee3e780-d002-11e8-90bd-d4c8fa1ad6ac.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
