### ISSUE TITLE
系统主界面----问题件标黄不能用

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1645]
系统主界面----问题件标黄不能用

**Comment by WENLINRONG** [comment]
![qq 20181009105845](https://user-images.githubusercontent.com/37489976/46644316-5ece5d80-cbb2-11e8-849e-0a1cb7be0752.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
