### ISSUE TITLE
一代：不同类型的多个单号搜索时，搜索结果没有按照搜索单号的顺序排序显示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1646]
一代：不同类型的多个单号搜索时，搜索结果没有按照搜索单号的顺序排序显示
6090389734
9881426752
9882041676
6520827633
3637148826
6581426946
YHT19879414
9882041805
6581426935
16820377
6090389760
6881619522
81805147 
![image](https://user-images.githubusercontent.com/37489976/46647696-17e96380-cbc4-11e8-9325-1e76a0684d51.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
