### ISSUE TITLE
日常收支---收入列，支出列表头自定义搜索查询，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1648]
![image](https://user-images.githubusercontent.com/37489976/46659983-9b1cb080-cbe8-11e8-9bb1-47a75f3e929a.png)
![image](https://user-images.githubusercontent.com/37489976/46660029-bc7d9c80-cbe8-11e8-8fea-2507ca154220.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
