### ISSUE TITLE
一代：系统批量打印转单LABEL，系统发票，转单发票，系统标签没有按照搜索的单号顺序打印

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1653]
8812480250
5867283540
51801834
9881098150
3165368166
DH800003994
5880544250
3165364938
1033423
8263786226
8812480176
16820381
9882042236
7881734232
12648100817
6014950502
66880749
系统批量打印转单LABEL，系统发票，转单发票，系统标签没有按照搜索的单号顺序打印
![image](https://user-images.githubusercontent.com/37489976/46713239-f8b40a00-cc87-11e8-90a5-0f94dac72cf6.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
