### ISSUE TITLE
TNT，DHL,FedExD，UPS抓取到（货物运输中，货件已就进接收）的轨迹关键字，把运单状态从待上网更新到待签收

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1655]
TNT，DHL,FedExD，UPS抓取到（货物运输中，货件已就进接收）的轨迹关键字，把运单状态从待上网更新到待签收
TNT的转单号：799213008
799213011
799213042
799212974
![image](https://user-images.githubusercontent.com/37489976/46723288-0ed2c200-ccaa-11e8-84ad-c3c1bf261058.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认
