### ISSUE TITLE
客户端---主查询主查询界面的全部界面没有按照收货时间排序（主列表的排序逻辑要跟用户的逻辑一致）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1659]
![image](https://user-images.githubusercontent.com/37489976/46778025-5efe6280-cd44-11e8-9d1b-44dd051e34c6.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
