### ISSUE TITLE
一代需求：在总账中，添加一种币别:BHD（客户账号，代理账户界面的余额表对应增加对账金额BHD,付款金额BHD,余额BHD）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1661]
在总账中，添加一种币别:BHD
（客户账号，代理账户界面的余额表对应增加对账金额BHD,付款金额BHD,余额BHD）
![bhd qq 20181011114626](https://user-images.githubusercontent.com/37489976/46779658-5f4e2c00-cd4b-11e8-8d95-c1da7479c62f.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
