### ISSUE TITLE
一代需求：在组织架构中，员工信息导出的模板中添加一列：角色

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1664]
在组织架构中，员工信息导出的模板中添加一列：角色
![image](https://user-images.githubusercontent.com/37489976/46780327-a853af80-cd4e-11e8-8905-ed5c45eb50ed.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
