### ISSUE TITLE
乐递环境：这二票件，手动做已签收状态，几次了，还是弹回来待签收的状态

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1671]
这二票件，手动做已签收状态，几次了，还是弹回来这二票件，手动做已签收状态，几次了，还是弹回来待签收的状态
![qq 20181011213549](https://user-images.githubusercontent.com/37489976/46807996-d6acab80-cd9d-11e8-9f86-19b13d20da21.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG @wny123  请测试确认
