### ISSUE TITLE
api对接：鑫硕

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1672]
仅api模板，不是承运商
1.获取转单号
2.下载标签--分2步
通过转单号拿到pdf标签下载链接
再从链接下载

world文件不能上传，QQ再发
测试用
接口地址：http://211.162.119.216:8011/wc/predictOrder.xsv
登录账号：22222API
登录密码：1048453
运输方式ID：DHL促销
![image](https://user-images.githubusercontent.com/37526066/46853044-9138be80-ce2f-11e8-8a18-892a689e12b7.png)

**Comment by johnnyZchan** [comment]
@wny123 @WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by johnnyZchan** [comment]
@WENLINRONG 已修改

**Comment by WENLINRONG** [comment]
经测试，已解决
