### ISSUE TITLE
api对接：华磊

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1674]
华磊文档
http://www.sz56t.com:8090/pages/viewpage.action?pageId=3473454
测试用
接口地址：120.24.208.92:8082
登录账号：YDGJ
登录密码：123456
运输方式ID：SGDHL
1身份认证 
 URL1/selectAuth.htm?username=TEST&password=123456
3添加订单(UTF-8)--【用含发件人】格式
6. 一键打印10*10标签（需要货代在系统设置各渠道的10*10标签)
URL2/order/FastRpt/PDF_NEW.aspx?PrintType=lab10_10&order_id=订单ID，多个用逗号分割。

![image](https://user-images.githubusercontent.com/37526066/46852898-24bdbf80-ce2f-11e8-8591-ad167eef2a28.png)

**Comment by johnnyZchan** [comment]
@wny123 @WENLINRONG  请测试确认
