### ISSUE TITLE
一代需求：燃油附加费界面。添加几个项： 创建人，创建件时间，修改人，修改时间

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1676]
燃油附加费界面。添加几个项：
创建人，创建件时间，修改人，修改时间(日志不用做 ）
![image](https://user-images.githubusercontent.com/37489976/46853193-fbe9fa00-ce2f-11e8-870a-df7adc0f1750.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
