### ISSUE TITLE
一代需求：已退货的界面增加撤回按钮(撤回退货要记录日志），让运单到待退货界面，再取消退货,

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1677]
已退货的界面增加撤回按钮，让运单到待退货界面，再取消退货
![image](https://user-images.githubusercontent.com/37489976/47480606-8b959c80-d863-11e8-9e9e-e4468eae309c.png)
![image](https://user-images.githubusercontent.com/37489976/47485921-c30b4580-d871-11e8-85dd-19613168b2eb.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
@johnnyZchan 问题反馈：
从已退货撤回到待退货时，同时清除退货原因且记录日志
![qq 20181029155931](https://user-images.githubusercontent.com/37489976/47636573-c402e680-db93-11e8-9c2b-b665ee870d11.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG   已修正  请确认

**Comment by WENLINRONG** [comment]
经测试，已解决
