### ISSUE TITLE
应收财务界面的客户名称（列表抬头），收货渠道，发货渠道，材积重显示异常

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#168]
应收财务界面的客户名称（列表抬头），收货渠道，发货渠道，材积重显示异常

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
问题反馈：应付财务界面的收货渠道跟发货渠道显示空白
![qq 20180426113041](https://user-images.githubusercontent.com/37489976/39284335-4ff2a176-4945-11e8-8323-47ca88fe3026.jpg)
@tomlamcn

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
