### ISSUE TITLE
UPS 转单COPY随货单证去掉付款账号显示，费用结算ID为空的显示在应付财务。

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#1686]
![029872497133b960d5192149cc83eae8](https://user-images.githubusercontent.com/37174434/46867512-d1ac3280-ce57-11e8-93f9-0e4976b8d2cf.jpg)
去掉

**Comment by WENLINRONG** [comment]
@tomlamcn 问题反馈：
UPS账号还是没去掉
![image](https://user-images.githubusercontent.com/37489976/46877849-66248e00-ce74-11e8-8456-60effbb8ef4c.png)
