### ISSUE TITLE
api对接：PostaPlus

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1689]
1.api接口模板：获取转单号【在开发文档中：3. Creating a Shipment in Postaplus】
2.添加承运商：PostaPlus，用于轨迹抓取【在开发文档中：5. Shipment Tracking】
![image](https://user-images.githubusercontent.com/37526066/46904726-6fb50100-cf1b-11e8-9368-d3388df7d5d3.png)

详细的对接字段说明文档是EXcel，开发的时候QQ再传
[Postaplus API documentaion-V-13.pdf](https://github.com/itdida/itdida-issues/files/2475386/Postaplus.API.documentaion-V-13.pdf)

**Comment by WENLINRONG** [comment]
接口地址：http://211.162.119.216:8011/wc/
特快美国DHL-快递电商
![image](https://user-images.githubusercontent.com/37489976/46989966-d90e5d00-d131-11e8-9452-17f8c564dbd5.png)

**Comment by WENLINRONG** [comment]
问题反馈：

获取转单号不成功，报获取失败

**Comment by johnnyZchan** [comment]
@wny123 @WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
@johnnyZchan 问题反馈：
获取转单号失败，说是验证身份失败
![qq 20181025155908](https://user-images.githubusercontent.com/37489976/47484749-1760f600-d86f-11e8-9f75-61cb432fbb84.jpg)

**Comment by WENLINRONG** [comment]
经测试，已解决
