### ISSUE TITLE
   转单号更新的（机器人+前端线程获取+API获取）也加上实时索引

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1690]
转单号更新的（机器人+前端线程获取+API获取），也加上实时索引
![image](https://user-images.githubusercontent.com/37489976/46905806-6338a480-cf2b-11e8-8a9e-3019c6d97772.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
