### ISSUE TITLE
发货以后的运单，客户充值后，运单欠费状态也会不更新

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1695]
发货以后的运单，客户充值后，运单欠费状态也会不更新
![qq 20181015162241](https://user-images.githubusercontent.com/37489976/46938756-1f62ae00-d097-11e8-906f-41ea8fc93c73.png)

**Comment by mrrc333** [comment]
@WENLINRONG 欠费运单不允许发货

**Comment by WENLINRONG** [comment]
经测试，已解决
