### ISSUE TITLE
打单录入，基本，收货录入界面，国家加拿大通过邮编自动对接洲名的显示 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1701]
打单录入，基本，收货录入界面，国家加拿大通过邮编自动对接洲名的显示

![qq 20181016112726](https://user-images.githubusercontent.com/37489976/46991004-87b49c80-d136-11e8-99a3-6e3c56cf497e.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
