### ISSUE TITLE
客户档案界面增加显示一列是否上传档案

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1705]
客户档案界面增加显示一列是否上传档案
![qq 20181016155645](https://user-images.githubusercontent.com/37489976/47001128-551d9a80-d15c-11e8-8cce-7901b7603907.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
