### ISSUE TITLE
主界面的发货计费重没有排序功能

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1707]
主界面的发货计费重没有排序功能
![qq 20181016160522](https://user-images.githubusercontent.com/37489976/47001613-7468f780-d15d-11e8-8fd3-e2e4bf7eb025.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
系统的重量列跟数值列不能自定义查询及表头查询
![image](https://user-images.githubusercontent.com/37489976/47008666-44c1eb80-d16d-11e8-9db0-ea19af035e04.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
