### ISSUE TITLE
应收财务，应付财务的类别不能自定义查询

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1708]
应收财务，应付财务的类别不能自定义查询
![qq 20181016161751](https://user-images.githubusercontent.com/37489976/47002348-50a6b100-d15f-11e8-8f2d-3c016af8fbf5.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
