### ISSUE TITLE
代理对账单界面，全选后，点审核付款，系统提示清选择对账单

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1729]
代理对账单界面，全选后，点审核付款，系统提示清选择对账单
![qq 20181019151444](https://user-images.githubusercontent.com/37489976/47203144-eafe3300-d3b1-11e8-8915-5b7751b3ed54.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
