### ISSUE TITLE
主界面，应收财务，应付财务界面的侧栏分组的收货渠道，发货渠道搜索查询不了 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1734]
![image](https://user-images.githubusercontent.com/37489976/47250015-0a4a9e00-d44e-11e8-80cb-f6afd1fbfea3.png)

![image](https://user-images.githubusercontent.com/37489976/47250035-3fef8700-d44e-11e8-98db-8fd41ae38a54.png)
**

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
