### ISSUE TITLE
应付财务----应收折算不能排序也不能搜索空的字段

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1737]
应付财务----应收折算不能排序也不能搜索空的字段
![image](https://user-images.githubusercontent.com/37489976/47251260-cb741280-d464-11e8-9390-68ff1355d775.png)
![image](https://user-images.githubusercontent.com/37489976/47251279-f8282a00-d464-11e8-9d49-bf1c983d0b30.png)
**
![image](https://user-images.githubusercontent.com/37489976/47251281-00806500-d465-11e8-80b7-a0d43f0aca30.png)
**

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试， 已解决
