### ISSUE TITLE
包号状态没有跟着运单状态同步更新

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1741]
包号状态没有跟着运单状态同步更新
![qq 20181022115559](https://user-images.githubusercontent.com/37489976/47277309-aeb91580-d5f1-11e8-812f-af9ba3168fad.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
