### ISSUE TITLE
一代需求：应收财务界面----登记费用中。 选择结算客户下拉框中：客户名称+客户编号

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1749]
一代需求：应收财务界面----登记费用中。 选择结算客户下拉框中：客户名称+客户编号
![image](https://user-images.githubusercontent.com/37489976/47349369-13ee3300-d6e6-11e8-852d-7d4f65fd0fb2.png)

**Comment by mrrc333** [comment]
@WENLINRONG
