### ISSUE TITLE
一代需求:代理对账单界面，代理账单费用详情中 双击运单，弹出基本详情界面 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1750]
一代需求:代理对账单界面，代理账单费用详情中 双击运单，弹出基本详情界面 
![image](https://user-images.githubusercontent.com/37489976/47349938-49475080-d6e7-11e8-80bc-2b87839f1dde.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
