### ISSUE TITLE
客户端下载已上传的文件，系统报UI错误

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1751]
客户端下载已上传的文件，系统报UI错误
![ui qq 20181023172034](https://user-images.githubusercontent.com/37489976/47350215-f4f0a080-d6e7-11e8-9b98-aea74296b34d.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
