### ISSUE TITLE
一代需求：收款单和付款单界面，客户下拉选框中：名称+编号

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1752]
收款单和付款单界面，客户下拉选框中：名称+编号
![image](https://user-images.githubusercontent.com/37489976/47350377-54e74700-d6e8-11e8-89f8-8e77a69a7a1f.png)
![image](https://user-images.githubusercontent.com/37489976/47350396-616b9f80-d6e8-11e8-89ce-592f1cfc8e04.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
