### ISSUE TITLE
客户端的运单录入界面的打印转单LB和打印转单发票的要判定客户是否有查看LB和发票的权限

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1755]
客户端的运单录入界面的打印转单LB和打印转单发票的要判定客户是否有查看LB和发票的权限
![lb lb qq 20181024152819](https://user-images.githubusercontent.com/37489976/47413716-a43d7e00-d7a1-11e8-872a-812cead9a446.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG
