### ISSUE TITLE
用户端，客户端的运费试算，查历史价格没有按照当时的燃油来计算

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1756]
用户端，客户端的运费试算，查历史价格没有按照当时的燃油来计算
![qq 20181024153057](https://user-images.githubusercontent.com/37489976/47413874-0eeeb980-d7a2-11e8-8f20-34e183894270.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
