### ISSUE TITLE
一代需求：用户端，客户端运费试算界面的字段顺序显示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1760]
1，用户端，客户端运费试算界面的字段顺序显示
![image](https://user-images.githubusercontent.com/37489976/47416934-5d538680-d7a9-11e8-8316-16f73878de46.png)
2，把列表上的字段全部显示出来（优先显示客户要求的默认字段：承运商，价格名，币种，折算总费用，含油单价，燃油费率，运费公式）
![image](https://user-images.githubusercontent.com/37489976/47417219-1914b600-d7aa-11e8-9336-b877fab17672.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
