### ISSUE TITLE
客户端---运单录入增加渠道筛选的功能

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1762]
客户端---运单录入增加渠道筛选的功能
![--- qq 20181024164300](https://user-images.githubusercontent.com/37489976/47418091-00a59b00-d7ac-11e8-9492-82ba8d2c615c.jpg)
![image](https://user-images.githubusercontent.com/37489976/47418118-10bd7a80-d7ac-11e8-848c-6b5d1404b4f8.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
