### ISSUE TITLE
应收财务，应付财务界面杂费登记时，系统生成的新运单不要自动生成运费为零的费用数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1770]
应收财务，应付财务界面杂费登记时，系统生成的新运单不要自动生成运费为零的费用数据

![image](https://user-images.githubusercontent.com/37489976/47542267-3a42e700-d90f-11e8-933f-500b4638a5da.png)

![qq 20181026110210](https://user-images.githubusercontent.com/37489976/47542217-fb149600-d90e-11e8-9dbd-7a4c8ffa0a51.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决。
