### ISSUE TITLE
重构导出模块的回归测试

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#1773]
1） 麻烦测试一下应收对账单的导出是不是正常
2） 测试一下报价的导出是不是正常
3）测试一下确认收货导出是不是正常
4）其他场景随便选一个试一下导出是不是正常（zip，excel，pdf都试一下）

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
1，档案界面的下载转单LABEL跟转单发票，系统报错
![image](https://user-images.githubusercontent.com/37489976/47600712-4bb3ee00-d9f8-11e8-9c82-9a7a45f4a9aa.png)

2，应收财务确认对账，下载对账单报错
![image](https://user-images.githubusercontent.com/37489976/47600721-52dafc00-d9f8-11e8-95a6-d245df1f4765.png)
3，客户对账单，代理对账单的导出报错
![image](https://user-images.githubusercontent.com/37489976/47600771-e6143180-d9f8-11e8-9f5b-939a1ccde9d9.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
