### ISSUE TITLE
客户端，运单录入界面。将申报价值移至邮编下方。

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1778]
客户端，运单录入界面。将申报价值移至邮编下方。
![image](https://user-images.githubusercontent.com/37489976/47628373-4bd6f980-db70-11e8-97f0-6d30d48388de.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
