### ISSUE TITLE
客户对账单界面的增加一列原币种合计（现在其他币种的账单，现实的折算金额是不对的 ）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1782]
![image](https://user-images.githubusercontent.com/37489976/47633373-a54b2280-db88-11e8-8dcd-2fb5f8a0bcc4.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
