### ISSUE TITLE
api对接：Aplus

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#1788]
api文档：api.apparcel.com
测试账号 ：test1@apparcel.com    
密码：TES123456
增加承运商：Aplus
不用生成转单发票
![image](https://user-images.githubusercontent.com/37526066/47696092-24e7f880-dc40-11e8-8b82-763851a4a4a7.png)

**Comment by johnnyZchan** [comment]
@wny123 @WENLINRONG   请测试确认

Ps：用以下账号测试
账号MKT01@FIRSTLINE56.COM，密码：YDL123456

**Comment by WENLINRONG** [comment]
经测试，已解决
