### ISSUE TITLE
加开2个按钮【快件丢失】【海关销毁】 当操作这两个任何一个，等同于【确认签收】，以后不再抓取，但轨迹内容表达为【快件丢失】或【海关销毁】

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1792]
运单轨迹完结，其实有3种情况
1.已签收
2.丢失
3.销毁
2。3这两种情况，也肯定 是人为处理。在待签收界面加开2个按钮【快件丢失】【海关销毁】
当操作这两个任何一个，等同于【确认签收】，以后不再抓取，但轨迹内容表达为【快件丢失】或【海关销毁】

**Comment by mrrc333** [comment]
@WENLINRONG
