### ISSUE TITLE
银行账户左侧栏输入关键字搜索敲回车，界面显示空白

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#1802]
1，银行账户左侧栏输入关键字搜索敲回车，界面显示空白
![qq 20181101152655](https://user-images.githubusercontent.com/37489976/47838580-c448ef00-ddea-11e8-8b00-dffb9b6f16be.png)
2，银行账户停用，系统报错
![image](https://user-images.githubusercontent.com/37489976/47838603-dc207300-ddea-11e8-9e1f-adaf91af048d.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
