### ISSUE TITLE
财务性能优化

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#19]
应收财务和应付财务打开比较慢。

**Comment by iamforrest** [comment]
@WENLINRONG 我已经解决了。请在测试环境测试一下。

**Comment by WENLINRONG** [comment]
应收财务打开速度很快，2-3秒内完成，应付财务打开报错，还在处理，等不报错时，一起测试速度

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
反馈反馈：一代这边财务数据有较多，应付财务界面的打开平均用时在10S-12S @iamforrest 

![10s-12s qq 20180323101350](https://user-images.githubusercontent.com/37489976/37807969-23e009a2-2e83-11e8-84eb-8adff1dffa7d.png)

**Comment by iamforrest** [comment]
这个我会进一步优化
但是跟进一下，有四十几万笔费用，是不是批处理帮他们改一下状态

**Comment by WENLINRONG** [comment]
我在跟客户确认

**Comment by iamforrest** [comment]
晚点他们紧急部署，应该应付会快一些，到时候你测试一下

**Comment by WENLINRONG** [comment]
好的

**Comment by WENLINRONG** [comment]
恩源  10:39:45
把应收应付里面的所有财务数据删掉，客户流水账数据，代理流水账数据，收款单，付款单数据，银行账户列表(银行账号保留）
运单列表的运单信息保留就好了
在1st的
今天之前的都这么处理，他现在还没有新的收货单

**Comment by WENLINRONG** [comment]
一代国际的应付财务界面打开用时 8S (444233条数据 ） @iamforrest 
![8s 444233 qq 20180323151327](https://user-images.githubusercontent.com/37489976/37816163-f175089e-2eac-11e8-80ac-47e50cd5cdbb.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
