### ISSUE TITLE
众鑫通需求：收款单界面只要增加显示审核时间跟到账时间（到账时间没有填写就默认当前费用登记保存时间）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#192]
1，收款单界面只要增加显示审核时间跟到账时间（到账时间没有填写就默认当前费用登记保存时间）
![image](https://user-images.githubusercontent.com/37489976/38986102-fc034594-43fd-11e8-9736-c6e8c8f83c64.png)

2，收款单登记界面增加到账时间的选择输入框
![qq 20180419182235](https://user-images.githubusercontent.com/37489976/38986341-c395d356-43fe-11e8-85bc-58765c138b83.jpg)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
收款单审核的数据进入不到银行账户里面
![qq 20180511233742](https://user-images.githubusercontent.com/37489976/39933191-d447779a-5574-11e8-9ca1-180c321dc9f7.png)
@tomlamcn
