### ISSUE TITLE
众鑫通需求：付款单界面只要增加显示审核时间跟付款时间（付款时间没有填写就默认当前费用登记保存时间）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#193]
付款单界面只要增加显示审核时间跟付款时间（付款时间没有填写就默认当前费用登记保存时间）
![image](https://user-images.githubusercontent.com/37489976/38986168-42a77b96-43fe-11e8-934b-89d11f6c5ec7.png)
![image](https://user-images.githubusercontent.com/37489976/38986195-5413d672-43fe-11e8-904c-bf7e7e287232.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
ID重复，显示了三列创建时间，林金斌还在改

**Comment by WENLINRONG** [comment]
经测试，已解决
