### ISSUE TITLE
众鑫通需求:应收财务日志界面增加客户名称，客户编号，对账批号，核销批号四个字段且增加导出功能

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#196]
应收财务日志界面增加客户名称，客户编号，对账批号，核销批号四个字段且增加导出功能
![qq 20180420142458](https://user-images.githubusercontent.com/37489976/39033902-e16f87c0-44a6-11e8-93b8-6420f7ee46be.jpg)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
