### ISSUE TITLE
众鑫通需求：应付财务日志界面增加的字段---代理名称，代理编号，对账单号，对账批号，核销批号 且界面增加导出功能

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#197]
应付财务日志界面增加的字段---代理名称，代理编号，对账单号，对账批号，核销批号 且界面增加导出功能

![--- qq 20180420142841](https://user-images.githubusercontent.com/37489976/39034121-d261fa96-44a7-11e8-94e7-cd1d79677efd.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
