### ISSUE TITLE
众鑫通需求：应收财务界面，应付财务界面增加多行过滤查询功能（类似于主查询界面的多行过滤）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#198]
众鑫通需求：应收财务界面，应付财务界面增加多行过滤查询功能（类似于主查询界面的多行过滤）
![_qq 20170821104542](https://user-images.githubusercontent.com/37489976/39034346-a1cf7eac-44a8-11e8-8690-11ed92476c25.png)

**Comment by tomlamcn** [comment]
@WENLINRONG
