### ISSUE TITLE
登录进来后可选择按导航显示首页

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#2]
登录进来后可选择按导航显示首页
![_qq 20180316122756](https://user-images.githubus
ercontent.com/37489976/37575992-e7cfc8b0-2b64-11e8-8fcb-aa25ee8e308b.jpg)
![_qq 20180316122746](https://user-images.githubusercontent.com/37489976/37576010-ff665f34-2b64-11e8-866b-78ee420b8af5.jpg)

**Comment by iamforrest** [comment]
@WENLINRONG 两个问题
1. 每个按钮可以点？
2. 如果是，每个按钮点的效果各是什么？

**Comment by WENLINRONG** [comment]
恩源  12:04:14
或者这个先不做吧@iamforrest
