### ISSUE TITLE
一代国际：一代采购了两套自动称重和量尺寸的称，这个称他们自己有称重系统，需要做API对接，接收他们的称重数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#205]
一代采购了两套自动称重和量尺寸的称，这个称他们自己有称重系统，需要做API对接，接收他们的称重数据
https://bitbucket.org/etaexltd/ship/wiki/DWS%20Interface%20Specification

**Comment by iamforrest** [comment]
@mrrc333 麻烦跟进这个，这个礼拜的版本希望有这个、因为客户已经买了机器。具体可以跟恩源直接沟通调试。
