### ISSUE TITLE
基础数据---寄件人新建保存后，客户名显示空白

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#228]
1，基础数据---寄件人新建保存后，客户名显示空白
![image](https://user-images.githubusercontent.com/37489976/39230307-9bec7064-4898-11e8-9e0b-aa561e257d4c.png)
2，寄件人编辑修改时，不能输入关键字搜索查询

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
