### ISSUE TITLE
录单界面及基本界面增加币种的选择框 （默认是USD，需要修改币种的在支持手动修改）----系统发票也要对接币种 转单LB跟转单发票的币种没办法支持美金以外其他币种对接

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#240]
录单界面及基本界面增加币种的选择框
（默认是USD，需要修改币种的在支持手动修改）----系统发票也要对接币种
转单LB跟转单发票的币种没办法支持美金以外其他币种对接
![image](https://user-images.githubusercontent.com/37489976/39285082-1319ba88-4949-11e8-98a0-09775888d13e.png)

2，系统发票模板及转单发票的模板的币种也要直接对接录单跟基本界面的币种

**Comment by WENLINRONG** [comment]
这个能不能优先处理下先
恩源  16:54:28
1.申报价值的币种选择
2.保存的时候判断申报价值与申报列表汇总金额是否相同
3.excel导出的按单号排序

**Comment by WENLINRONG** [comment]
赶本周六迭代 @tomlamcn

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
