### ISSUE TITLE
代理流水账界面的流水号ID重复，显示了多了流水号数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#247]
代理流水账界面的流水号ID重复，显示了多了流水号数据
![image](https://user-images.githubusercontent.com/37489976/39299683-ebeb8274-497b-11e8-9886-691aac633b89.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
