### ISSUE TITLE
收货录单的电子秤连接不上，电子秤界面的端口显示空白

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#25]
1，收货录单的电子秤连接不上，电子秤界面的端口显示空白
![qq 20180321145958](https://user-images.githubusercontent.com/37489976/37697786-c699cfe0-2d19-11e8-94e7-b44878160fa9.png)
2，sa扫单助手电子秤界面的端口显示空白

**Comment by iamforrest** [comment]
@WENLINRONG 这个应该是你机器硬件的问题，得不到串端口？别的机器有问题吗？别的机器串端口的选择框也是空的？

**Comment by WENLINRONG** [comment]
我换了台电脑，还是显示找不到串端口 @iamforrest 
![image](https://user-images.githubusercontent.com/37489976/38129104-22a643f0-3430-11e8-8984-c3d4ab623036.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
