### ISSUE TITLE
一代需求：自定义字段可保存多份 自定义字段可以保存多份记录

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#259]
自定义字段可保存多份
自定义字段可以保存多份记录。

![image](https://user-images.githubusercontent.com/37526066/40905602-05cec45e-6811-11e8-81cb-c039b4abedf5.png)

**Comment by wny123** [comment]
1.对自定义列显示字段，保存的记录，可命名；根据命名方便快速切换显示字段
2.能否增加一个导出EXCEL表功能，利用所见即所得模板按显示字段名导出，这样就可以实现按字段名的自定义导出

**Comment by WENLINRONG** [comment]
经测试，已解决
