### ISSUE TITLE
报价管理---基本界面的电池金句的备选项没有过滤掉基础数据电池金句已删除的数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#29]
1，报价管理---基本界面的电池金句的备选项没有过滤掉基础数据电池金句已删除的数据
![--- qq 20180323160243](https://user-images.githubusercontent.com/37489976/37818152-232b3faa-2eb4-11e8-9d56-8544a1682081.png)

2，基础数据的电池金句的数据要跟报价管理---基本界面电池金句的数据一致
3，基础数据---电池金句的双击不能查看编辑
![--- qq 20180323160850](https://user-images.githubusercontent.com/37489976/37818262-86dba5bc-2eb4-11e8-947b-940704beb3f4.jpg)

**Comment by WENLINRONG** [comment]
问题反馈：基础数据---电池金句的双击不能查看编辑 @tomlamcn

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
