### ISSUE TITLE
一代需求：报价增加新的计算方式----按件计算合并后为整票运单（勾选按件计算，运费计算要把单件运费分别计算后，再汇总相加）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#3]
一代需求：报价增加新的计算方式----按件计算合并后为整票运单（勾选按件计算，运费计算要把单件运费分别计算后，再汇总相加）

**Comment by tomlamcn** [comment]
![default](https://user-images.githubusercontent.com/37174434/37576451-7146a3a0-2b67-11e8-80d6-1112afc5da39.jpg)
Attach

**Comment by iamforrest** [comment]
@chenguolin123 原来是用单票试算，现在是单件试算合计。 这个应该是试算和计算费用的相关方法就行了吧？这相关的方法在哪个类哪个方法？

**Comment by chenguolin123** [comment]
FeiYongService.calYunFei()。计费重传单件的计费重即可

**Comment by iamforrest** [comment]
@chenguolin123 完成此任务的大概修改的步骤说一下。

**Comment by chenguolin123** [comment]
判断报价是按单件还是整票计费，如果单件，传入 单件计费重，调用FeiYongService.calYunFei( 单件计费重)，然后循环++汇总即可；整票的传入整票计费重，即可算出运费 @tomlamcn @iamforrest

**Comment by iamforrest** [comment]
@tomlamcn 优先解决这个，并给一下时间

**Comment by tomlamcn** [comment]
@WENLINRONG weffen通过后我发布你试一下。因为是报价的比较关键，所以要看没问题才能发布正式。
