### ISSUE TITLE
众鑫通需求 ：问题处理列增加显示一列最新回复内容---将最新回复内容显示上来，方便操作判断处理

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#302]
问题处理列增加显示一列最新回复内容---将最新回复内容显示上来，方便操作判断处理
![--- qq 20180507174452](https://user-images.githubusercontent.com/37489976/39696004-f462c010-521e-11e8-8023-744f118b9129.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
