### ISSUE TITLE
批量打印系统发票，针对没有申报信息的运单，系统弹出提示且可以继续打印其他能有申报信息的发票（现在是弹出提示后，不能继续打印其他正常运单的发票，用户觉得在操作上不方便）

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#303]
批量打印系统发票，针对没有申报信息的运单，系统弹出提示且可以继续打印其他能有申报信息的发票（现在是弹出提示后，不能继续打印其他正常运单的发票，用户觉得在操作上不方便）
![image](https://user-images.githubusercontent.com/37526066/39701689-b54fa418-5234-11e8-86c4-2af9f3916780.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
