### ISSUE TITLE
收款登记，付款登记界面的账户没有过滤掉已删除的账户数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#308]
收款登记，付款登记界面的账户没有过滤掉已删除的账户数据
![qq 20180508154624](https://user-images.githubusercontent.com/37489976/39744499-142c83b4-52d7-11e8-9271-63535606a1bd.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
@johnnyZchan 问题反馈：付款单已删除的账户没有过滤掉
![image](https://user-images.githubusercontent.com/37489976/40912416-0cfe5204-6824-11e8-8a63-89226008311b.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 已解决，请确认

**Comment by WENLINRONG** [comment]
经测试，已解决
