### ISSUE TITLE
所有分组的关键字过滤优化

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#32]
参考印象笔记《关于分组的关键字过滤的优化》
把所有的分组的关键字优化都做了，优先财务，然后再是主界面，然后到其他，全部都做好。有问题就找我

**Comment by iamforrest** [comment]
@tomlamcn 现在做到哪些分组，已经优化了？

**Comment by tomlamcn** [comment]
@WENLINRONG 所有有侧栏分组的都做了优化了。测试点击和搜索侧栏分组就可以

**Comment by WENLINRONG** [comment]
经测试，已解决
