### ISSUE TITLE
一代国际：触发器页面显示无法最大化，现在用户看不清楚数据，需要拖进度条

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#329]
触发器页面显示无法最大化，现在用户看不清楚数据，需要拖进度条
![image](https://user-images.githubusercontent.com/37489976/39965248-f2bfbc42-56c7-11e8-8c9d-2d22bc74a3d0.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
