### ISSUE TITLE
一代国际：报关方式在基础数据增加报关方式可编辑，目前只能在后台数据库操作可在电子词典里面增加

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#330]
报关方式在基础数据增加报关方式可编辑，目前只能在后台数据库操作可在电子词典里面增加
![image](https://user-images.githubusercontent.com/37489976/39877766-5d46c96e-54a9-11e8-88d9-6e25a782c93c.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经 测试，已解决
