### ISSUE TITLE
一代需求：运费欠费触发方式（只针对未发货的运单数据)

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#338]
运费欠费触发方式（只针对未发货的运单数据)
![image](https://user-images.githubusercontent.com/37489976/39965304-f79db196-56c8-11e8-816d-3cfab9850bb9.png)

**Comment by chenguolin123** [comment]
大致思路：
欠费：
1.三个多选款全部勾选的情况，优先判断前面两个财务的，一起判断，如果前面两个查到数据，无视后面所有逻辑，直接欠费未发货所有运单；前面两个条件不满足，额度写一个公用方法，传入一个额度，欠费哪些单即可，浮动额度需动态计算下而已
不欠费逻辑和欠费相反即可
