### ISSUE TITLE
一代需求：主页面的 各个单号 及时间表头 要有排序； 「需要再确认详细字段」 需要排序与筛选的栏位有：客户名称、收货时间、客户单号、系统单号、转单号码、最新轨迹、收货渠道、发货渠道、折算合计、品名、收件人电话、、客户纺号、换单号、上网时间、收货站点、签收时间、发货时间、位置、操作时间、上一站、下一站、收货批号、代理编号、发货批号、港前客服、港后客服、销售、退货批号、空运单号、其他单号1、其他单号2

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#346]
主页面的 各个单号 及时间表头 要有排序； 「需要再确认详细字段」
需要排序与筛选的栏位有：客户名称、收货时间、客户单号、系统单号、转单号码、最新轨迹、收货渠道、发货渠道、折算合计、品名、收件人电话、、客户纺号、换单号、上网时间、收货站点、签收时间、发货时间、位置、操作时间、上一站、下一站、收货批号、代理编号、发货批号、港前客服、港后客服、销售、退货批号、空运单号、其他单号1、其他单号2

**Comment by WENLINRONG** [comment]
建议：以后主运单表所有新增加的栏位都要增加排序与筛选功能，包括所有与数值有关的栏位要求增加汇总功能，

**Comment by johnnyZchan** [comment]
@WENLINRONG  已完成，请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
