### ISSUE TITLE
系统批量收货，系统需要提速（不需要请等待的进度条）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#35]
系统批量收货，系统需要提速（不需要请等待的进度条）
![image](https://user-images.githubusercontent.com/37489976/37875957-9bc3f45a-3078-11e8-9d9d-cc3062e568fa.png)

**Comment by chenguolin123** [comment]
已大幅提速

**Comment by WENLINRONG** [comment]
经测试，以解决
