### ISSUE TITLE
一代需求 ：系统主查询界面，应收财务，应付财务界面----左下角的查找框（CTRL+F）这个功能，建议改用放大镜的方式摆在系统右上角，且可以调用快捷键crtl+f来调此功能，此功能要允许同时多票进行查询，建议查询票数锁定在30票以内，数据过多系统速度会慢。此界面的应用需要在主运单表、应收财务、应付财务功能里面使用，用户会经常要用此功能，频繁操作性比较高。

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#351]
系统主查询界面，应收财务，应付财务界面----左下角的查找框（CTRL+F）这个功能，建议改用放大镜的方式摆在系统右上角，且可以调用快捷键crtl+f来调此功能，此功能要允许同时多票进行查询，建议查询票数锁定在30票以内，数据过多系统速度会慢。此界面的应用需要在主运单表、应收财务、应付财务功能里面使用，用户会经常要用此功能，频繁操作性比较高

**Comment by WENLINRONG** [comment]
![image](https://user-images.githubusercontent.com/37489976/40095316-e8971642-58fd-11e8-9993-4d836a7f58a8.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG  已完成、请测试确认

**Comment by WENLINRONG** [comment]
@johnnyZchan 问题反馈：
1,客户端的支持30票 的查询
![30 qq 20180523164422](https://user-images.githubusercontent.com/37489976/40413581-c4ba0ab2-5ea8-11e8-8324-495c63b3aac3.png)
2，应收财务，应付财务的查找框的样式需要调整
![qq 20180523164823](https://user-images.githubusercontent.com/37489976/40413734-28579d96-5ea9-11e8-98e9-f6d98539b984.jpg)
3，批量查找框，实现自子系统单号查询（这个是一件一个子系统单号，一票运单可能存在多个子系统单号

**Comment by johnnyZchan** [comment]
@WENLINRONG 
1、客户端已支持
2、应收应付样式已调整
3、支持子系统单号查找尚未完成，在另外一个git中体现

**Comment by WENLINRONG** [comment]
经测试，已解决
