### ISSUE TITLE
系统所有的下载文件及导出数据置保存路径(有代码可以指定下载方式而不是直接下载) ---录制视频教客户

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#353]
系统所有的下载文件及导出数据置保存路径(有代码可以指定下载方式而不是直接下载)

**Comment by WENLINRONG** [comment]
不用写程序---录制视频教客户

**Comment by tomlamcn** [comment]
两种方式
1.看视频教程，地址： https://pan.baidu.com/s/15NshX66-MjKq_OcVRrOzPw 
2. 手动设置方法：chrome://settings/  复制一下内容:chrome://settings/  到浏览器 回车，然后向下拉到最低，点高级 继续拉开菜单 在 下载内容 有 位置（下载的默认路径） 以及 下载前询问 按钮 点击打开 就可以。

**Comment by iamforrest** [comment]
写到印象笔记留底

**Comment by WENLINRONG** [comment]
@wny123 这个你跟客户培训时跟客户对接沟通下

**Comment by WENLINRONG** [comment]
经测试，已解决
