### ISSUE TITLE
打单录入能否跳出新窗口页面，有标题 全屏页面紧凑 「美工问题」---加一个按钮(跳转到浏览器新界面

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#355]
打单录入能否跳出新窗口页面，有标题 全屏页面紧凑 「美工问题」----加一个按钮(跳转到浏览器新界面）
该功能里面的所有数据控制提示建议用对话框形式展示，目前在右上角只是显示了一下就消失了，导致客户不知道是什么问题，必须要让客户知道是什么问题，且点取消才可以进行后面的功能操作。

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
