### ISSUE TITLE
一代国际：录单，打单录入，基本的申报信息界面的申报价值单行总额不需要进位功能，目前小数点是二位，建议开放至三位小数点，总额不要进位，目前进位后就导致申报价值汇总与前面的总申报价值不符

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#356]
录单，打单录入，基本的申报信息界面的申报价值单行总额不需要进位功能，目前小数点是二位，建议开放至三位小数点，总额不要进位，目前进位后就导致申报价值汇总与前面的总申报价值不符
![image](https://user-images.githubusercontent.com/37489976/40099980-e4978196-5914-11e8-83c7-4b97e818169e.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
