### ISSUE TITLE
一代需求：打单录入 加 验证地址

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#358]
打单录入 加 验证地址
![image](https://user-images.githubusercontent.com/37489976/40101107-ec816d0a-5918-11e8-8e59-4f41a415365b.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
经测试，已解决
