### ISSUE TITLE
一代需求：打单录入增加新建问题件 (增加一行，打单问题：+录入框，与收货问题一样）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#359]
打单录入增加新建问题件 「增加一行，打单问题：+录入框，与收货问题一样」
要产生成问题件
标识为打单问题件，标题，这个是需要去区分的
![image](https://user-images.githubusercontent.com/37489976/40101315-ab8482c8-5919-11e8-8bac-b51e25da34f5.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
