### ISSUE TITLE
谷歌浏览器----编辑触发器的界面样式显示异常

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#36]
chrome的浏览器----编辑触发器的界面样式显示异常
![qq 20180326215917](https://user-images.githubusercontent.com/37489976/37910937-51d5f14e-3141-11e8-9437-5cef7cde42fe.jpg)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
样式还是显示异常 @iamforrest

**Comment by tomlamcn** [comment]
@WENLINRONG 测试试一下看看。

**Comment by WENLINRONG** [comment]
@chenguolin123 样式还是不行
