### ISSUE TITLE
已失效的报价可以支持修改报价全部数据且修改的报价生成一个已失效的报价版本，价格名不变，渠道名不变，生成的已失效的报的创建时间，报价编号唯一

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#363]
已失效的报价可以支持修改且修改的报价生成一个已失效的报价版本，价格名不变，渠道名不变，生成的已失效的报的创建时间，报价编号唯一
![image](https://user-images.githubusercontent.com/37489976/40113145-fe38a6c2-593a-11e8-9ee6-3393b0037a65.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
