### ISSUE TITLE
确认发货后，提示操作成功，确认发货的弹窗不会关闭

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#369]
确认发货后，提示操作成功，确认发货的弹窗不会关闭
![qq 20180517165553](https://user-images.githubusercontent.com/37489976/40167317-5650f824-59f3-11e8-9846-53a8e065ca4d.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@tomlamcn 问题反馈：系统操作一票也会出现滚动条且操作成功后，进度条不会关闭
![image](https://user-images.githubusercontent.com/37489976/40400340-47f9a688-5e74-11e8-8c99-b4fe572241a3.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
