### ISSUE TITLE
客户导入增加字段(销售员	,应收财务，应付财务，销售客服，港前客户，港后客户

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#37]
客户导入增加字段(销售员	,应收财务，应付财务，销售客服，港前客户，港后客户
![qq 20180326221505](https://user-images.githubusercontent.com/37489976/37911671-4c116fca-3143-11e8-9c73-6d4ea1cfba8a.jpg)

**Comment by chenguolin123** [comment]
待测试

**Comment by WENLINRONG** [comment]
经测试，已解决
