### ISSUE TITLE
一代需求：客户预报导入功能增加运费付款方式：寄付、到付，增加代收货款栏位---对接电子词典，基本，录单，打单录入界面

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#370]
客户预报导入功能增加运费付款方式：寄付、到付，增加代收货款栏位
![image](https://user-images.githubusercontent.com/37489976/40171917-6a293102-59ff-11e8-82d1-0df2f9e1cf49.png)

**Comment by WENLINRONG** [comment]
以上需求仅限增加栏位记录数据，无数据逻辑问题存在。

**Comment by johnnyZchan** [comment]
@WENLINRONG 
1、客户预报导入已支持新增字段
2、基本和主页面列表已支持新增字段
3、录单和打单由魏一川完成，这里并没有做
