### ISSUE TITLE
一代需求：录单功能增加运费付款方式：寄付、到付、代收货款

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#372]
录单功能增加运费付款方式：寄付、到付、代收货款
![image](https://user-images.githubusercontent.com/37489976/40172292-911a0f60-5a00-11e8-9623-8f28b18e4e49.png)

**Comment by WENLINRONG** [comment]
以上需求仅限增加栏位记录数据，无数据逻辑问题存在。

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
