### ISSUE TITLE
主列表界面增加字段：应收运费，应付运费、应收附加费、应付附加费、 所有应收、所有应付、毛利（所有应收减所有应付，本位币rmb）、 毛利率，按本币别rmb作结算单位

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#375]
1，主列表界面增加字段：应收运费、应付运费、应收附加费、应付附加费、
所有应收、所有应付、毛利（所有应收减所有应付，本位币rmb）、
毛利率（毛利率=利润/应收费用总额），按本币别rmb作结算单位
2，这些新增的字段数据的查看权限跟费用界面的权限关联
应收运费、应收附加费------对接应收费用查看权限
应付附加费、应付运费-------对接应付费用查看权限
毛利（所有应收减所有应付，本位币rmb）-----对接应收应付利润权限
毛利率（毛利率=利润/应收费用总额）----对接应收应付利润权限
3，应收运费，应付运费、 所有应收、所有应付、毛利（所有应收折算金额减所有应付折算金额，本位币rmb）、 毛利率加汇总.
![image](https://user-images.githubusercontent.com/37489976/40177303-c59d1d80-5a10-11e8-8804-50ac7757d2c9.png)

**Comment by chenguolin123** [comment]
![Uploading EB180E3DDF6351347587E9333D459D32.jpg…]

**Comment by chenguolin123** [comment]
![qq20180517-0](https://user-images.githubusercontent.com/37174477/40177804-261c9e96-5a12-11e8-934f-9c82a73367b4.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG    请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
