### ISSUE TITLE
CNDHL的登录不上去

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#378]
CNDHL的登录不上去
![image](https://user-images.githubusercontent.com/37489976/40219273-3e29111e-5aa7-11e8-9c13-532602ec8813.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   已修正，请确认

**Comment by WENLINRONG** [comment]
还是显示登录失败 @johnnyZchan

**Comment by johnnyZchan** [comment]
@WENLINRONG   这个weffen改后  应该可以了吧？

**Comment by WENLINRONG** [comment]
经测试，已解决
