### ISSUE TITLE
导入预报后的宽跟高的值错误，系统默认是等同于长的数据了

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#379]
导入预报后的宽跟高的值错误，系统默认是等同于长的数据了
![image](https://user-images.githubusercontent.com/37489976/40223060-518d858e-5ab4-11e8-9864-8a234add20e7.png)
![qq 20180518155956](https://user-images.githubusercontent.com/37489976/40223141-a032e1fc-5ab4-11e8-9347-67f6ef880d60.jpg)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
