### ISSUE TITLE
待发货运单触发撤回至待排货状态

### ISSUE THREAD

**Issue by wny123** [itdida/itdida-issues#382]
待发货运单【发货渠道、代理编号、代理名称】3个字段有一个为空，即时触发撤回至待排货状态
![image](https://user-images.githubusercontent.com/37526066/40270071-be8e81be-5bb9-11e8-9c44-89be51b020a1.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
