### ISSUE TITLE
扫单助手---滞留件判定，  单独开一个tab，叫滞留件

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#388]
扫单助手---滞留件判定，  单独开一个tab，叫滞留件

![image](https://user-images.githubusercontent.com/37489976/40340631-9f29b596-5db2-11e8-8ec7-7f6785eb493b.png)

**Comment by iamforrest** [comment]
@wny123 梳理和优化一下设计

**Comment by WENLINRONG** [comment]
@chenguolin123 1.扫单助手设置：加开单独标签「滞留件」
2. 扫单助手列表增加操作按钮「滞留件」
3.主运单列表加开「滞留件」列表，与「问题件」标签并排，扫单助手确认滞留件后，运单进入「滞留件」
4.滞留件列表操作按钮「确认发货、确认退货、取消滞留」将滞留件移出

安琪 2018/7/1 18:58:28
    单选：启用、不启用
    勾选：[]播音   以下是滞留件判断规则
* 正常滞留：收货小于（8）小时，不是问题件
* 超时滞留：收货超过（8）小时，不是问题件
* 已发货：数据已发货，实物在仓库
* 未收货：有预报、无预报
* 已退货：状态为已退货
* 问题件：是问题件，忽略滞留时间判断

安琪 2018/7/1 18:58:55
* 正常滞留：收货小于（8）小时，不是问题件
* 超时滞留：收货超过（8）小时，不是问题件
* 已发货：数据已发货，实物在仓库
* 未收货：有预报、无预报
* 已退货：状态为已退货
* 问题件：是问题件，忽略滞留时间判断


什么意思？

安琪 2018/7/1 18:59:24
这个是不是多加一个列，列的名字叫滞留状态，显示的逻辑是：

* 正常滞留：收货小于（8）小时，不是问题件
* 超时滞留：收货超过（8）小时，不是问题件
* 已发货：数据已发货，实物在仓库
* 未收货：有预报、无预报
* 已退货：状态为已退货
* 问题件：是问题件，忽略滞留时间判断

安琪 2018/7/1 18:59:30
是的，在主运单列表要加3列，
1.滞留状态
2.滞留时间
3.滞留件操作人

安琪 2018/7/1 18:59:53
操作通过【确认发货、确认退货、取消滞留】改变滞留状态
