### ISSUE TITLE
客户端的运单，只要有打印标签，或者打印发票或者打印转单 ，系统拦截撤回到草稿

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#389]
客户端的运单，只要有打印标签，或者打印发票或者打印转单 ，系统拦截撤回到草稿
![default](https://user-images.githubusercontent.com/37489976/40341439-c843d7d6-5db7-11e8-96d9-de5df1e2f91a.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，要解决
