### ISSUE TITLE
录单界面，扫单助手界面---电子秤对接重量，经常链接不到接口

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#391]
1，录单界面，扫单助手界面---电子秤对接重量，经常链接不到接口
![image](https://user-images.githubusercontent.com/37489976/40347353-8d92d95a-5dd2-11e8-8e66-c4da10722d75.png)

2，-电子秤启用后，实重会经常变成可以修改的重量状态，重量录入框要显示只读

![image](https://user-images.githubusercontent.com/37489976/40347454-f3fe51e2-5dd2-11e8-9c1e-e91c720b880d.png)

2-实重的重量为0不能进入列表，系统要拦截且提示（现在是一票多件，在单号扫入后，选择单件时，会把电池秤的重量清零），显示接口对接空白
![image](https://user-images.githubusercontent.com/37489976/40349638-c22cd222-5dd9-11e8-852c-03db367eed22.png)
重量清零后，再动一下电子秤，电池秤对接的重量输入框的重量变成了可编辑的状态
![image](https://user-images.githubusercontent.com/37489976/40349811-50b5ffa0-5dda-11e8-8944-c51db45a4c1e.png)

![image](https://user-images.githubusercontent.com/37489976/40348149-555e2b22-5dd5-11e8-8ace-73e063a60411.png)
操作步骤：
一票三件的扫入单号后
![image](https://user-images.githubusercontent.com/37489976/40348416-4258f3ee-5dd6-11e8-8bd3-8b4986288619.png)
![image](https://user-images.githubusercontent.com/37489976/40349463-45734310-5dd9-11e8-8d1b-89e71a48b78e.png)
![image](https://user-images.githubusercontent.com/37489976/40349489-586c6e56-5dd9-11e8-94f1-665b79d73a05.png)
![image](https://user-images.githubusercontent.com/37489976/40349496-632d16f6-5dd9-11e8-94b4-f65334637a54.png)

**Comment by WENLINRONG** [comment]
http://he.yidida.top
用户名：1368900761
密码：123456

**Comment by WENLINRONG** [comment]
是三个问题，问题一：一票多件的，单号扫入后，选中单件单号，电子秤重量被清空。问题二:电子秤重量被清空后，点开设置，发现端口显示空白。问题三：把电子秤上的重量动一下，电池秤重新对接重量，但是重量变成了编辑状态

**Comment by WENLINRONG** [comment]
问题反馈：问题一：一票多件的，单号扫入后，选中单件单号，电子秤重量被清空
问题二：把电子秤上的重量动一下，电池秤重新对接重量，但是重量变成了编辑状态 @iamforrest

**Comment by iamforrest** [comment]
@WENLINRONG 已经好了，其实第二点和第三点本身就没问题的。只是可能你之前觉得字不是灰色，误会了可以编辑而已。

**Comment by WENLINRONG** [comment]
经测试，已解决
