### ISSUE TITLE
一代国际：新建报价，生效时间的默认值保留其他的默认值清空 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#393]
1，新建报价，生效时间的默认值保留其他的默认值清空 
![qq 20180522171220](https://user-images.githubusercontent.com/37489976/40353561-5de9cd96-5de4-11e8-9ef1-c36f6636b0eb.jpg)
2，报价--基本界面的起运地设置为必填

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
