### ISSUE TITLE
运费试算界面关闭后，界面数据清空

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#395]
运费试算界面关闭后，界面数据清空
![qq 20180522173542](https://user-images.githubusercontent.com/37489976/40354572-c2b932a0-5de6-11e8-8bb2-0a5192971947.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
