### ISSUE TITLE
导入预报，选择字段后，点确认，界面消失了，数据也没有进入

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#398]
1，导入预报（1000票预报导入），选择字段后，点确认，界面消失了，数据也没有进入
2，导入到草稿，导入完毕后，系统没有提示操作成功且即时的刷新界面
![image](https://user-images.githubusercontent.com/37489976/40401806-de01ced4-5e7a-11e8-8140-253524446ce0.png)

**Comment by tomlamcn** [comment]
文那边测试是 六七票的时候可以，但是1000票的时候不行。我看日志没有报错@iamforrest
![image](https://user-images.githubusercontent.com/37174434/40402518-cc518d6a-5e7e-11e8-92e8-42158a4faa8f.png)

**Comment by tomlamcn** [comment]
使用nginx的时候导入运单不会弹出错误提示
原本这个日志下面那句应该弹出错误原因。
[taskExecutor-5] INFO  c.i.w.c.ExcelImportController.analysisError - end
![cc0be391c7cc358c5717666d3668a498](https://user-images.githubusercontent.com/37174434/40409903-d1edd524-5e9e-11e8-90da-693d467b0482.jpg)
@iamforrest
