### ISSUE TITLE
系统标签支持API下载----API支持把系统档案界面的地址标签数据传通过API传给客户的系统后可以下载

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#403]
系统标签支持API下载---API支持把系统档案界面的地址标签数据传通过API传给客户的系统后可以下载
（在我们的客户API，原来可下载LB标签和发票的，现在增加可下载系统标签）

**Comment by iamforrest** [comment]
1. 调通代码
2. 更新好API文档

@likeasb

**Comment by WENLINRONG** [comment]
经测试，已解决
