### ISSUE TITLE
录单界面的货物特性界面增加查找搜索框

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#406]
录单界面的货物特性界面增加查找搜索框

**Comment by WENLINRONG** [comment]
![image](https://user-images.githubusercontent.com/37489976/40530731-80eae83a-602c-11e8-82aa-9049fa3576bb.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
