### ISSUE TITLE
原来的分区号，改为序号，加一个报价分区号（从导入那里取，可以修改，且判定重复，可为空)；分区栏和价格栏加一列分区号

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#413]
1,原来的分区号，改为序号，加一个报价分区号（从导入那里取，可以修改，且判定重复，可为空)；
2,分区栏和价格栏加一列分区号
![image](https://user-images.githubusercontent.com/37489976/40605186-11aa7214-6294-11e8-9335-4c0d1abfc8bf.png)
![image](https://user-images.githubusercontent.com/37489976/40605189-15a92554-6294-11e8-9f7f-3aa184b8c35e.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
