### ISSUE TITLE
支持一次性导入分区和国家（逗号，顿号，分号,正斜杠，反斜杠都可以分割国家）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#416]
支持一次性导入分区和国家（逗号，顿号，分号，正斜杠，反斜杠都可以分割国家）
 1. 按左右分区号自动归区，一行一个国家
2. 一行多国家
3,左列分区行是合并单元格，右国家

![qq 20180528164136](https://user-images.githubusercontent.com/37489976/40605784-082f6dd2-6296-11e8-8365-50d4b4c94171.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
