### ISSUE TITLE
待退货---退货提醒界面的提示内容异常 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#42]
待退货---退货提醒界面的提示内容异常 
![--- qq 20180329182200](https://user-images.githubusercontent.com/37489976/38084132-440b93ea-337e-11e8-8774-de48db7d177a.jpg)

**Comment by WENLINRONG** [comment]
问题反馈：退货i提醒显示异常
@tomlamcn 
![image](https://user-images.githubusercontent.com/37489976/39356251-269c792a-4a42-11e8-9213-cf67c2db888a.png)

**Comment by tomlamcn** [comment]
之前的版本应该已经改好了的。@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
