### ISSUE TITLE
报价没有做任何修改的时候，点确定不要生成新版本，确认按钮就等同于关闭

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#424]
报价没有做任何修改的时候，点确定不要生成新版本，确认按钮就等同于关闭

![image](https://user-images.githubusercontent.com/37489976/40608158-2e130908-629d-11e8-88ed-84ea6b4fa38c.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
