### ISSUE TITLE
添加itdida转单设置模板（易抵达系统内对接），只要输入itdida网址，登录账号和密码，即可对接

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#425]
添加itdida转单设置模板（易抵达系统内对接），只要输入itdida网址，登录账号和密码，即可对接
![image](https://user-images.githubusercontent.com/37489976/40608222-626a5bd4-629d-11e8-8315-704d694ff602.png)
![image](https://user-images.githubusercontent.com/37489976/40608246-70c9fc0c-629d-11e8-9fec-4d2149341294.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG    请测试确认
