### ISSUE TITLE
将生效的报价不能修改

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#427]
将生效的报价不能修改
![qq 20180529102536](https://user-images.githubusercontent.com/37489976/40635074-dabb90fc-632a-11e8-9aaf-2972f1442dd5.png)

**Comment by WENLINRONG** [comment]
赶今天的迭代

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
