### ISSUE TITLE
新客户登记----修改客户编号后，修改的编号保存不了数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#429]
新客户登记----修改客户编号后，修改的编号保存不了数据
![image](https://user-images.githubusercontent.com/37489976/40635758-2d0cf384-632e-11e8-8da9-63f56f7e0c89.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
