### ISSUE TITLE
主界查询界面的承运商跟起运地不能表头搜索

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#430]
主界查询界面的承运商跟起运地不能表头搜索

**Comment by WENLINRONG** [comment]
![qq 20180529110248](https://user-images.githubusercontent.com/37489976/40636093-f51d65ce-632f-11e8-8155-620f7ffa5909.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
