### ISSUE TITLE
导入多段续重的识别及算法

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#444]
导入多段续重的识别及算法
1.要能识别这种导入的是首续重方式
2.自动填充各重量段的首重
![image](https://user-images.githubusercontent.com/37489976/40771543-2b911706-64f0-11e8-9046-465a5718347c.png)

![qq 20180531163341](https://user-images.githubusercontent.com/37489976/40771619-679c0e36-64f0-11e8-8dd2-8760f5e6ce6d.jpg)

**Comment by iamforrest** [comment]
@WENLINRONG @wny123 我进一步优化和重构了价格清洗，所以所有的类型的报价都测一下，算的对不对
