### ISSUE TITLE
收款登记，付款登记的折算币种默认的RMB去掉，默认为空且设置为必填项，要用户一定要选

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#446]
收款登记，付款登记的折算币种默认的RMB去掉，默认为空且设置为必填项，要用户一定要选
![rmb qq 20180601095125](https://user-images.githubusercontent.com/37489976/40816836-9d594f7a-6581-11e8-93f4-9d0f850a09d8.jpg)

**Comment by WENLINRONG** [comment]
6月4日-9日的开发任务

**Comment by wny123** [comment]
@WENLINRONG @tomlamcn 
账户也要默认为空

**Comment by tomlamcn** [comment]
已更新到alpha

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
1，账户切换时，折算币种没有对应的切换跟显示
![image](https://user-images.githubusercontent.com/37489976/41761550-48bda72c-762a-11e8-8105-284c192597cb.png)
2，应收财务界面，应付财务界面的收付款登记界面的折算币种默认显示为空且设置为必填.
![image](https://user-images.githubusercontent.com/37489976/41761659-b61a9fbe-762a-11e8-995b-2e4e33691845.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
