### ISSUE TITLE
基本界面修改申报信息及申报价值，系统报错 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#447]
基本界面修改申报信息及申报价值，系统报错

**Comment by WENLINRONG** [comment]
![qq 20180601105111](https://user-images.githubusercontent.com/37489976/40818568-4e00b54a-658a-11e8-962f-d3f0ec64f51d.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
