### ISSUE TITLE
基础数据---新建国家界面的CANCEL，OK按钮改成取消跟报错按钮

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#457]
基础数据---新建国家界面的CANCEL，OK按钮改成取消跟报错按钮

![image](https://user-images.githubusercontent.com/37489976/40895663-4cb28a96-67e3-11e8-9b8b-e471fb4d7819.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
经测试，已解决
