### ISSUE TITLE
基础数据---新建问题件模板界面放大，把窗口放大，不要出现滚动条

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#459]
基础数据---新建问题件模板界面放大，把窗口放大，不要出现滚动条
![image](https://user-images.githubusercontent.com/37489976/40895868-57e45aba-67e4-11e8-87ab-12932f40385d.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
