### ISSUE TITLE
基础数据----汇率界面---把汇率分成客户汇率跟代理汇率

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#460]
基础数据----汇率界面---把汇率分成客户汇率跟代理汇率
![image](https://user-images.githubusercontent.com/37489976/40895919-8de84554-67e4-11e8-859f-c725d8044aa0.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   涉及到汇率的地方都可能需要测试确认一下

**Comment by WENLINRONG** [comment]
问题反馈： @johnnyZchan 
1，收款单，付款单界面的汇率对接基础数据的汇率经常显示不出来



2，收款单，付款单界面的汇率不能手动输入汇率或者修改汇率

**Comment by WENLINRONG** [comment]
经测试，已解决
