### ISSUE TITLE
应付财务【增加字段：对账人、所有应收、所有应付、毛利润（应收总额-应付总额）】

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#469]
应付财务【增加字段：对账员、所有应收、所有应付、毛利润】

**Comment by tomlamcn** [comment]
@WENLINRONG 注意下 新建费用 和修改费用后的数据是否还正确。

**Comment by WENLINRONG** [comment]
这个报错就是跟下午改基本的报错一样的，
 @tomlamcn 现在是费用登记报错
![image](https://user-images.githubusercontent.com/37489976/41107325-ba0eaa98-6aa4-11e8-85d7-9f27fea70b0f.png)

**Comment by tomlamcn** [comment]
@WENLINRONG 上版本已经改好

**Comment by WENLINRONG** [comment]
经测试，已解决
