### ISSUE TITLE
客户档案，代理档案列表，每列增加排序，增加余额和预估余额的合计

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#472]
客户档案，代理档案列表，每列增加排序，增加余额和预估余额的合计
![image](https://user-images.githubusercontent.com/37489976/40897589-8126e5be-67ee-11e8-994e-99129be50967.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
