### ISSUE TITLE
新建报价时复制价格的EXcel能识别单元格中如【***、- - -，空】等非数值型的字符时，为0

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#475]
1，新建报价时复制价格的EXcel能识别单元格中如【***、- - -,空白的】等非数值型的字符时，为0
![image](https://user-images.githubusercontent.com/37489976/40897837-ee54989c-67ef-11e8-8cad-e349f632569c.png)
![image](https://user-images.githubusercontent.com/37489976/40897996-13b97a48-67f1-11e8-9877-3960fe35aec2.png),
2，为空的也要自动填充为0
![image](https://user-images.githubusercontent.com/37489976/40951081-183d4f10-68a8-11e8-8b56-de386ec07807.png)

**Comment by wny123** [comment]
测试
1.中间有空的单元格时，不会自动填写0去占位，
2.单元格为***或0或-字符，导入正常用0占位 @WENLINRONG @chenguolin123

**Comment by WENLINRONG** [comment]
经测试，已解决
