### ISSUE TITLE
主界面排序的优化（应收运费，应收附加费，应收合计，应付运费，应付附加费，应付合计，毛利，毛利率）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#478]
主界面排序的优化（应收运费，应收附加费，应收合计，应付运费，应付附加费，应付合计，毛利，毛利率）
![image](https://user-images.githubusercontent.com/37489976/40908919-bbce57c0-681a-11e8-9f77-90d29c35a78e.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
