### ISSUE TITLE
应付财务---用空运单号分组查询运单数据后，进入到费用登记界面，点任何选项都会出现两个

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#480]
应付财务---用空运单号分组查询运单数据后，进入到费用登记界面，点任何选项都会出现两个
![image](https://user-images.githubusercontent.com/37489976/40951692-a9922e66-68aa-11e8-9700-bfae7f404654.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
