### ISSUE TITLE
待排货，待退货界面的重新排货---手动排货---已失效，选择报价时，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#482]
重新排货---手动排货---已失效，选择报价时，系统报错

**Comment by WENLINRONG** [comment]
![image](https://user-images.githubusercontent.com/37489976/40960468-5d7bf606-68d2-11e8-8c53-6c70c6d14296.png)
![-- qq 20180605145601](https://user-images.githubusercontent.com/37489976/40960493-783baab8-68d2-11e8-9fe0-5641eb6678db.png)
![image](https://user-images.githubusercontent.com/37489976/40960502-7cbac970-68d2-11e8-93f4-633158a98203.png)

**Comment by tomlamcn** [comment]
这个是不是改好了？测试我试了没问题？

**Comment by WENLINRONG** [comment]
经测试，已解决
