### ISSUE TITLE
导入客户系统判定错误，模板多了一列预警额度导入不了，导致分公司跟销售显示错位，系统识别不到 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#484]
导入客户系统判定错误，模板多了一列预警额度导入不了，导致分公司跟销售显示错位，系统识别不到 
![image](https://user-images.githubusercontent.com/37489976/40963017-d2de1490-68d9-11e8-949a-c0d8f01c1dd4.png)

**Comment by WENLINRONG** [comment]
[11-导入客户daoRuKeHu.xlsx](https://github.com/itdida/itdida-issues/files/2071479/11-.daoRuKeHu.xlsx)

**Comment by wny123** [comment]
导入测试，正常

**Comment by WENLINRONG** [comment]
经测试，已解决
