### ISSUE TITLE
排货规则界面----已失效报价对应的渠道不消失，把排货规则标黄且把失效的发货渠道对应的价格标黄

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#485]
排货规则界面----已失效报价对应的渠道不消失，把排货规则标黄且把失效的发货渠道对应的价格标黄 
![image](https://user-images.githubusercontent.com/37489976/41220427-f67dc030-6d93-11e8-9984-fa49a3f5df44.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，也解决
