### ISSUE TITLE
客户端---打印转单LABLE打印不了

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#488]
客户端---打印转单LABLED的打印不了
![--- labled qq 20180606160727](https://user-images.githubusercontent.com/37489976/41025237-f1771ee0-69a3-11e8-8973-a0f8ce54c2c9.png)

**Comment by WENLINRONG** [comment]
赶今晚迭代

**Comment by tomlamcn** [comment]
@WENLINRONG 昨天的紧急迭代好了

**Comment by WENLINRONG** [comment]
经测试，已解决
