### ISSUE TITLE
收款单，付款单界面的汇率对接基础数据的汇率经常显示不出来

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#489]
1，收款单，付款单界面的汇率对接基础数据的汇率经常显示不出来
![qq 20180606173830](https://user-images.githubusercontent.com/37489976/41031676-db3353fa-69b3-11e8-9165-338c9131d8f3.png)

2，汇率现在不能手动输入修改
![qq 20180606173941](https://user-images.githubusercontent.com/37489976/41032248-5d29bd26-69b5-11e8-8ab3-c0ca1ab0e998.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   已修正

**Comment by WENLINRONG** [comment]
经测试，已解决
