### ISSUE TITLE
基础数据客户汇率，代理汇率修改后，客户预估余额汇总值，代理预估余额的汇总值没有重新计算

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#490]
基础数据客户汇率，代理汇率修改后，客户预估余额汇总值，代理预估余额的汇总值没有重新计算
![image](https://user-images.githubusercontent.com/37489976/41034988-e522a26c-69bd-11e8-94af-7c0761601f76.png)
（160.42*0.85）-（160.42*0.8）=136.357-128.336=8.021
35.62-27.62=8.021

**Comment by johnnyZchan** [comment]
@WENLINRONG   已修正

**Comment by WENLINRONG** [comment]
经测试，已解决
