### ISSUE TITLE
承运商CNDHL的获取转单号失败，一直显示接口返回空数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#496]
承运商CNDHL的获取转单号失败，一直显示接口返回空数据
![cndhl qq 20180610094645](https://user-images.githubusercontent.com/37489976/41197498-641322b8-6c93-11e8-8919-7371e9dbbd6b.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
