### ISSUE TITLE
主运单列表，收、发货渠道、中文国家增加多行过滤【双击出来的弹窗，与客户单号多行过滤一样】

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#500]
主运单列表，收、发货渠道、中文国家增加多行过滤【双击出来的弹窗，与客户单号多行过滤一样】
![image](https://user-images.githubusercontent.com/37489976/41212300-72e9b306-6d6f-11e8-8e99-392dc725d6bd.png)

**Comment by tomlamcn** [comment]
@WENLINRONG
