### ISSUE TITLE
报价-基本-日期选择框增加确认关闭按钮

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#501]
报价-基本-日期选择框增加确认关闭按钮
![image](https://user-images.githubusercontent.com/37489976/41212357-ce81599e-6d6f-11e8-9bdb-d79e8f473d94.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   经尝试，primefaces的组件并不支持，只有一个关闭按钮，且没有什么效果仅仅是把弹出的时间选择框关闭而已。

**Comment by johnnyZchan** [comment]
@WENLINRONG   这个可以关闭了，实现不了，也没什么太大必要去花时间解决了
