### ISSUE TITLE
报价附加费-收费条件-自定义组合增加：单票实重、单票材积重

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#503]
报价附加费-收费条件-自定义组合增加：单票实重、单票材积重
![image](https://user-images.githubusercontent.com/37489976/41212437-7d03ecc0-6d70-11e8-85a3-bc50015483df.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
