### ISSUE TITLE
全球城市邮编校验接口【a-用UPS地址验证接口在系统参数中设置UPS「AccessLicenseNumber密钥：UserId登录账号：Password密码：」用*号隐藏只显示后三位，b-自动校验设定「状态=已预报、承运商=可多选」自动校验规则-草稿确认预报、EXCEL导入已预报、API导入已预报，c-校验结果不对等的，将查询结果保存在问题处理，标题为「城市邮编不符」，收货后是问题件，在已预报状态客户可见】，在已预报列表增加一列为「城市邮编查询」，存入备注信息，格式为城市xxx，邮编xxx，方便操作修改和查看；d-打单录入/收货录单，国家城市邮编三格写完后自动查【开发文档下载https://www.ups.com/upsdeveloperkit/downloadresource?loc=zh_HK 地址確認 - 城市、州、郵政編碼，驗證城市、州以及郵政編碼資訊是否有效。】---通过触发器，API的单证模板去掉

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#505]
全球城市邮编校验接口【a-用UPS地址验证接口在系统参数中设置UPS「AccessLicenseNumber密钥：UserId登录账号：Password密码：」用*号隐藏只显示后三位，b-自动校验设定「状态=已预报、承运商=可多选」自动校验规则-草稿确认预报、EXCEL导入已预报、API导入已预报，c-校验结果不对等的，将查询结果保存在问题处理，标题为「城市邮编不符」，收货后是问题件，在已预报状态客户可见】，在已预报列表增加一列为「城市邮编查询」，存入备注信息，格式为城市xxx，邮编xxx，方便操作修改和查看；d-打单录入/收货录单，国家城市邮编三格写完后自动查【开发文档下载https://www.ups.com/upsdeveloperkit/downloadresource?loc=zh_HK 地址確認 - 城市、州、郵政編碼，驗證城市、州以及郵政編碼資訊是否有效。】---**通过触发器，API的单证模板去掉**
![image](https://user-images.githubusercontent.com/37489976/41212497-efab6f82-6d70-11e8-9169-a04033f596e5.png)

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by wny123** [comment]
@WENLINRONG @chenguolin123 
当前
新建问题件：客户名：AC电子的客户单号：2862153211552的国家名是：美国的城市名NEW YORK 跟邮编11不对应，请重新提供正确的城市名跟邮编

优化
将系统中查询到正确的城市和邮编提示出来。如城市NEW YORK、邮编10000-10015

全球所有国家和地区都有城市名，可按国家+城市名查询，将对应的邮编提示出来

**Comment by tomlamcn** [comment]
全球所有国家和地区都有城市名，可按国家+城市名查询，将对应的邮编提示出来
@WENLINRONG @wny123 
这个显示要显示在哪里？

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：现在是不对应也触发不了问题件
![image](https://user-images.githubusercontent.com/37489976/41756078-0d6c28aa-760d-11e8-9d23-f92b3d4e24e1.png)

’
这个触发器现在还是不会触发
现在是不对应也触发不了

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
