### ISSUE TITLE
应收财务费用添加增加一个备注框为「内部备注」， 不需要「是否允许客户可见」，每个应收费用增加此备注框「内部备注」， 应收财务列表费用视图增加此一列

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#510]
应收财务费用添加增加一个备注框为「内部备注」，
不需要「是否允许客户可见」，每个应收费用增加此备注框「内部备注」，
应收财务列表费用视图增加此一列
![image](https://user-images.githubusercontent.com/37489976/41221916-2716c4e0-6d98-11e8-8c99-876f94852286.png)

**Comment by WENLINRONG** [comment]
问题反馈： @tomlamcn 内部备注 的在客户端要隐藏
![image](https://user-images.githubusercontent.com/37489976/41402063-ea3b8ff2-6ff3-11e8-84b7-e09132cbcb37.png)

**Comment by tomlamcn** [comment]
这个上个版本迭代的时候就改好了吧？

**Comment by WENLINRONG** [comment]
经测试，已解决
