### ISSUE TITLE
无纸化国家与转单账号对接设置

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#512]
无纸化国家与转单账号对接设置
![image](https://user-images.githubusercontent.com/37489976/41222473-83bd5e1a-6d99-11e8-918f-a3020ad2bd49.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 国家勾了无纸化，不能获取转单号
![image](https://user-images.githubusercontent.com/37489976/41391604-24816a54-6fce-11e8-8e3a-380f1e26b532.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
