### ISSUE TITLE
应收财务，应付财务界面的数据筛选后不能二次复制

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#515]
应收财务，应付财务界面的数据筛选后不能二次复制

![image](https://user-images.githubusercontent.com/37489976/41270757-9c879b94-6e3f-11e8-9c70-7710c128107a.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
