### ISSUE TITLE
客户端主界面增加显示客户的预估余额（按照币种分开显示） 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#521]
客户端主界面增加显示客户的预估余额（按照币种分开显示）

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
@mrrc333 客户端没有分‘币种显示预估余额（现在显示的是预估余额折算）
![image](https://user-images.githubusercontent.com/37489976/47281451-c900ec80-d60d-11e8-9850-4352d213d6cd.png)
![image](https://user-images.githubusercontent.com/37489976/47281459-d1592780-d60d-11e8-8277-492ab3e6fdb6.png)

**Comment by mrrc333** [comment]
@WENLINRONG
