### ISSUE TITLE
付款单界面的到账时间显示空白，到账时间填了就按照填的显示，没填就默认跟收款单保存时间样

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#532]
付款单界面的到账时间显示空白，到账时间填了就按照填的显示，没填就默认跟收款单保存时间样
![image](https://user-images.githubusercontent.com/37489976/41338789-bd4e477e-6f25-11e8-98bf-cb425d812f84.png)

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by wny123** [comment]
@WENLINRONG 
没有时间默认值上来
