### ISSUE TITLE
费用添加界面显示异常

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#533]
费用添加界面显示异常
![image](https://user-images.githubusercontent.com/37489976/41340108-2d7f33c0-6f29-11e8-9d32-ec908b203083.png)
2，费用编辑也点不了 
![image](https://user-images.githubusercontent.com/37489976/41340536-32deb2fe-6f2a-11e8-9f4b-3be64e35966d.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试。已解决
