### ISSUE TITLE
运费试算不好选中复制（选不了要选择的内容）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#537]
运费试算不好选中复制（选不了要选择的内容）
![image](https://user-images.githubusercontent.com/37489976/41400537-fd8e7852-6fef-11e8-8ba0-f8895ee74372.png)

**Comment by iamforrest** [comment]
@WENLINRONG 部署测试验证一下

**Comment by WENLINRONG** [comment]
经测试，已解决
