### ISSUE TITLE
批量修改附加费，提交保存，报价渠道重复没有做重复判定，导致同一代理，同一渠道，存在多份成本价，同一渠道，同一客户存在多份指定报价跟多份公开的客户报价

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#539]
批量修改附加费，提交保存，报价渠道重复没有做重复判定，导致同一代理，同一渠道，存在多份成本价，同一渠道，同一客户存在多份指定报价跟多份公开的客户报价
![image](https://user-images.githubusercontent.com/37489976/41406090-09ac425a-6ffe-11e8-8556-8d9a54d99aa9.png)

**Comment by iamforrest** [comment]
@WENLINRONG 已解决

**Comment by WENLINRONG** [comment]
经测试，已解决
