### ISSUE TITLE
易抵达系统内对接的目前问题 1.API导入、EXCEL导入，问题提示为【获取转单号失败，原因：获取转单号为空】「API导入客户单号：YD15272339948107390；EXCEL导入客户单号：2395148541」 2.从其它运单复制，问题提示为【新建问题件：获取转单号失败，原因：系统错误,请稍后重试！ 】「复制的客户单号：9180603926424」

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#548]
系统内对接的目前问题
1.API导入、EXCEL导入，问题提示为【获取转单号失败，原因：获取转单号为空】「API导入客户单号：YD15272339948107390；EXCEL导入客户单号：2395148541」
2.从其它运单复制，问题提示为【新建问题件：获取转单号失败，原因：系统错误,请稍后重试！ 】「复制的客户单号：9180603926424」
![image](https://user-images.githubusercontent.com/37489976/41463044-96512292-70c7-11e8-9534-3594730d731a.png)

**Comment by WENLINRONG** [comment]
现在确认的问题是API导入的内部对接的单获取转单号不成功 @mrrc333 
![image](https://user-images.githubusercontent.com/37489976/41699977-06457a5e-7559-11e8-99ec-8b9dcecfea8e.png)

**Comment by mrrc333** [comment]
提示有误~

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
