### ISSUE TITLE
燃油修改生效时间跟失效是时间的限制取消

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#559]
应收燃油，应付燃油，销售成本的生效时间，失效时间都要独立显示跟维护且支持单独修改生效时间跟失效是时间
![image](https://user-images.githubusercontent.com/37489976/41498557-2483663e-71a3-11e8-90b1-6a00ceaebca6.png)

**Comment by WENLINRONG** [comment]
一定要记得修复历史数据！！！

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
