### ISSUE TITLE
报价管理界面增加渠道管理界面增加类型（收货渠道，发货渠道），类别，LA跟发票是否可见（全部客户，部分客户---有列表）增加按照客户结算方式（自打单可以默认可见）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#560]
报价管理界面增加渠道管理界面增加类型（收货渠道，发货渠道），类别，LA跟发票是否可见（全部客户，部分客户---有列表）增加按照客户结算方式（自打单可以默认可见）
1，渠道管理界面增加类型（收货渠道，发货渠道），类别，LA跟发票是否可见（全部客户，部分客户---有列表）
2，报价渠道名的只能选，对接渠道管理界面选数据。
3，收货界面的渠道从渠道管理选，报价失效后，收货渠道的备选项也要过滤。

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
