### ISSUE TITLE
运单主表、应收、应付允许折算金额筛选功能>0,<0 （先迫切的字段增加这个搜索过滤的功能）---赶本周迭代

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#573]
运单主表、应收、应付允许折算金额筛选功能>0,<0 （先迫切的字段增加这个搜索过滤的功能）
![image](https://user-images.githubusercontent.com/37489976/41713674-772ce2e4-7580-11e8-9b39-c75c4981eda4.png)

**Comment by likeasb** [comment]
支持>=,<=,>,<,!=(不等于)
