### ISSUE TITLE
导入只有一列单号 要能自动识别单号类型 客户单号 转单号 系统单号（本周迭代）a.识别单号是否存在，b.存在的，对比导入时选中的代理名称与系统中是否相同

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#577]
导入只有一列单号 要能自动识别单号类型 客户单号 转单号 系统单号（本周迭代）a.识别单号是否存在，b.存在的，对比导入时选中的代理名称与系统中是否相同
![image](https://user-images.githubusercontent.com/37489976/41715289-877230aa-7585-11e8-887d-5cc06679b169.png)

**Comment by chenguolin123** [comment]
我们是选择表头的，不可以模糊对应单号
