### ISSUE TITLE
一代需求：应收财务界面----公开备注加旁边加上备注： 客户系统可见 （正常迭代）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#578]
应收财务界面----公开备注加旁边加上备注： 客户系统可见 
![image](https://user-images.githubusercontent.com/37489976/41753657-528073da-7601-11e8-9fe1-748e44e3291c.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
