### ISSUE TITLE
一代需求：客户档案的去掉付款时间（正常迭代）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#580]
一代需求：客户档案的去掉付款时间（正常迭代）
![image](https://user-images.githubusercontent.com/37489976/41753768-001e5da4-7602-11e8-89b4-94d2caa21f69.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
