### ISSUE TITLE
一代需求：新客户登记、客户导入、客户档案增加签约日期栏位（默认空），并在运单主表增加此栏位（上线前）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#582]
在新客户登记、客户导入、客户档案增加签约日期栏位（默认空），并在运单主表增加此栏位（上线前）
![image](https://user-images.githubusercontent.com/37489976/41753929-e1bc0d56-7602-11e8-9969-287ebe91134e.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
