### ISSUE TITLE
一代需求：报价分区可以新增可删可选的权限

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#589]
报价分区可以新增可删可选的权限
![image](https://user-images.githubusercontent.com/37489976/41838223-6822b3f4-7892-11e8-8ad3-4e2ae1d69c9c.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
@johnnyZchan 问题反馈：添加一行分区后，添加过来，系统报错
![image](https://user-images.githubusercontent.com/37489976/41981875-90249a40-7a5c-11e8-810f-2782747542c6.png)


![image](https://user-images.githubusercontent.com/37489976/41981794-5c43fffe-7a5c-11e8-9333-7500e5e41f44.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   错误无法重现
