### ISSUE TITLE
一代需求:报价主页面增加字段。 燃油，附加费名称。(上线前)

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#590]
报价主页面增加字段。 燃油，附加费名称。(上线前)

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
问题反馈：应该代理成本对应付燃油，客户报价对接应收燃油，销售成本对接销售燃油
@johnnyZchan 
![image](https://user-images.githubusercontent.com/37489976/41979880-b218aca4-7a57-11e8-9ed4-19348115a605.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG    请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
