### ISSUE TITLE
与哲盟运单推送API对接

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#6]
与哲盟运单推送API对接
[yde预报信息推送接口文档-推送收货数据到哲盟.docx](https://github.com/itdida/itdida-issues/files/1823744/yde.-.docx)

[预报数据接口文档.zip](https://github.com/itdida/itdida-issues/files/1823745/default.zip)

**Comment by wny123** [comment]
TEST

**Comment by chenguolin123** [comment]
已完成

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
测试通过
