### ISSUE TITLE
一代需求：系统导入预报的模板要支持可以保存多个，也要支持对已保存模板删除

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#608]
系统导入预报的模板要支持可以保存多个，也要支持对已保存模板删除
![image](https://user-images.githubusercontent.com/37489976/41805332-fe0d7ad4-76da-11e8-8405-7931c171ea15.png)

**Comment by mrrc333** [comment]
@WENLINRONG 可删除，新增会删除之前重名的

**Comment by WENLINRONG** [comment]
经测试，已解决
