### ISSUE TITLE
一代需求：组织架构---全选导出，导出数据空白

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#611]
组织架构---全选导出，导出数据空白
![image](https://user-images.githubusercontent.com/37489976/41807548-c0a7526e-7702-11e8-8a09-76c41fabe4fa.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
导出还是显示空白 @mrrc333

**Comment by WENLINRONG** [comment]
经测试，已解决
