### ISSUE TITLE
DHL偏远数据要重新导入最新的偏远数据以便系统判定偏远的准确性

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#618]
DHL偏远数据要重新导入最新的偏远数据以便系统判定偏远的准确性

**Comment by WENLINRONG** [comment]
[2018 dhl_express_remote_areas.zip](https://github.com/itdida/itdida-issues/files/2131669/2018.dhl_express_remote_areas.zip)

**Comment by johnnyZchan** [comment]
[pian_yuan.sql.zip](https://github.com/itdida/itdida-issues/files/2136918/pian_yuan.sql.zip)
附件是最新的偏远数据，请测试确认吧

**Comment by johnnyZchan** [comment]
@WENLINRONG 
已完成，请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
