### ISSUE TITLE
客户档案，代理档案，双击数据，系统报错 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#623]
客户档案，代理档案，双击数据，系统报错 
![image](https://user-images.githubusercontent.com/37489976/41888506-637fd060-7938-11e8-8ec6-dffa97d8cc0b.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
