### ISSUE TITLE
CTRL加enter保存录单后，提示框错误，提示请输入正确的国家，这个提示是多余的

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#624]
CTRL加enter保存录单后，提示框错误，提示请输入正确的国家，这个提示是多余的

![ctrl enter qq 20180626144359](https://user-images.githubusercontent.com/37489976/41894184-b1dc8ea2-7950-11e8-9bfc-183800d75f34.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
