### ISSUE TITLE
一代国际：待退货界面点确认退货，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#629]
一代国际：待退货界面点确认退货，系统报错
![image](https://user-images.githubusercontent.com/37489976/41945109-f59e8b58-79dd-11e8-8505-7168a7ad08a6.png)

**Comment by WENLINRONG** [comment]
赶今天的迭代

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
