### ISSUE TITLE
银行账户，增加账户总表，可以方便查看总览账户余额

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#632]
总账：银行账户、客户账户、代理账户
1.每列排序（去看这个，有需求图
排序 ，金额范围过滤查找，都要的）
2.数值型列，筛选
3.权限，要能分别勾选
4，总账表的界面的所有字段加加排序跟检索
![image](https://user-images.githubusercontent.com/37489976/42203018-174f8d50-7ed0-11e8-84a4-c8e40b02dc44.png)

[总账.pdf](https://github.com/itdida/itdida-issues/files/2152882/default.pdf)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
