### ISSUE TITLE
主界面跟扫单助手界面包号封包后，单号还能扫入包号内，系统没有提示跟拦截

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#636]
1，主界面跟扫单助手界面包号封包后，单号还能扫入包号内，系统没有提示跟拦截
2，未封包号的拦截发货。
![image](https://user-images.githubusercontent.com/37489976/41967558-71870de8-7a34-11e8-9052-8bb90397777b.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG    请测试确认
