### ISSUE TITLE
一代需求----批号管理界面增加包号列表

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#64]
批号管理界面增加包号列表

![qq 20180330190515](https://user-images.githubusercontent.com/37489976/38135932-7c1d479a-344d-11e8-83bd-531bedc99217.png)

**Comment by iamforrest** [comment]
@mrrc333 
1. 建立一个包号新表，类似收货批号那种
2. 改写dealPihao方法，支持包号
![image](https://user-images.githubusercontent.com/2240276/38712308-565689ee-3efd-11e8-8e41-68f1c3d8eb08.png)
3. 前端加一个模块页面 - 包号，类似发货批号，退货批号等等

**Comment by WENLINRONG** [comment]
经测试，已解决
