### ISSUE TITLE
包号解封后，点发货，系统报错 (一代的包号：YDFDX18062805）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#641]
包号解封后，点发货，系统报错 
![image](https://user-images.githubusercontent.com/37489976/42018791-c1c81a66-7ae5-11e8-9996-8f789d58f6f1.png)
![image](https://user-images.githubusercontent.com/37489976/42018797-c74d16f8-7ae5-11e8-86f9-c9069bfa7c7f.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
