### ISSUE TITLE
扫单助手---限制条件界面增加包号状态跟报关方式

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#643]
扫单助手---限制条件界面增加包号状态跟报关方式
![image](https://user-images.githubusercontent.com/37489976/42022463-fa5ff2cc-7aef-11e8-92ab-486750dfbd6c.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
