### ISSUE TITLE
发货批号，收货批号，退货批号撤销或者新增后，汇总数据汇总的不准确 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#644]
发货批号，收货批号，退货批号撤销或者新增后，汇总数据汇总的不准确 
（删除上数据，有一票原来做了出货，后来发现有问题，不出了）
![image](https://user-images.githubusercontent.com/37489976/42022988-5ca83006-7af1-11e8-992b-82914f2391a9.png)

**Comment by WENLINRONG** [comment]
张总(203278) 16:14:57@安琪 跟进一下，转给 @│假◆貨┭ 跟进吧
--
张总(203278) 16:15:11紧急迭代，首先先修复数据，再找出漏的代码

**Comment by johnnyZchan** [comment]
@WENLINRONG    数据恢复的sql在印象笔记中

**Comment by WENLINRONG** [comment]
经常测试，已解决
