### ISSUE TITLE
包号界面支持包号发货且增加未封包，未发货标签

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#647]
包号界面支持包号发货且增加未封包，未发货标签
包号列表，增加包的发货状态【未发货，部分发出，已发货】-【紧急】
![image](https://user-images.githubusercontent.com/37489976/42031015-5cd6574a-7b07-11e8-9889-58ba3cfe56db.png)
两个标签 已发货 未发货。 默认未发货。

**Comment by iamforrest** [comment]
需求有改动
