### ISSUE TITLE
改写搜索的全文检索的表头搜索

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#65]
现在所有的COLUMN_TYPE_TEXT表头，都是直接用全文检索来搜索，数据多的时候，会特别卡。目前财务就已经暴露了。我已经改写了应收财务和应付财务的两个表头，系统单号和客户单号。你参考一下印象笔记《怎么优化全文检索的表头搜索》，先把财务的其他的类似表头都改写优化一下。
![87c6a7cc-5a60-4967-bfd7-80924456f3ed](https://user-images.githubusercontent.com/2240276/38159026-3fdc047a-34d3-11e8-9e40-2bc93727c77e.png)

**Comment by tomlamcn** [comment]
单号类的搜索增加 多行过滤功能。
@iamforrest

**Comment by tomlamcn** [comment]
现在的没有

                                    <p:autoComplete style="width:100%;border-width:0px;margin:0px"
                                                    rendered="#{column.filter.type eq constants.COLUMN_TYPE_AUTO_COMPLETE_XTDH}"
                                                    value="#{column.filter.whereSqlParameterMap['textValue']}"
                                                    placeholder="#{empty column.label ? '' : column.label}"
                                                    forceSelection="true"
                                                    completeMethod="#{autoCompleteController.xiTongDanHaoComplete}">
                                        <p:ajax event="itemSelect" update="@form" process="@form"/>
                                    </p:autoComplete>

**Comment by tomlamcn** [comment]
财务和主查询页面做了优化，可以看看现在搜索的性能。

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
