### ISSUE TITLE
主界面导出支持所看即所得

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#66]
一代需要导出运单列表，需求是，所看到的列和数据，根据选择，倒出来。类似原来的导出功能。
我已经做了

加上一个所看即所得.xlsx文件的模版，类型选择所看即所得，场景选择运单。

测试一下。

**Comment by iamforrest** [comment]
[所看即所得.xlsx](https://github.com/itdida/itdida-issues/files/1865427/default.xlsx)

**Comment by WENLINRONG** [comment]
应收财务，应付财务的导出，系统报错
![qq 20180402112847](https://user-images.githubusercontent.com/37489976/38182187-62114f30-366a-11e8-8133-6e6ad602559f.png)
@iamforrest

**Comment by iamforrest** [comment]
@WENLINRONG 重新部署就可以了。并且注意上传模版的时候，类型要所看即所得，场景是应收财务或者应付财务

**Comment by WENLINRONG** [comment]
问题反馈：
1，主查询界面，应收财务，应付财务所见即所得的就算拉到底把数据加载完了，但是导出也只有40条 @iamforrest 
![40 qq 20180404164013](https://user-images.githubusercontent.com/37489976/38297436-02333916-3827-11e8-96b5-1bfed3b25ac2.png)
2，套用模板的数据导出，点全选后的导出，导出的数据条数跟全选的条数对不上
![236 qq 20180404170607](https://user-images.githubusercontent.com/37489976/38298720-bc8eb09e-382a-11e8-91f7-5b271ad33ca4.png)

![qq 20180404171152](https://user-images.githubusercontent.com/37489976/38298988-7c1a3eb0-382b-11e8-856e-677ae410a9ea.jpg)

**Comment by iamforrest** [comment]
@WENLINRONG 已解决，等会部署测试环境测试一下

**Comment by WENLINRONG** [comment]
经测试，已解决
