### ISSUE TITLE
销售客服也要能看到她所属的客户档案的权限

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#661]
销售客服也要能看到她所属的客户档案的权限

![image](https://user-images.githubusercontent.com/37489976/42121935-cce125a0-7c6b-11e8-9caf-9660b28f665b.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
