### ISSUE TITLE
扫单助手-重量复核也要能识别系统参数中的重量限制

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#664]
扫单助手-重量复核也要能识别系统参数中的重量限制

**Comment by mrrc333** [comment]
@WENLINRONG alpha

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：收货渠道，发货渠道，单件重量的超过限制的，都加拦截跟提示

![image](https://user-images.githubusercontent.com/37489976/42210817-88914260-7ee4-11e8-86c8-b2c1e1edb3dc.png)

**Comment by mrrc333** [comment]
@WENLINRONG
