### ISSUE TITLE
在应收、应付财务，各加一个状态标签「费用为零」 应收财务：确认收货、确认退货后，应收费用为0的运单 应付财务：确认发货、确认退货后，应付费用为0的运单

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#666]
在应收、应付财务，各加一个状态标签「费用为零」
应收财务：确认收货、确认退货后，应收费用为0的运单
应付财务：确认发货、确认退货后，应付费用为0的运单

**Comment by WENLINRONG** [comment]
![image](https://user-images.githubusercontent.com/37489976/42125849-fe6208b6-7cb0-11e8-9ac3-9d37953f650b.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   和恩源讨论过，不新加这个画面了，由主页面的应收合计、应付合计、操作状态这三列的筛选功能来实现。

**Comment by WENLINRONG** [comment]
@wny123 张总  10:12:29
转给恩源，注明，等我跟他讨论好需求，让他在补充转给小明吧！

**Comment by iamforrest** [comment]
这个我记得之前跟恩源说了，在主列表自己去查就是了，没必要在财务还做一个运单列表。你跟恩源再确认一下，如果是，就关闭了
