### ISSUE TITLE
退后货，费用明细没有了，主列表的合计金额显示没有即时刷新显示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#668]
退后货，费用明细没有了，主列表的合计金额显示没有即时刷新显示
![qq 20180702145544](https://user-images.githubusercontent.com/37489976/42149297-301dcafe-7e08-11e8-8a49-46121a236f2b.jpg)

**Comment by WENLINRONG** [comment]
问题反馈：退货后，应收合计还是没有清零

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
