### ISSUE TITLE
系统运单没有按照先后顺序排列显示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#67]
系统运单没有按照先后顺序排列显示
![qq 20180402140239](https://user-images.githubusercontent.com/37489976/38185062-d7dcabe2-367e-11e8-92a0-b8e88e63aa8f.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
