### ISSUE TITLE
新建，复制，修改报价三个场景----价格跟分区行数不一致，系统没有拦截保存且提示（一行价格，两行分区 ） 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#673]
价格跟分区行数不一致，系统没有拦截保存且提示（一行价格，两行分区 ）
![image](https://user-images.githubusercontent.com/37489976/42156277-3e1e80ca-7e1d-11e8-9c94-08d75f1c6ca3.png)
![image](https://user-images.githubusercontent.com/37489976/42156289-43c46bc0-7e1d-11e8-949e-20606473c93a.png)

![image](https://user-images.githubusercontent.com/37489976/42156293-483a74e2-7e1d-11e8-94d2-46f4c7967ecb.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
