### ISSUE TITLE
已重新获取转单号，已自动重新获取转单号，更换label提醒，获取转单号失败 这几个自动提示的问题件，在系统参数中加一个选项，可由用户自定义是否启用

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#680]
已重新获取转单号，已自动重新获取转单号，更换label提醒，获取转单号失败
这几个自动提示的问题件，在系统参数中加一个选项，可由用户自定义是否启用

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：没有换单提醒的通知
![image](https://user-images.githubusercontent.com/37489976/43315008-42776476-91c7-11e8-86c2-fe8c65302504.png)

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：
1，打单录入界面的换单单后，运单没有生产换单提醒的问题件
![image](https://user-images.githubusercontent.com/37489976/43319494-890612ba-91d7-11e8-8a41-d2da05cc36e4.png)
2，主界面重新获取转单号后，没有换单号跟换单提醒的问题件

**Comment by mrrc333** [comment]
@WENLINRONG 更换label提醒之前是要改渠道，已重新获取转单号逻辑已修正

**Comment by WENLINRONG** [comment]
经测试，已解决
