### ISSUE TITLE
总账表不容易看到，菜单按钮要往上调

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#684]
总账表不容易看到，菜单按钮要往上调

**Comment by WENLINRONG** [comment]
![qq 20180703143704](https://user-images.githubusercontent.com/37489976/42202859-8a33b1c6-7ecf-11e8-9a1f-c1f2da8bbf84.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
