### ISSUE TITLE
打单录入界面增加加载显示港前问题件，把未关闭的港前问题件显示在前，把已解决的显示在后，将回复内容全部展开仅查看。已关闭的问题件按加画中横线显示

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#689]
打单录入界面增加加载显示港前问题件，把未关现在在前，把已解决的显示在后，将回复内容全部展开仅查看。已关闭的问题件按加画中横线显示
![image](https://user-images.githubusercontent.com/37489976/42215913-8f8efbf8-7ef2-11e8-8b6e-3bc78d3e1d54.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
