### ISSUE TITLE
用户自定义登录界面公司LOGO,公司介绍

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#7]
用户自定义登录界面公司LOGO,公司介绍
![logo _qq 20180226163826](https://user-images.githubusercontent.com/37489976/37578770-d7aac794-2b75-11e8-89b5-8f9a0d5b14d7.jpg)

**Comment by iamforrest** [comment]
![1fca54f9-f26b-4bfe-ae23-d591196e2bb8](https://user-images.githubusercontent.com/2240276/37697393-8dcafd58-2d17-11e8-8436-16a8f13ea2a0.jpeg)

**Comment by iamforrest** [comment]
客户端套件的下载地址要挪到右边来

![1fca54f9-f26b-4bfe-ae23-d591196e2bb8](https://user-images.githubusercontent.com/2240276/37697416-c31e0df6-2d17-11e8-99e8-df1ef7671712.jpeg)

**Comment by chenguolin123** [comment]
已完成
