### ISSUE TITLE
应收财务界面打开（费用视图的数据展示），用时 5.82S 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#70]
1，应收财务界面打开（费用视图的数据展示），用时 5.82S 
![5 82s qq 20180402183319](https://user-images.githubusercontent.com/37489976/38193412-89fc3d68-36a4-11e8-83fd-7d3e7e2e5ceb.png)
2，应收财务界面的字定义字段的设置保存，用时7.06S
![7 06s qq 20180402183509](https://user-images.githubusercontent.com/37489976/38193451-b37bf50c-36a4-11e8-9e0d-6122af940ea3.jpg)

**Comment by iamforrest** [comment]
@tomlamcn @WENLINRONG 确定测试环境是不是和正式环境加上索引

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
问题反馈：乐递的应收财务打开用时6.64S @iamforrest 
![6 64s qq 20180404142034](https://user-images.githubusercontent.com/37489976/38291710-8aae22e2-3813-11e8-87e6-6a2ae5fd48b1.png)
http://ledii.itdida.com/caoZuo.xhtml
账户：222@QQ.COM
密码：123456

**Comment by WENLINRONG** [comment]
测试通过
