### ISSUE TITLE
运单欠款，出不了货，日志记录欠费件无法 扫描记录 我们需要留下记录

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#700]
运单欠款，出不了货，日志记录欠费件无法 扫描记录 我们需要留下记录
![image](https://user-images.githubusercontent.com/37489976/42262798-f1950c78-7f9e-11e8-8d31-07a5dd69a408.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
