### ISSUE TITLE
包号明细展开速度优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#704]
1，包号明细展开速度优
![image](https://user-images.githubusercontent.com/37489976/42282355-cc3b2d24-7fd8-11e8-88eb-0ff00d51bc4a.png)
2，主界面 ，扫单助手，APP包号保存，过滤空格，回车符等特殊符号

**Comment by johnnyZchan** [comment]
@WENLINRONG   速度已优化，请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
