### ISSUE TITLE
包号列表，运单移除后，包号列表的数据没有实时汇总刷新，显示的汇总数据还是运单移除前的汇总数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#705]
包号列表，运单移除后，包号列表的数据没有实时汇总刷新，显示的汇总数据还是运单移除前的汇总数据
![image](https://user-images.githubusercontent.com/37489976/42302071-777267e4-804b-11e8-8d04-60003347f1bc.png)

**Comment by iamforrest** [comment]
帮我再过一下，搜索一下，
1. 所有的setBaoHao setTuiHuoPiHao setFaHuoPiHao setShouHuoPiHao
2. 然后看看有没有都调用了dealPiHao 的方法，
3. 并且有没有都考虑了老新号都调用了

@mrrc333

**Comment by mrrc333** [comment]
shou_huo_pi_hao等均已搜过，只发现一处，已修正

**Comment by mrrc333** [comment]
@WENLINRONG
