### ISSUE TITLE
已退货的运单，修改基本的申报信息，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#71]
已退货的运单，修改基本的申报信息，系统报错
![qq 20180403113258](https://user-images.githubusercontent.com/37489976/38227882-f1be1140-3732-11e8-9d19-6509fcce9112.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
