### ISSUE TITLE
统计分析----应收分析，应付分析，成本分析界面，查数据没反应 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#713]
统计分析----应收分析，应付分析，成本分析界面，查数据没反应 
![image](https://user-images.githubusercontent.com/37489976/42381600-2c58e8fe-8164-11e8-89fc-549912a59b38.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
