### ISSUE TITLE
客户流水账界面客户名不能表头搜索

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#718]
客户流水账界面客户名不能表头搜索
代理l流水账界面代理名不能表头搜索

![qq 20180709060743](https://user-images.githubusercontent.com/37489976/42424440-e6063334-833e-11e8-9744-1f427dc7fdb5.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
