### ISSUE TITLE
增加批量打印转单发票按钮

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#720]
![image](https://user-images.githubusercontent.com/37174434/42430374-6ea12f78-8371-11e8-9b59-501cbf7e91ea.png)
注意，不需要增加 批量打印 按钮。 直接使用导出 选择模版 。
要设计模版上传到模版中心供选择，模版样式在档案下载一个参考。

**Comment by WENLINRONG** [comment]
@likeasb 问题反馈：
转单号跟转单条码没显示，运单勾了四票，只能打印出来一票
![qq 20180709203854](https://user-images.githubusercontent.com/37489976/42450943-509b0b4e-8375-11e8-8ede-ff8fc55da182.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
