### ISSUE TITLE
应收财务也有CTRL+f 的搜索，窗口最小化，所以缩小应收财务的窗口的时候 按的CTRL+F 搜索框也缩小的应收财务里面

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#722]
应收财务也有CTRL+f 的搜索，窗口最小化，所以缩小应收财务的窗口的时候 按的CTRL+F 搜索框也缩小的应收财务里面
![image](https://user-images.githubusercontent.com/37489976/42487725-d604f0f0-8434-11e8-9ef5-19854b4b151e.png)

**Comment by mrrc333** [comment]
@WENLINRONG
