### ISSUE TITLE
客户流水账，代理流水账界面的汇总要按照币种显示汇总数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#723]
客户流水账，代理流水账界面的汇总要按照币种显示汇总数据

**Comment by WENLINRONG** [comment]
<img width="1007" alt="qq 20180710153841" src="https://user-images.githubusercontent.com/37489976/42496294-1033c9b0-8415-11e8-81ee-cf3f6f12e76a.png">

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
