### ISSUE TITLE
发货批号里面的运单减少或者增加或者撤销发货时（撤销发布，运单的发货批号要清除），发货批号的汇总数据不会即时汇总计算 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#735]
发货批号里面的运单减少或者增加或者撤销发货时（撤销发布，运单的发货批号要清除），发货批号的汇总数据不会即时汇总计算 
![image](https://user-images.githubusercontent.com/37489976/42550515-dd9c0e04-8504-11e8-96f3-282e67f12687.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
问题反馈：这个运单撤销后，发货批号汇总的还是不对

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
