### ISSUE TITLE
汇率管理这个，要继续优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#740]
汇率管理这个，要继续优化
1. 取消生效字段，没意义
2. 无论生效和失效，都要尽量做到无缝衔接生效失效时间
3.另外， 如果出现这样的：
如果已经有一个汇率 20180301~20180331
用户新建一个汇率，20180201~20180531
第一条要删除（假删除）

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
