### ISSUE TITLE
急急急，触发器 条件 增加 寄件人（或寄件公司） 是否为黑名单

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#742]
现在有 黑名单 未更新前 进来的预报运单等，没有触发问题件或其他预警。
增加触发器这个条件。让她们先用起来先。
![image](https://user-images.githubusercontent.com/37174434/42562370-2f396184-852e-11e8-99df-81b02354c7bb.png)

**Comment by WENLINRONG** [comment]
经测试。已解决
