### ISSUE TITLE
 fedex从系统参数设置，自动识别美东美西-

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#754]
fedex从系统参数设置，自动识别美东美西-
1.美国西岸USA1邮编范围:80000-81699,83200-83999,84000-84799,85000-86599,89000-89899,90000-96699,97000-97999,98000-99499)，
2.其他地区ROW为美国东岸USA2
在系统参数里面增加这个设置，根据邮编自动分别美国的东岸西岸，要能够自定义设置适用于是哪个承运商或者是某一个收货渠道

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
