### ISSUE TITLE
客户端岗位修改没加入岗位变更日志。

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#758]
客户的岗位（包括 港前 港后 应收付财务等。）变更要增加日志，修改人是谁。什么时候修改的。

![ff3e7200-8388-4770-bcd9-e0b500dbabe3](https://user-images.githubusercontent.com/37174434/42612158-4f127c2c-85cc-11e8-8aaa-74029974aaa8.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
