### ISSUE TITLE
包号列表多加状态列

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#763]
1. 包号表加多一个字段：zhuang_tai, -100为异常，其它的值对接运单的操作状态的值
2. 如果这个包号里面的单件的所有运单状态都是一致的，包号的状态就是该运单操作状态；否则就是-100（异常）
3. 包号列表加上这个新的表头：状态，并且表头搜索支持下拉式菜单的过滤（全部，异常，待收货。。。）
4. 包号展开的单件明细也多加一列：状态，对接运单的操作状态

**Comment by iamforrest** [comment]
这个包号状态要通过运单表的触发器同步，如果运单的操作状态有变化，运单的所有单件的的相关包号都要同步一下。我附件有一个通过包号得到状态的函数，可能对你有用。可以参考。


DELIMITER ;;

CREATE FUNCTION `baoHaoZhuangTaiValue`(baoHao varchar(100)) RETURNS int
COMMENT '包号状态值' 
BEGIN 
DECLARE ztText int DEFAULT 0;
DECLARE rowCount int DEFAULT 0;
select
  count(1) as count,
  max(cao_zuo_zhuang_tai) as cao_zuo_zhuang_tai
into
  rowCount, ztText
from
  (
    select
      yun_dan.`cao_zuo_zhuang_tai`,
      count(1) as count
    from
      yun_dan_dan_jian
      inner join yun_dan on (yun_dan.id = yun_dan_dan_jian.yun_dan_id)
    where
      yun_dan_dan_jian.bao_hao = baoHao
    group by
      yun_dan.`cao_zuo_zhuang_tai`
  ) a;
    if rowCount > 1 then
      RETURN -100;
    else
      return ztText;
    end if;
  END;;
  
DELIMITER ;

**Comment by iamforrest** [comment]
这个包号状态要通过运单表的触发器同步，如果运单的操作状态有变化，运单的所有单件的的相关包号都要同步一下。我附件有一个通过包号得到状态的函数，可能对你有用。可以参考。这个包号状态要通过运单表的触发器同步，如果运单的操作状态有变化，运单的所有单件的的相关包号都要同步一下。我附件有一个通过包号得到状态的函数，可能对你有用。可以参考。
[itdida.txt](https://github.com/itdida/itdida-issues/files/2187724/itdida.txt)

**Comment by iamforrest** [comment]
@johnnyZchan 走hotfix

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
