### ISSUE TITLE
 对账单导出这个，多选变成导出一个网页了

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#765]
对账单导出这个，多选变成导出一个网页了
![image](https://user-images.githubusercontent.com/37489976/42624632-67711c3e-85f8-11e8-954a-1e571f8bb5ab.png)

**Comment by iamforrest** [comment]
@WENLINRONG 

改了导出和下载的的代码，所以
1. 应收界面的几个导出都要测试一下
2. 应付和主界面的导出随机抽样试一下
3. 打印label和下载文档的都随机抽样测试一下

**Comment by WENLINRONG** [comment]
经测试，已解决
