### ISSUE TITLE
待上网，待签收，已签收的运单，点重算应收费用，重算应付费用，重算销售费用，系统不会执行重算

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#774]
待上网，待签收，已签收的运单，点重算应收费用，重算应付费用，重算销售费用，系统不会执行重算
![qq 20180713111717](https://user-images.githubusercontent.com/37489976/42670604-7aec1c5a-868e-11e8-9dc1-f299eef7209a.png)

**Comment by iamforrest** [comment]
@WENLINRONG 
1. 测试一下，手动重算，现在还会不会限制
2. 再测试一下，如果改已签收的运单的计费重，会不会触发重算（按道理，不应该自动重算）

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
