### ISSUE TITLE
代理流水账界面，客户流水账界面针对当个核销金额对应的核销审核明细实现导出明细数据

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#777]
代理流水账界面，客户流水账界面针对当个核销金额对应的核销审核明细实现导出明细数据
![image](https://user-images.githubusercontent.com/37489976/42672031-fbf160ce-8695-11e8-801d-400cd39e6968.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认
