### ISSUE TITLE
收货批号，发货批号，退货批号，包号界面增加排序功能

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#778]
收货批号，发货批号，退货批号，包号界面增加排序功能
![image](https://user-images.githubusercontent.com/37489976/42672773-81385a0e-869a-11e8-9c37-d2f35899b058.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
