### ISSUE TITLE
应付财务，应收财务界面 待对账审核-审核通过-登记收款单 ，银行账号无法输入选择

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#780]
应收财务界面 待对账审核-审核通过-登记收款单 ，银行账号无法输入选择
![image](https://user-images.githubusercontent.com/37489976/42677834-9aa71da8-86af-11e8-941e-afeefcfab44f.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
