### ISSUE TITLE
一代：应收财务，应付财务界面的有些人工添加的费用的币种没显示（修复历史数据）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#781]
一代：应收财务，应付财务界面的有些人工添加的费用的币种没显示（修复历史数据）

![image](https://user-images.githubusercontent.com/37489976/42679469-9c683a8c-86b4-11e8-87c8-8847c2c564c5.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
