### ISSUE TITLE
包号 增加多选，全选功能。第二图是bug，打不开详情，请修复。

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#782]
![image](https://user-images.githubusercontent.com/37174434/42681808-4deda606-86bb-11e8-97eb-6fb470d2867c.png)
![image](https://user-images.githubusercontent.com/37174434/42681927-9814e6c2-86bb-11e8-9bb3-668d1651cab7.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
