### ISSUE TITLE
众鑫通需求：收货界面及基本界面的载入按钮去掉

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#79]
收货界面及基本界面的载入按钮去掉
![_qq 20180312104447](https://user-images.githubusercontent.com/37489976/38406498-d1a0ad10-39a7-11e8-940b-2d9e71866360.png)
2，基本界面跟补录资料的界面的地址载入要优化，公司名或者收件人名输入完毕后，再选择载入（可输可选）

**Comment by WENLINRONG** [comment]
恩源  12:56:59

这个自动加载的，还是要赶快去掉

**Comment by iamforrest** [comment]
@WENLINRONG 这个我记得整理过逻辑出来的，麻烦列出来之前说的逻辑

**Comment by WENLINRONG** [comment]
之前讨论的逻辑是：
第一：把载入按钮去掉
第二：要输入完收件公司名后者收件名后，在选择是否载入收件地址 @iamforrest

**Comment by WENLINRONG** [comment]
张总(203278)  16:16:01
我记得了，我当时的意思是保留autocompete，但是每个输入框均不做关联

**Comment by WENLINRONG** [comment]
载入按钮已去掉
