### ISSUE TITLE
客户档案的联系人手机必填的取消限制 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#790]
客户档案的联系人手机必填的取消限制 
![qq 20180714084435](https://user-images.githubusercontent.com/37489976/42719080-ef61d1f6-8742-11e8-8753-f68aa9477673.jpg)

**Comment by iamforrest** [comment]
这个可以关闭了吧，陈曦之前做了登录名

**Comment by WENLINRONG** [comment]
已解决
