### ISSUE TITLE
ALPHA测试环境：扫单助手，主界面操作添加的包号的运单，数据进入不到包号列表----ALPHA

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#793]
ALPHA测试环境：扫单助手，主界面操作添加的包号的运单，数据进入不到包号列表
![image](https://user-images.githubusercontent.com/37489976/42720057-2276012e-8753-11e8-8871-b8ab9129beef.png)

**Comment by WENLINRONG** [comment]
操作步骤如下：
1.在主界面添加包号，数据进入不到包号列表
![image](https://user-images.githubusercontent.com/37489976/42720070-5e8b4444-8753-11e8-8da9-94b7bbd733c8.png)
![image](https://user-images.githubusercontent.com/37489976/42720134-07c44b46-8754-11e8-802d-41a8d768eaa7.png)
2，扫单助手--扫入运单后，添加包号，数据也进入不到包号列表

**Comment by iamforrest** [comment]
@WENLINRONG 数据库没更新成功，让鮑更新好了重启了再试一下。
