### ISSUE TITLE
应付财务日志和应收财务日志的表头搜索加上autocomplete

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#795]
![image](https://user-images.githubusercontent.com/2240276/42720530-2d14471e-875b-11e8-872f-6865d5482d17.png)
![image](https://user-images.githubusercontent.com/2240276/42720531-2ff8d5bc-875b-11e8-9a54-5e913c9f4497.png)

性能要保证，需要加索引的要加索引

**Comment by WENLINRONG** [comment]
问题反馈：应收财务日志，应付财务日志，打开系统报错 @likeasb 
![image](https://user-images.githubusercontent.com/37489976/42722968-a7835518-8787-11e8-8455-1f302de5e9b9.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
