### ISSUE TITLE
下载档案和打印档案的进一步优化

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#797]
1. 打印档案目前没有代码支持downloadURL不为空，保存路径为空的场景，这个场景，应该尝试从downloadURL去下载，然后再输出给客户端打印。建议将这个逻辑方法从下载和打印单独封装出一个方法来调用。

2. 下载和打印，都不支持友好错误信息。也即是说，先genertaeFile，再去下载或者调用 printJS('other/xiaZaiDangAn.xhtml?id=#{dangAn.id}')。

完成之后，在hotfix造假数据给文林荣测试一下。

附：
p:fileDownload 的友好错误信息处理，可以参考：
https://stackoverflow.com/questions/5584673/primefaces-filedownload-error-handling

![image](https://user-images.githubusercontent.com/2240276/42721835-20d651fe-8774-11e8-86c2-57bad1f6afef.png)

**Comment by iamforrest** [comment]
@WENLINRONG 这个测试点很简单，就是点击各种类型的档案，回归测试一下，看看能不能正确打印和下载就行了。类型包括：

0：其他，1：label，2：发票，3：转单lebel，4：转单发票，5：日终报告

**Comment by WENLINRONG** [comment]
@iamforrest 系统下载都报下载失败
![image](https://user-images.githubusercontent.com/37489976/42732180-048d2c4e-884f-11e8-8634-ed2cdda0b57b.png)

**Comment by WENLINRONG** [comment]
经测试，以解决
