### ISSUE TITLE
众鑫通需求：扫单助手-补录资料的功能（类似于运单基本界面的修改）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#8]
众鑫通需求：扫单助手-补录资料的功能（类似于运单基本界面的修改）
[扫单助手-补录资料.pdf](https://github.com/itdida/itdida-issues/files/1823756/-.pdf)

**Comment by iamforrest** [comment]
@WENLINRONG 请测试

**Comment by WENLINRONG** [comment]
@@问题反馈：
1，补录资料界面的 城市名，邮编，州名录入后，提交保存，数据保存不了 
![qq 20180322102544](https://user-images.githubusercontent.com/37489976/37747811-e137141e-2dbb-11e8-9b50-5fe53357a43a.png)
2，选择完寄件人对接地址后，之前录入的收件人地址，城市名，邮编，州名 就被自动清除了
![qq 20180322102936](https://user-images.githubusercontent.com/37489976/37747825-00d58aee-2dbc-11e8-90b7-a70cc0de30e2.jpg)
3，收件地址修改对接地址后，已填写的城市名，邮编，州名被自动清除 
![qq 20180322103035](https://user-images.githubusercontent.com/37489976/37747869-32c5f354-2dbc-11e8-929b-3b9f45b23b9f.png)
@likeasb

**Comment by iamforrest** [comment]
小明家里有事，不能跟进，转给林锦斌跟进

**Comment by iamforrest** [comment]
@tomlamcn 小明家里有事，不能跟进，帮忙跟进

**Comment by WENLINRONG** [comment]
经测试，已解决
