### ISSUE TITLE
主查询界面----多行过滤后，双击运单，基本界面打不开

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#80]
多行过滤后，双击运单，基本界面打不开
![qq 20180406200413](https://user-images.githubusercontent.com/37489976/38420343-f81c73ce-39d5-11e8-9636-ceffb1d200f4.png)

**Comment by iamforrest** [comment]
@WENLINRONG 已解决，等会部署测试环境测试一下

**Comment by WENLINRONG** [comment]
经测试，已解决
