### ISSUE TITLE
打单录入，录单界面，基本界面，客户端的自动载入是否一并取消

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#800]
单证那边因为自动输入这个导致 掉包了。尽快给它取消掉。
![image](https://user-images.githubusercontent.com/37174434/42722776-bd3b06d8-8784-11e8-844b-a0afd7f03822.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
