### ISSUE TITLE
费用登记增加批量粘贴运单号来输入费用。

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#802]
如果不能全匹配，这里还是判断输入的是客户单号吧。
![image](https://user-images.githubusercontent.com/37174434/42722995-fac7829e-8787-11e8-9cbd-383c77edec91.png)

**Comment by iamforrest** [comment]
@mrrc333 直接改为文本框来做，一行一个运单。

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
@mrrc333 问题反馈：应付财务的费用登记界面没做
![image](https://user-images.githubusercontent.com/37489976/42732481-01d8845c-8855-11e8-805e-e5b7ac4eab15.png)
****

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
应付财务打不开

**Comment by WENLINRONG** [comment]
经测试，已解决
