### ISSUE TITLE
ALPHA的总账表---打开客户账户跟代理账户，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#807]
ALPHA的总账表---打开客户账户跟代理账户，系统报错
![alpha --- qq 20180714193145](https://user-images.githubusercontent.com/37489976/42724007-dbba691a-879c-11e8-91f0-7b13a6045f54.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG   现在以hotfix环境为准再次确认下吧，我并未重现出该问题
