### ISSUE TITLE
包号列表---部分运单移除后，总实重数汇总错误 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#816]
包号列表---部分运单移除后，总实重数汇总错误 
![image](https://user-images.githubusercontent.com/37489976/42730618-898988a8-882b-11e8-89c8-5ede1207cda8.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试。已解决
