### ISSUE TITLE
包号列表的站点列显示下拉式选择

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#817]
包号列表的站点列显示下拉式选择
![qq 20180715123809](https://user-images.githubusercontent.com/37489976/42730650-1c6e33f8-882c-11e8-86ca-d52e57040a1e.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
