### ISSUE TITLE
API的黑名单判定优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#827]
API的黑名单判定优化

![image](https://user-images.githubusercontent.com/37489976/42743059-03a3d4dc-88f3-11e8-9f6f-4df8e4cf1011.png)

**Comment by iamforrest** [comment]
@WENLINRONG 重点检查一下：
1. 黑名单导入的时候，如果关键字段空的，不应该导入的
2. 重点关注各个黑名单需要检查的场景到底判断准确还是不准确。

**Comment by WENLINRONG** [comment]
张总(203278)  18:57:58
上次不是确定了需求了么
1. 对接了api的运单 并且 
2. 承运商是DHL 并且 
3. 使用运单寄件公司 并且 
4 运单寄件公司不为空

满足这四个条件，才去判断黑名单
安琪(285549096)  18:58:56
是这个，需求上应该是判定发货渠道才对。现在判定的是收货渠道，
@小明 这个就是要判定发货渠道了，不是收货渠道

**Comment by WENLINRONG** [comment]
经测试，已解决
