### ISSUE TITLE
正是环境的应付财务的列表字段缺少代理名称的字段

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#83]
正是环境的应付财务的列表字段缺少代理名称的字段
![qq 20180407115434](https://user-images.githubusercontent.com/37489976/38450995-81ab94d8-3a5a-11e8-8b16-682abaf232c1.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by tomlamcn** [comment]
刚应该发布好了的。

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by WENLINRONG** [comment]
正式环境缺少的字段：发货渠道，公式，客户名，备注，报价编号，报价名称，报价生效时间 @tomlamcn

**Comment by tomlamcn** [comment]
@chenguolin123
