### ISSUE TITLE
客户端----问题处理界面的代理编号，发货渠道 要去掉 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#831]
客户端----问题处理界面的代理编号，发货渠道 要去掉 
![---- qq 20180716155841](https://user-images.githubusercontent.com/37489976/42748088-67d6effc-8911-11e8-9e21-cec600a64189.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
