### ISSUE TITLE
联邦获取转单号失败

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#84]
联邦获取转单号失败 
单号是：1223333333334444445
http://he.iruda.co/caoZuo.xhtml
用户名是：tomlam@gmail.com
密码是：123456
![qq 20180407191401](https://user-images.githubusercontent.com/37489976/38454334-2db2afa4-3a98-11e8-8209-4f3e2e13f0b1.png)

**Comment by iamforrest** [comment]
@WENLINRONG 部署正式环境再测试一下

**Comment by WENLINRONG** [comment]
经测试，已解决
