### ISSUE TITLE
急。录单优化

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#843]
优化一下， 扫描预输入单好回车报出来后 鼠标可以直接去到收货渠道。
问题解决：
1，从扫描预报出来的，跳到件数后没有出来条码 打印。有勾打印条码的选项的。
2，从扫描预报出来的，输入重量没进入下面子系统单号重量，而是生成一票新的子系统单号
3，从扫描预报出来的， 状态没去到 待收货，还是预报状态的。
4， 录单输入错误的提示闪的太快
![image](https://user-images.githubusercontent.com/37174434/42802379-5aec3c2e-89d5-11e8-8664-4af2fb876b60.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
