### ISSUE TITLE
复制运单和主界面的各种操作

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#847]
我优化了主界面的底层，包括复制运单

1.测试复制运单
2. 回归测试确认收货，发货，切换条点一下等等

**Comment by WENLINRONG** [comment]
复制运单跟确认排货异常 @likeasb

**Comment by likeasb** [comment]
![111](https://user-images.githubusercontent.com/8414932/42828035-60680c1a-8a1a-11e8-8754-618b585c4bad.png)
![222](https://user-images.githubusercontent.com/8414932/42828042-63a44cf4-8a1a-11e8-912b-2d36941f47e5.png)
![333](https://user-images.githubusercontent.com/8414932/42828047-668094c8-8a1a-11e8-81d6-d7ec5249a7b7.png)

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：侧栏分组查询后在全部界面连续复制，跳转到草稿界面时，数据显示异常
![image](https://user-images.githubusercontent.com/37489976/42874946-0209ad18-8ab5-11e8-8017-c7cd9f0d669b.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG    请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
