### ISSUE TITLE
付款单审核权限错误，跟收款单权限混淆在一起了，如果没分配收款单审核权限，导致付款单审核权限不能用 

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#851]
付款单审核权限错误，跟收款单权限混淆在一起了，如果没分配收款单审核权限，导致付款单审核权限不能用 
![image](https://user-images.githubusercontent.com/37489976/42814121-cc2ea4f6-89f5-11e8-8daf-a03938472d0a.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
