### ISSUE TITLE
包号子列表增加表头搜索查询功能

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#868]
![d678dd7b-d6d1-4727-8189-a644e39ee4ef](https://user-images.githubusercontent.com/37174434/42921338-31258380-8b4e-11e8-9315-eaa9fa84a9f7.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
