### ISSUE TITLE
录单界面，没有填写客户，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#870]
录单界面，没有填写客户，系统报错
![qq 20180719143340](https://user-images.githubusercontent.com/37489976/42925505-fefcaaec-8b60-11e8-9662-a3e4fddae25b.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
