### ISSUE TITLE
将客户编号默认为客户登录账号第一个人的’登录账号

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#877]
将客户编号默认为客户登录账号第一个人的’登录账号
张总  15:10:29
他新建联系人的时候，如果登录账号不存在这个客户编号的，在登录账号那里默认先写好客户编号
改成这样

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
