### ISSUE TITLE
系统的轨迹显示跟承运商上轨迹的显示时间排序对不上（系统轨迹没有按照轨迹的插入时间排序显示）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#91]
系统的轨迹显示跟承运商上轨迹的显示时间排序有问题（转单号是2807629764）承运商网址是：http://www.cn.dhl.com/zh/express/tracking.html?AWB=2807629764&brand=DHL
![qq 20180408130018](https://user-images.githubusercontent.com/37489976/38463441-9c32f0ac-3b2d-11e8-9f01-025cf36ff76d.png)
承运商最新轨迹更新时间是当地(USA)的4月7日21：54分
![usa 4 7 21 54 qq 20180408130035](https://user-images.githubusercontent.com/37489976/38463447-acd0f576-3b2d-11e8-98ad-cca02da04610.png)

**Comment by iamforrest** [comment]
@WENLINRONG 部署测试一下，目前按照时间来排序了（但是不排除有时差的误差）

**Comment by WENLINRONG** [comment]
当轨迹有当地时间轨迹时，系统轨迹显示的轨迹顺序跟承运商的轨迹顺序对不上 @iamforrest 
![qq 20180408190437](https://user-images.githubusercontent.com/37489976/38466753-e196d4a6-3b5f-11e8-9664-0759ba80287a.png)
承运商显示的轨迹
![image](https://user-images.githubusercontent.com/37489976/38466762-35066566-3b60-11e8-8fa5-7c83a4434207.png)

**Comment by WENLINRONG** [comment]
存在时间差
