### ISSUE TITLE
系统参数支持系统排货规则，重算规则，暂时尚未对接逻辑

### ISSUE THREAD

**Issue by chenguolin123** [itdida/itdida-issues#911]
系统参数支持系统排货规则，重算规则，暂时尚未对接逻辑

**Comment by WENLINRONG** [comment]
@chenguolin123 问题反馈:排货规则重算保存后，系统报错
![image](https://user-images.githubusercontent.com/37489976/42991712-04aa11c2-8c39-11e8-91a0-3727fd83711c.png)
