### ISSUE TITLE
黑名单拦截修复

### ISSUE THREAD

**Issue by likeasb** [itdida/itdida-issues#925]
收货录入，api，排货，修改运单等黑名单拦截修复

**Comment by WENLINRONG** [comment]
@likeasb 问题反馈：
1，  录单（用户端，客户端），打单录入没拦截
2，基本修改渠道跟修改寄件人，提交保存，报错
![image](https://user-images.githubusercontent.com/37489976/43036818-2433bece-8d3a-11e8-88a9-3cd126d6f6cb.png)
