### ISSUE TITLE
使用运单寄件公司名的对接承运商打单的，转单LB跟发票没有对接显示对应的运单寄件公司名

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#929]
使用运单寄件公司名的对接承运商打单的，转单LB跟发票没有对接显示对应的运单寄件公司名
![lb qq 20180722080948](https://user-images.githubusercontent.com/37489976/43041040-5582d260-8d87-11e8-84d1-820b2778d6f2.jpg)
![image](https://user-images.githubusercontent.com/37489976/43041053-9a42428c-8d87-11e8-8c52-77f6d0638882.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
