### ISSUE TITLE
基本界面重算应收费用，重算应付费用的按钮弹出的界面标题错误（显示的界面标题都是重算销售）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#94]
基本界面重算应收费用，重算应付费用的按钮弹出的界面标题错误（显示的界面标题都是重算销售）
![image](https://user-images.githubusercontent.com/37489976/38464657-eb5a92e6-3b43-11e8-880e-c34b73669181.png)

**Comment by tomlamcn** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
