### ISSUE TITLE
包号，批号还是改回数据库触发器模式

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#947]
java漏洞太多了，很不好控制，客户总是抱怨包号表不同步。笔记有修复包号的语句，你可以借鉴一下。

1. 删掉所有dealPiHao的调用
2. 改为MYSQL触发器调用。

![image](https://user-images.githubusercontent.com/2240276/43115220-910a68c0-8f35-11e8-8f5f-ae534dab2c64.png)

**Comment by chenguolin123** [comment]
包号的我先做了， 其他没做 @johnnyZchan

**Comment by WENLINRONG** [comment]
经测试，已解决
