### ISSUE TITLE
包号列表，改为弹窗模式

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#948]
1.  双击弹窗
2. 下面有个按钮，“查看明细”，点击可以查看所选包号的所有明细（可多个包号）
3. 明细弹出框跟expand出来的差不多，有明细和汇总即可。
4. 其他的批号类型的，也按照此改动做。

![image](https://user-images.githubusercontent.com/2240276/43115380-3e695c74-8f36-11e8-9152-4cbc7172ca02.png)

**Comment by johnnyZchan** [comment]
@WENLINRONG    包号页面已经完成   其他几个批号页面还没有完成，  可以另开git跟踪  也可以测试完包号页面再把这个git返回给我也行

**Comment by WENLINRONG** [comment]
经测试，已解决
