### ISSUE TITLE
多行过滤的大小写敏感问题

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#952]
如果多行过滤里面，有些单号是英文字符，举个例子，含有小写字母，数据库里面是大写的，结果是：
搜索可以搜索出来，但是会进入不存在清单。

**Comment by iamforrest** [comment]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/2240276/43128125-bcfba240-8f63-11e8-9fe4-9e689fdb50ea.png">

**Comment by WENLINRONG** [comment]
经测试，已解决
