### ISSUE TITLE
系统留言功能开放出来针对所有问题件都能留言（不限定是否是问题件）

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#956]
系统留言功能开放出来针对所有问题件都能留言（不限定是否是问题件）

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
问题反馈：正常件留言对接不到日志
![image](https://user-images.githubusercontent.com/37489976/43198624-e88c499e-9041-11e8-8044-9718ef475fff.png)

**Comment by mrrc333** [comment]
@WENLINRONG 问题件留言已复原，这个也麻烦测下~留言放至批量修改中

**Comment by WENLINRONG** [comment]
经测试，已解决
