### ISSUE TITLE
客户端---档案界面针对客户自己上传档案的删除按钮隐藏，不让客户删除

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#957]
客户端---档案界面针对客户自己上传档案的删除按钮隐藏，不让客户删除
![image](https://user-images.githubusercontent.com/37489976/43130082-68698878-8f68-11e8-8006-85e09aff2c9b.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
