### ISSUE TITLE
总账表对应列表的排序，显示，汇总的优化

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#959]
总账表对应列表的排序，显示，汇总的优化

**Comment by WENLINRONG** [comment]
![qq 20180725121513](https://user-images.githubusercontent.com/37489976/43179259-6e9c7ac4-9004-11e8-8045-7bac558d37a6.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG  请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
