### ISSUE TITLE
应收财务，应付财务界面----按照费用视图显示时，左侧栏分组的汇总数显示错误，现在显示的还是按票的合计数

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#96]
应收财务，应付财务界面----按照费用视图显示时，左侧栏分组的汇总数显示错误，现在显示的还是按票的合计数
![qq 20180408172356](https://user-images.githubusercontent.com/37489976/38465706-cb850380-3b51-11e8-8ff5-ee782a3c7b9a.png)

**Comment by iamforrest** [comment]
@WENLINRONG 已解决，部署测试环境测试一下

**Comment by WENLINRONG** [comment]
经测试，已解决
