### ISSUE TITLE
总账表---核销审核明细增加显示收货时间，费用的财务状态，重量列，金额列且核销明细增加汇总跟排序

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#960]
总账表---核销审核明细增加显示收货时间，费用的财务状态，重量列，金额列且核销明细增加汇总跟排序
![image](https://user-images.githubusercontent.com/37489976/43298794-1e4d9c56-918a-11e8-8ba3-28fb8c549162.png)

![--- qq 20180725122441](https://user-images.githubusercontent.com/37489976/43179573-400d4524-9006-11e8-9bbd-5c50824c67f5.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG 请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决

**Comment by johnnyZchan** [comment]
@WENLINRONG    没有汇总数据的bug已修复

**Comment by WENLINRONG** [comment]
经测试，已解决
