### ISSUE TITLE
银行流水表把撤销核销审核的对应的收款单付款单的流水号显示到备注里

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#961]
银行流水表把撤销核销审核的对应的收款单付款单的流水号显示到备
![qq 20180725124656](https://user-images.githubusercontent.com/37489976/43180176-37be6d78-9009-11e8-8aba-1e1c95f59bb9.jpg)
注里

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
