### ISSUE TITLE
联邦LB支持条形码扫描

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#970]
主要测试：
1. 联邦获取转单号，看看LB pdf能不能生成成功。如果有错误，会在运单操作日志看到的。
2. 多测试几个单试试
3. 获取成功之后，抽样把PDF给我看看，我可以告诉你成功处理的PDF的特征怎么样的，一般PDF的文件大小会大一些，大概100多K以上，条形码会长一些。

**Comment by WENLINRONG** [comment]
经测试，已解决
