### ISSUE TITLE
总账表---客户余额表界面，代理余额表界面增加导出按钮

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#981]
总账表---客户余额表界面，代理余额表界面增加导出按钮
![--- qq 20180726165919](https://user-images.githubusercontent.com/37489976/43252653-9f21e05c-90f5-11e8-9da4-3fb332b11e9b.jpg)

**Comment by johnnyZchan** [comment]
@WENLINRONG   请测试确认

**Comment by WENLINRONG** [comment]
经测试，已解决
