### ISSUE TITLE
主界面增加应收财务 字段

### ISSUE THREAD

**Issue by tomlamcn** [itdida/itdida-issues#982]
增加客户的 岗位选择那里可以搜索
录单 和 修改基本的重量可以到100000
主界面增加应收财务 字段

**Comment by WENLINRONG** [comment]
问题反馈：
1，应收财务没有对接数据
![image](https://user-images.githubusercontent.com/37489976/43262758-d9ff5718-9113-11e8-9f29-3933ed17d3fa.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
