### ISSUE TITLE
退货批号自动修复

### ISSUE THREAD

**Issue by iamforrest** [itdida/itdida-issues#989]
麻烦也看看退货批号的数据是否准确

**Comment by WENLINRONG** [comment]
@iamforrest 问题反馈：
扫单助手操作的退货数据没有进入退货批号的列表
![image](https://user-images.githubusercontent.com/37489976/43271213-8961788e-9129-11e8-9c8a-6c938ece28b5.png)
![image](https://user-images.githubusercontent.com/37489976/43271244-9c0e1384-9129-11e8-84fb-867a95db8e80.png)

**Comment by WENLINRONG** [comment]
经测试，已解决
