### ISSUE TITLE
组织架构---全选后导出，系统报错

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#990]
组织架构---全选后导出，系统报错
![--- qq 20180727105909](https://user-images.githubusercontent.com/37489976/43299313-48b58c7c-918c-11e8-9728-6d404b13cfb9.jpg)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
