### ISSUE TITLE
日常收支----分公司不能表头过滤查询

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#995]
日常收支----分公司不能表头过滤查询
![---- qq 20180727181947](https://user-images.githubusercontent.com/37489976/43315830-d34dd4e2-91c9-11e8-94f2-9ac5d4206265.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，已解决
