### ISSUE TITLE
人工添加的轨迹，系统要记录操作日志

### ISSUE THREAD

**Issue by WENLINRONG** [itdida/itdida-issues#996]
1，人工添加的轨迹，系统要记录操作日志,
2，轨迹界面增加一列人工跟系统 
![image](https://user-images.githubusercontent.com/37489976/43317683-663be144-91d0-11e8-835c-f44ba99ef7a6.png)

**Comment by mrrc333** [comment]
@WENLINRONG

**Comment by WENLINRONG** [comment]
经测试，要解决
